### ISSUE TITLE
[Plugin] Need expert help with nativescript-mediafilepicker plugin

### ISSUE THREAD

**Issue by relez** [NativeScript/ios-runtime#1001]
Hi there, I am trying to get some expert help from the NativeScript team in order to fix an issue on iOS. The author can not figure out what is going on and its a nice plugin the community could use on their apps.

This is the link for the issue:

[https://github.com/jibon57/nativescript-mediafilepicker/issues/32](https://github.com/jibon57/nativescript-mediafilepicker/issues/32)

Thanks!

**Comment by mbektchiev** [comment]
This issue is not related to the iOS runtime and I'm closing it. Let's continue discussion in the original one.
