### ISSUE TITLE
How to get IPv6 address?

### ISSUE THREAD

**Issue by DeepakArora76** [NativeScript/ios-runtime#1017]
I am able to retrieve IPv4 address using **inet_ntop** and **interop.Reference** technique. The API **inet_ntop** is capable of getting an IPv6 address in Objective-C using  **sockaddr_in6** and as well **sockaddr_in**.  I am unable to find any reference of **sockaddr_in6** in NativeScript, and when I tried using **sockaddr_in** to get IPv6 I get garbage address. The correct approach requires **sockaddr_in6**.

Appreciate your valuable tips/help to solve this problem.

> declare function inet_ntop(p1: number, p2: interop.Pointer | interop.Reference<any>, p3: string, p4: number): string;
> 
> interface sockaddr_in {
> 	sin_len: number;
> 	sin_family: number;
> 	sin_port: number;
> 	sin_addr: in_addr;
> 	sin_zero: interop.Reference<number>;
> }
> declare var sockaddr_in: interop.StructType<sockaddr_in>;
> 
>

**Comment by mbektchiev** [comment]
Or you can try something more hacky involving a little bit of pointer arithmetics which should also work. Since the `sin6_addr` member is located at offset 8, you can pass a Pointer to 8 bytes after the `sockaddr_in` variable that you have. E.g. something like: 
```TS
// if `in` is a Pointer to the `struct sockaddr_in` 
const sin6_addr = in.add(8); 
inet_ntop(AF_INET6, sin6_addr, ...);
```

Here's the `sockaddr_in6` definition for reference:
```C
struct sockaddr_in6 {
	__uint8_t	sin6_len;	/* length of this struct(sa_family_t) */
	sa_family_t	sin6_family;	/* AF_INET6 (sa_family_t) */
	in_port_t	sin6_port;	/* Transport layer port # (in_port_t) */
	__uint32_t	sin6_flowinfo;	/* IP6 flow information */
	struct in6_addr	sin6_addr;	/* IP6 address */
	__uint32_t	sin6_scope_id;	/* scope zone index */
};
```

**Comment by mbektchiev** [comment]
@DeepakArora76, I've managed to write a JS function which logs the IPv4 and IPv6 addresses of all adapters using the following code. I hope this helps:

```JS
function dumpIPs() {
    const ppAddrs = interop.alloc(interop.sizeof(interop.types.id));

    if (getifaddrs(ppAddrs) == -1) {
        console.log("getifaddrs failed");
        return;
    }

    const pAddrs = new interop.Reference(interop.Pointer, ppAddrs).value;
    let addrs = new interop.Reference(ifaddrs, pAddrs).value;
    for (; addrs; addrs = addrs.ifa_next && new interop.Reference(ifaddrs, addrs.ifa_next).value) {
        if (addrs.ifa_addr) {
            let sin_addr = null;
            let address_type = "";
            if (addrs.ifa_addr.value.sa_family == 2 /*AF_INET*/) {
                let addr_in = interop.Reference(sockaddr_in, addrs.ifa_addr).value;
                sin_addr = addr_in.sin_addr;
                address_type = "IPv4";
            } else if (addrs.ifa_addr.value.sa_family == 30 /*AF_INET6*/) {
                sin_addr = interop.handleof(addrs.ifa_addr).add(8);
                address_type = "IPv6";
            }

            if (sin_addr) {
                const name = NSString.stringWithUTF8String(addrs.ifa_name);
                const address_buf = interop.alloc(50);
                const res = inet_ntop(addrs.ifa_addr.value.sa_family, sin_addr, address_buf, 80);
                if (!res) {
                    console.warn(`inet_ntop for adapter ${name} failed with error: ${errno}`);
                } else {
                    console.log(`Adapter name: ", ${name}, ${address_type}: ${NSString.stringWithUTF8String(address_buf)}`);
                }
            }
        }
    }
    freeifaddrs(pAddrs);
}
```

**Comment by DeepakArora76** [comment]
@Martin Bektchiev: Good evening. Many many thanks for your superb support. Appreciated a lot. Your sample code gave me an insight into the **interop** feature. I was using it in a naive way, but now I have a good understanding of it.

I using NativeScript with Angular, and I had to tune your solution to something presented below:

 ``` javascript
 dumpIPs() {
    const ppAddrs = new interop.Reference<interop.Reference<ifaddrs>>();

    if (getifaddrs(ppAddrs) == -1) {
      console.log("getifaddrs failed");
      return;
    }

    const pAddrs = ppAddrs.value;
    let addrs = new interop.Reference(ifaddrs, pAddrs).value;
    for (; addrs; addrs = addrs.ifa_next && new interop.Reference(ifaddrs, addrs.ifa_next).value) {
      if (addrs.ifa_addr) {
        let sin_addr = null;
        let address_type = "";

        const ifa = <interop.Reference<sockaddr>>(addrs.ifa_addr);
        if (ifa.value.sa_family == 2 /*AF_INET*/) {
          let addr_in = new interop.Reference(sockaddr_in, addrs.ifa_addr).value;
          sin_addr = addr_in.sin_addr;
          address_type = "IPv4";
        } else if (ifa.value.sa_family == 30 /*AF_INET6*/) {
          sin_addr = interop.handleof(addrs.ifa_addr).add(8);
          address_type = "IPv6";
        }

        if (sin_addr) {
          const name = NSString.stringWithUTF8String(addrs.ifa_name); 
          
          // I am not using interop.alloc(50) as this does not work in Angular. inet_ntop requires string argument
          const address_buf = NSString.stringWithString("test").UTF8String;

          const res = inet_ntop(ifa.value.sa_family, sin_addr, address_buf, 80);
          if (!res) {
            console.warn(`inet_ntop for adapter ${name} failed with error: ${/*errno*/__error()}`);
          } else {

            const name = NSString.stringWithUTF8String(addrs.ifa_name);
            console.log(`Adapter name: ${name}, ${address_type}: ${NSString.stringWithUTF8String(address_buf)}`);
          }
        }
      }
    }
    freeifaddrs(pAddrs);
  }

```

**Comment by DeepakArora76** [comment]
If you have time, please take a look into my solution which works well on Angular platform. If you foresee any problems with the sample above, please share views. 

Once again thanks for your help. In my opinion the issue can be marked as close.

**Comment by mbektchiev** [comment]
>const address_buf = NSString.stringWithString("test").UTF8String;
>const res = inet_ntop(ifa.value.sa_family, sin_addr, address_buf, 80);

Although it may work, this is undefined behaviour in C. You're passing the temporary buffer returned from the `UTF8String` to `inet_ntop`. I'd suggest using `interop.alloc` as it ensures that you're the owner of the memory buffer and that it has the size that you've requested. To circumvent the strict typing requirement to pass a string, I'd write it like this:
```TS
const address_buf = interop.alloc(80);
const res = inet_ntop(ifa.value.sa_family, sin_addr, <string><unknown>address_buf, 80);
```

**Comment by DeepakArora76** [comment]
>  NSString.stringWithString("test").UTF8String;

I was uncomfortable using the above line for the same reason as you pointed out. I used it due to lack of my understanding of interop. What you have shown here `<string><unknown>address_buf` I could not have come up on my own. 

Just wondering about `<unknown>`. As far as I know, there is no such data type called as **unknow**. I found a link which is about [`unknown`: a less-permissive alternative to `any`](https://github.com/Microsoft/TypeScript/issues/10715) and narrowing using **unknown** in this [link](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html).

I will give a try later today to your suggested approach. 

Thanks again for your enlightening me.

**Comment by DeepakArora76** [comment]
@mbektchiev Finally, with your help, I managed to have the right implementation. It took a while for me as the installed toolchain was a bit outdated.

Thanks a bunch for this assistance👍 

I believe the patch that you made [fix(typings): Accept Pointers and References for CString arguments](https://github.com/NativeScript/ios-metadata-generator/commit/487034c2eaefbcb44a156a9791d1e1c1fda766ab) does not require me to apply locally to my development environment. If I am not wrong the patch will be available in the minor release cycle of NS.

And, if I have understood the patch, then the expression `<string><unknown>address_buf` will not be needed in future.

It was a pleasure to interact and learn from you.

Have a good day ahead.

**Comment by mbektchiev** [comment]
It was a pleasure to help! 

Yes, that's right - it would make the casts unneeded and the patch should be released with the next minor version of {N}.
