### ISSUE TITLE
Installing a pod crashes the app without an error

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/ios-runtime#1020]
@michaelpwilson commented on [Tue Nov 20 2018](https://github.com/NativeScript/NativeScript/issues/6588)

**Environment**

 - CLI: 5.0.1
 - Cross-platform modules: 5.0.3
 - Android Runtime:
 - iOS Runtime: 5.0.0
 - Plugin(s): 

**Describe the bug**

I'm trying to install a pod ([Onfido 10.1.0](https://github.com/onfido/onfido-ios-sdk)) with a fresh clone of [nativescript-plugin-seed](https://github.com/NativeScript/nativescript-plugin-seed).

Everything works perfectly before I try to add this [podfile](https://github.com/michaelpwilson/nativescript-onfido/blob/master/src/platforms/ios/Podfile) to ```src/platforms/ios```, the app installs and builds with no errors.

But whenever I try to open the app it closes straightaway, no error or anything. Log trace doesn't give anything useful relating to Cocoapods or a NativeScript issue. 

**To Reproduce**

1). Follow instructions for [nativescript-plugin-seed](https://github.com/NativeScript/nativescript-plugin-seed)
2). Add latest version of [Onfido 10.1.0](https://github.com/onfido/onfido-ios-sdk) to ```src/platforms/ios``` Podfile.
3). App crashes and no errors are present.

**Expected behavior**

An error should be present or the app should load, as no code has been written yet.

**Sample project**

[https://github.com/michaelpwilson/nativescript-onfido](https://github.com/michaelpwilson/nativescript-onfido)

**Additional context**

I'm using XCode 10.1 and MacOS 10.13.6.

---

@NickIliev commented on [Wed Nov 21 2018](https://github.com/NativeScript/NativeScript/issues/6588#issuecomment-440562899)

The app crashes with Dynamic library error.
```
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /Users/niliev/Library/Developer/CoreSimulator/Devices/81C0D8DE-36F3-4612-AFBB-BA543A1DD1C8/data/Containers/Bundle/Application/DC7838E4-6AA0-4FB0-AF39-2800B336402D/demo.app/Frameworks/Onfido.framework/Onfido
  Reason: image not found
```

Seems related to [this issue](https://github.com/onfido/onfido-ios-sdk/issues/37)

**Comment by NickIliev** [comment]
@michaelpwilson in the buildd.xcconfig of the plugin include the following line

```
ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES
```

Related to [https://stackoverflow.com/questions/32771796/dyld-library-not-loaded-rpath-libswiftavfoundation-dylib](https://stackoverflow.com/questions/32771796/dyld-library-not-loaded-rpath-libswiftavfoundation-dylib)

**Comment by michaelpwilson** [comment]
Thank you very much @NickIliev, this fixed my issue!
