### ISSUE TITLE
Feature Request: Provide automatic garbage collection triggering by the {N} Runtimes

### ISSUE THREAD

**Issue by mbektchiev** [NativeScript/ios-runtime#1035]
**Is your feature request related to a problem? Please describe.**
When large native objects are created and referenced from JavaScript they do not cause memory pressure for the garbage collection and could remain alive for too long. This sometimes causes memory issues and even app termination.

**Describe the solution you'd like**
Provide a setting in `app/package.json` for configuring a heuristics algorithm implemented in the {N} runtime, which will periodically check for the current memory footprint of the application and forcefully trigger JS garbage collections depending on memory usage. 

The idea of the algorithm is to check the current memory footprint on each N (configurable number) of native calls. When the application's memory usage has increased by at least `M`(another configurable value) megabytes it will immediately trigger a garbage collection.

**Describe alternatives you've considered**
Leave users to manually call `__collect` whenever they decide in the application logic. This however doesn't create a best practice approach and could lead to other problems. Having one recommended approach is preferable although we know that it may have cases which will not benefit or could even suffer (most likely performance-wise) from it. That's why it should be switched off by default. 

**Additional context**
It turns out that a single garbage collection cycle might not be enough to free a (large) object. This is the case when a long chain of `JS -> Native -> JS -> Native ... ` references leads to the given object. During the first cycle only the first `JS -> Native` part of the chain will be released. The reason is that all `Native` instances keep strong references to JS fields and they cannot be marked for collection until the last `Native` instance referring them is destroyed. On the other hand, all JS instances also hold strong references to the Native fields and they can't be destroyed until the last JS instance holding a reference is garbage collected.

The GitHub Issue for the Android Runtime is https://github.com/NativeScript/android-runtime/issues/1232

**Comment by lini** [comment]
(android only) Can we somehow know if GC ran in native (e.g. event, memory consumtion falls, etc) and simply trigger the V8 GC then? When native memory starts to fill up, the Java GC should run and try to free up some. We register this and call the corresponding JS method to start GC there as well.

**Comment by mbektchiev** [comment]
I'm not sure but we should implement this in the android-runtime instead of require plugins/apps to handle it themselves. 

We will open a separate feature request in the android-runtime repository as well and I suggest that we discuss all details regarding the android implementation there.

**Comment by NathanaelA** [comment]
How heavy is the `_collect` statement?    Why not just call `_collect` four times on navigation away from a page.  That should free up most memory as the UIViewController, and UIView are freed up in passes 1 & 2 and the first two levels of the screen should then get cleaned up.

**Comment by pana-cc** [comment]
@NathanaelA we used to do that when navigating away from a page. There are cases where you put several pages in the navigation stack and then discard them. That used to trigger huge delays, like you click "back" and the app freezes for two seconds.

We've discussed with @mbektchiev that there may be a way to keep an eye on the memory usage of the app and hint the JS VM to run async GC more frequently in general, while when the memory pressure is high, to run blocking GC passes. That sounds a little bit better since it will not be blocking apps in cases there is enough free memory.

Please note the approach I described earlier is merely a hint how native APIs can be used in a way that they are more easily collected by the GC and overall reducing both CPU and memory usage. When apps are crashing with OOM it should be possible to attach Xcode instruments, find what native instances cause the memory spike and try to detangle the native things.

**Comment by mbektchiev** [comment]
@NathanaelA That might be a solution but you never know in advance how many GC passes will be required in order to reclaim the memory. Moreover it might be the last element which occupies the most amount of it. A rather extreme example would be if you have a deeper UI components hierarchy and there's a video player at the lowest level that keeps a video file loaded in memory. 

Another peculiarity is that due to the way native instances are being delay-released, calling several `__collect`s  in row doesn't actually manage to get rid of the chain -- rather it's required to queue them on the main loop, by calling `setTimeout(__collect, 0);` for example. 

All in all, it seems that there are a lot of details that need to be considered in order to successfully cope with these memory issues and IMO the runtime has to provide a mechanism for that.

**Comment by NathanWalker** [comment]
@mbektchiev it’d be nice if developers had a property to set on certain objects which the system could consider when being more aggressive or not to collect. For example a developer could flag a Page object with ‘gc=“auto”’ or ‘gc=“aggressive” if they knew that page contains a lot of memory hungry components that when navigated away they would want the system to aggressively recollect memory from by calling the GC multiple times or as @pana-cc mentioned potentially traversing the tree to agreesively free up the stack up to the top node with one GC pass or whichever strategy ended up being most effective.

Idea would be to allow a view property to be set on nodes which the system would consider when doing GC passes and how aggressive it should be with an apps view hierarchy.
