### ISSUE TITLE
possibility to use ObjC/Swift files directly In apps or modules

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/ios-runtime#1041]
This is the iOS counterpart of the [android one](https://github.com/NativeScript/android-runtime/issues/1172)

This would be very very useful when you want quick categories or quick class extensions while keeping things as native as possible.

**Comment by mbektchiev** [comment]
Support is provided in the CLI with https://github.com/NativeScript/nativescript-cli/issues/3807
