### ISSUE TITLE
The debugger does not stop at application launch 

### ISSUE THREAD

**Issue by vchimev** [NativeScript/ios-runtime#1063]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.1.1
 - Cross-platform modules: 5.1.1
 - iOS Runtime: 5.1.1

**Describe the bug**

The debugger doesn't stop at application launch when: `--debug-brk` option is passed and the application's root is not a frame, i.e. SideDrawer, TabView.

**To Reproduce**

```
tns create my-tab-ts --template tns-template-tab-navigation-ts
cd my-tab-ts
tns debug ios --debug-brk
```

**Expected behavior**

The debugger to stop at application launch.

**Sample project**

Could be caused by: https://github.com/NativeScript/ios-runtime/blob/master/src/debugging/TNSDebugging.h#L362-L373.

**Comment by mbektchiev** [comment]
Fixed with https://github.com/NativeScript/nativescript-cli/pull/4296 and https://github.com/NativeScript/ios-runtime/pull/1073
