### ISSUE TITLE
Wait for debugger

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/ios-runtime#107]
- [x] When the app is launched for debugging, it should wait for the debugger to connect before executing any client JavaScript. The debugger back-end in the app should wait all break-points to be sent from the front-end, so if the user had placed a break-point on the second line of the app.js, the app should break on it. The app should not be able to execute it before the break-point is received from the front-end.

 - [x] All "debugger;" statements in the app should cause the debugger to break.

 - [x] Allow the app to be launched in "debug break", and have it break in the first statement of user code. It should execute the built-in JavaScript (e.g. the require implementation).

 - [ ] Profile startup time

**Comment by PanayotCankov** [comment]
The `tns debug ios --debug-brk` command in the CLI is supposed to break on `debugger;` statements. The runtime will wait for the debugger to connect before executing any JavaScript. However it will not wait for all breakpoints to be set so it is possible for a JavaScript statement to be executed before the debugger has the chance to send all breakpoints to the runtime.

**Comment by jasssonpet** [comment]
This requires newer version of JavaScriptCore.

**Comment by fealebenpae** [comment]
This is implemented in #245.
