### ISSUE TITLE
tns-platform-declarations - In objc!SafariServices.d.ts is declared the deprecated class SFAuthenticationSession instead of ASWebAuthenticationSession

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/ios-runtime#1090]
_From @alexmeia on March 6, 2019 10:59_

**Describe the bug**
Version 5.2.0 of _tns-platform-declarations_ still references to the deprecated class
[SFAuthenticationSession](https://developer.apple.com/documentation/safariservices/sfauthenticationsession) instead of the analogous, but not deprecated, [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession).
SFAuthenticationSession will not be usable starting from iOS 13, so an update to the iOS platform declarations id needed.

_Copied from original issue: NativeScript/NativeScript#6992_

**Comment by alexmeia** [comment]
Actually the definition for ASWebAuthenticationSession is available in [objc!AuthenticationServices.d.ts](https://github.com/NativeScript/NativeScript/blob/master/tns-platform-declarations/ios/objc-x86_64/objc!AuthenticationServices.d.ts#L174), as pointed out by @mbektchiev in the original thread. I din't look there.
