### ISSUE TITLE
Can't compile runtime with CMake 3.14

### ISSUE THREAD

**Issue by DiThi** [NativeScript/ios-runtime#1097]
Followed readme instructions to the letter. Linked cmake and llvm-config to /usr/local/bin/.

We want to compile the runtime to then modify with custom features like we did with Android's. But maybe I'm not doing it right... I selected the project "NativeScript" in Xcode.

Fails with this message:

    echo "Performing configure step for 'WebKit'"
    Performing configure step for 'WebKit'
    cd /Users/dev/ios-runtime/cmake-build/WebKit-prefix/src/WebKit-build && /Applications/CMake.app/Contents/bin/cmake --debug=all -DCMAKE_SYSTEM_PROCESSOR=arm "-DCMAKE_XCODE_ATTRIBUTE_SUPPORTED_PLATFORMS=iphoneos iphonesimulator" -DCMAKE_XCODE_EFFECTIVE_PLATFORMS=-iphoneos -iphonesimulator -DPORT=Mac -DENABLE_REMOTE_INSPECTOR=OFF -DENABLE_INTL=OFF -DJSC_OBJC_API_ENABLED=OFF -DUCONFIG_NO_COLLATION=ON -Wno-dev -DCMAKE_C_COMPILER_WORKS=YES -DCMAKE_CXX_COMPILER_WORKS=YES -DHAVE_QOS_CLASSES=ON -DENABLE_WEBCORE=OFF -DENABLE_WEBKIT_LEGACY=OFF -DENABLE_WEBKIT=OFF -DENABLE_STATIC_JSC=1 -DENABLE_JIT=ON -DENABLE_EXCEPTION_SCOPE_VERIFICATION=ON -DUSE_CAPSTONE=ON -DCMAKE_C_COMPILER_ID=AppleClang -DCMAKE_CXX_COMPILER_ID=AppleClang -DCMAKE_C_COMPILER=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -DCMAKE_CXX_COMPILER=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -DCMAKE_CXX_STANDARD_REQUIRED=ON "-DCMAKE_CXX_FLAGS_RELWITHDEBINFO=-O2 -g -DNDEBUG -O3" -GXcode /Users/dev/ios-runtime/src/WebKit
    -- The CMake build type is: RelWithDebInfo
    CMake Error at Source/cmake/WebKitCompilerFlags.cmake:115 (message):
      Compiler with C++17 support is required
    Call Stack (most recent call first):
      Source/cmake/WebKitCommon.cmake:57 (include)
      CMakeLists.txt:157 (include)

    -- Configuring incomplete, errors occurred!
    See also "/Users/dev/ios-runtime/cmake-build/WebKit-prefix/src/WebKit-build/CMakeFiles/CMakeOutput.log".
    See also "/Users/dev/ios-runtime/cmake-build/WebKit-prefix/src/WebKit-build/CMakeFiles/CMakeError.log".
    make: *** [/Users/dev/ios-runtime/cmake-build/WebKit-prefix/src/WebKit-stamp/Debug-iphoneos/WebKit-configure] Error 1
    Command /bin/sh failed with exit code 2

**Comment by mbektchiev** [comment]
I think that you may have missed [this step](https://github.com/NativeScript/ios-runtime/blob/master/README.md#local-development):
`sudo ./src/webkit/Tools/Scripts/configure-xcode-for-ios-development`

Can you try repeating it? Also, it may help if you attach the `CMakeOutput.log` and `CMakeError.log` files if the issue persists.

**Comment by DiThi** [comment]
I'm sure I did that step but maybe I was missing something at that moment.
I've built an app the usual way (with tns instead of compiling the runtime
myself) and that works. I repeated the steps on the readme for the runtime
and it doesn't. Should I remove the build directory and try again?

Attached are the log files, the ones named webkit are in
`cmake-build/WebKit-prefix/src/WebKit-build/CMakeFiles`

**Comment by mbektchiev** [comment]
I noticed that you are using CMake version 3.13.4, but we currently require version 3.3.2. Can you please switch to it and see how it goes?

**Comment by mbektchiev** [comment]
iOS Runtime should now build correctly with the latest version of CMake
