### ISSUE TITLE
tns build ios using Xcode 9 instead of 10

### ISSUE THREAD

**Issue by lukecolburn** [NativeScript/ios-runtime#1121]
**Environment**
 - CLI: 5.3.1
 - Cross-platform modules: 5.2.1
 - iOS Runtime: 5.3.1

**Describe the bug**
We're using the Azure DevOps hosted macOS agents to create CI builds, which we then push out to TestFlight using fastlane. This has been working fine for us until April 1, when Apple started blocking publishing of SDK 11 apps. This is the error we get from fastlane and in an email from Apple:
"SDK Version Issue. This app was built with the iOS 11.4 SDK. All iOS apps submitted to the App Store must be built with the iOS 11 SDK or later, included in Xcode 9 or later. Further, starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later."

The AzureDevops agents have Xcode 10 installed, but they also have 9 and 8 installed, and based on the build logs it looks like tns is selecting version 9 for building. When we build this same app using Sidekick cloud build, it works fine.

**To Reproduce**
This is the tns command we run after setting up the necessary prerequisites:
`tns build ios --bundle --release --for-device --provision 7bb152be-f761-4257-9efa-d48833d98955 --path spendid-tns`

**Expected behavior**

Tns build uses Xcode 10 for building instead of 9

**Comment by mbektchiev** [comment]
Hi, Luke. The version which `tns` uses is the same as the `xcodebuild` command would use. To print the currently selected version you can execute `xcode-select -p` and to select a different version -- `xcode-select -s <path to Xcode.app/Contents/Developer>`. I hope this helps!

**Comment by lukecolburn** [comment]
Sweet, that was just what we needed. Thanks!
