### ISSUE TITLE
How to create plugin from shared framework in NativeScript 

### ISSUE THREAD

**Issue by Saravanan109587** [NativeScript/ios-runtime#1124]
I am trying to use TriPos Payment Gateway IOS SDK  "https://developer.vantiv.com/docs/DOC-1915" in my cross platform mobile application,So that i have a plan to create custom native script plugin using that shared sdk.
but unfortunately i could not found any complete documentation or example to build a custom plugin from Third party native ios Shared sdk.

They have given me a Shared library called "triPOSMobileSDK.framework",It contains only .h files not any module files. i have clone plugin seed from "https://github.com/NativeScript/nativescript-plugin-seed.git" and include m y framework inside ios folder,and i dont know what is the next step or how to consume the functions inside a framework using plugin.

Here is my Plugin source "https://github.com/Saravanan109587/TriPosNativePLugin"

Can any one help me out to way for creating custom plugin from third party sdk?

**Comment by NathanaelA** [comment]
@Saravanan109587 - I have several tutorials on my Blog; https://fluentreports.com/blog

**Comment by Saravanan109587** [comment]
@NathanaelA  thanks for reply,
I have followed your steps and  when i try to create typescript declaration for my ios library using 
"**TNS_TYPESCRIPT_DECLARATIONS_PATH="$(pwd)/typings" tns build ios [--for-device] [--release]**" i am getting the following error .

**TNS_TYPESCRIPT_DECLARATIONS_PATH=$(pwd)/typings : The term 
'TNS_TYPESCRIPT_DECLARATIONS_PATH=$(pwd)/typings' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ TNS_TYPESCRIPT_DECLARATIONS_PATH="$(pwd)/typings" tns build ios [--fo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (TNS_TYPESCRIPT_...=$(pwd)/typings:Strin 
   g) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException**

ran **npm i tns-platform-declarations --save-dev** before that commannd.
i have tried to run this cmd from root directory and from src directory i got the same result?
am i missing something?

**Comment by Saravanan109587** [comment]
and there is no module.map file in library ,i have created module.map file inside **platform/ios/module.map** as

framework module Tripos {
    umbrella "triPOSMobileSDK.h"
    export *
    module * {export *}
}

and my  build.cconfig is empty.
Can you please advise me for this issue ?

**Comment by NathanaelA** [comment]
@Saravanan109587 - 
1. You are doing this on a Mac correct?
2. Are you using a standard Bash terminal?

From my instructions at http://fluentreports.com/blog/?p=227

I just did this on my mac:
![image](https://user-images.githubusercontent.com/850871/56097159-5b47c600-5eb6-11e9-9f7e-876201628eb3.png)

And when it was done I had a new `tsc` folder; inside 
![Screenshot from 2019-04-14 13-09-41](https://user-images.githubusercontent.com/850871/56097382-d1e5c300-5eb8-11e9-99ba-9276cfbd2de3.png)


Inside the new `tsc` folder was the folders that had the typings...

---

As for your second issue; the module map file needs to be inside the framework; and the framework should be in the **platform/ios/** folder like this:
![Screenshot from 2019-04-14 13-27-15](https://user-images.githubusercontent.com/850871/56097397-11acaa80-5eb9-11e9-9cbb-9234fe25472f.png)


and in the platforms/ios/<yourframework> file should contain a modulemap file like this:
![Screenshot from 2019-04-14 13-24-22](https://user-images.githubusercontent.com/850871/56097384-d9a56780-5eb8-11e9-8165-237581debccb.png)

There are ways to put a modulemap in your platforms ios folder if the framework is a prebuild system module; but that is a corner case.

**Comment by Saravanan109587** [comment]
last time i have tried in windows,now i am trying the same in mac i am getting different Error like below

![Tripos1](https://user-images.githubusercontent.com/38832874/56122649-830b5c80-5f90-11e9-97a0-992d076dbafa.JPG)


When i run the same inside src folder of my plugin i am getting the below Error

![TriPos2](https://user-images.githubusercontent.com/38832874/56122727-a9c99300-5f90-11e9-9e32-3a0784093080.JPG)

looks like it searching directory in src/app/App_Resources
and Every time i run this command it generates src/app folder inside platforms/ios.

from which path i need to run this command whether from root folder or from src folder?

and one more question is ,Since this typing generation is only for debugging and intellisence can i use the framework without generating typescript declaration?If yes then do i need to create wrapper for every functions which is inside that framework?

For example ,
my framework has function in **VTP+Sale.h** like 
-(void)processSaleRequest:(VTPSaleRequest *)request completionHandler:(VTPSaleApiCompletionHandler)completionHandler errorHandler:(VTPErrorHandler)errorHandler;

if i want to call the above function in my app ,then what i need to do in my plugin ?how to call the ablve function using my plugin?

can you please help me out ?
Thanks.

**Comment by mbektchiev** [comment]
Hi, you should execute `TNS_TYPESCRIPT_DECLARATIONS_PATH="$(pwd)/typings" tns build ios` in a project which uses your plugin (e.g. in the demo app). The typings are not required but it's advisable to generate them, at least because of IntelliSense. 


For calling instance methods on native classes like [processSaleRequest](https://github.com/Saravanan109587/Nativescript-Tripos/blob/master/src/platforms/ios/triPOSMobileSDK.framework/Headers/VTP%2BSale.h#L40) you'll need to retrieve or create a variable from the class and find out the JS name of the method by either looking at the generated typings or the debug metadata in YAML format. You can also guess them by following the algorithm of the metadata generator, which basically concatenates all parameters' names in a single camel case identifier. For the `processSaleRequest` method it should be `processSaleRequestCompletionHandlerErrorHandler`.

**Comment by NathanaelA** [comment]
@Saravanan109587 - 
1. This only works on **Mac** while building an iOS **application**.
2. You have to create a app; (does NOT have to do anything in your plugin YET).  

You can use https://github.com/NativeScript/nativescript-plugin-seed
as a seed to get you started.    Basically you need an **app** (demo), and a **src** folder for the plugin.
Then you put in your plugin framework inside the `src/platforms/ios` folder, and name your plugin info in the `src/package.json` file.    Then you can do

1. `cd demo`
2. `tns plugin add ../src`   <-- This adds your plugin to the demo app (even though it does nothing yet)
3. `TNS_TYPESCRIPT_DECLARATIONS_PATH="$(pwd)/typings" tns build ios`

**Comment by Saravanan109587** [comment]
Wow thanks its worked ,now i can able to create typescript declarations.
for example it generates class named  VTP as below

![TRIPOS1](https://user-images.githubusercontent.com/38832874/56181711-573db480-602c-11e9-885e-a3e572255bc7.JPG)

as @mbektchiev  command to call processSaleRequestCompletionHandlerErrorHandler inside a VTP class ,need to declare a varriable (do i need to create instance for VTP in my demo app)?
if yes then i need to import that VTP class declaration my consumer class of demo app,if i try to do that i am getting Error as  **No exported module as below**

![Tripos2](https://user-images.githubusercontent.com/38832874/56181957-7721a800-602d-11e9-81b0-f5e28e4fd0da.JPG)
ofcourse there is no exported modules?then how should i invoke that?

still i didn't write anything in my plugin source other than insert a framework file and module file.So don't i need to do anything in my plugin ?

**Comment by NickIliev** [comment]
@Saravanan109587 please post how-to related questions in the community channels (like Slack or StackOverflow). The issues section in `ios-repository` is for logging bugs, issues, and feature requests.

CLosing the issue as how-to related.
