### ISSUE TITLE
Cannot access framework headers from source files in App_Resouces/src

### ISSUE THREAD

**Issue by tdermendjiev** [NativeScript/ios-runtime#1136]
From: https://www.nativescript.org/blog/adding-objective-c-code-to-a-nativescript-app

> Adding the cocoapods to the Podfile is not enough to be able to use framework code from the pod. 
When I try to import the header files that represent the interfaces of the objects inside the pod they are not found by the linker.
If you add pods in xcode then the header files of frameworks from the pods are available to the linker.

**Comment by tdermendjiev** [comment]
I wasn't able to reproduce this issue. [Here](https://github.com/tdermendjiev/tns-pod-source) is a sample project I created.

**Comment by mbektchiev** [comment]
Closing as not reproducible.
