### ISSUE TITLE
Question: WASM support possible

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/ios-runtime#1140]
Hey, I was curious to see if JavaScriptCore (which is used for iOS) has the ability to use WASM code; my test which actually worked nicely in the Android NativeScript (v8); but failed right away on iOS.     

Looking through the JSC code base; it appears that Wasm on JSC requires JIT ability to be enabled...   

Simple question; Just to confirm; because Apple does not still allow JIT to be enabled; this means that their is no way to get WASM working on the iOS version of NativeScript, correct?

**Comment by mbektchiev** [comment]
Correct. The WASM feature depends on JIT and it cannot be used without it.

**Comment by NathanaelA** [comment]
@mbektchiev - Thanks for confirming what I was pretty sure of.  

That is a super bummer as the Android v8 engine seems to work with Wasm on Android.   But I suspected based on the source that the non-jit makes Wasm pretty much impossible on iOS.   Silly Apple; just complicates things don't they...

**Comment by luiguild** [comment]
Just 2 cents, now that NativeScript change to V8 on iOS, it will be possible to work with WASM on iOS too?

**Comment by NathanaelA** [comment]
@luiguild - I'm pretty sure thas WASM in v8 also requires JIT ability, and since Apple doesn't allow JIT on any engine except what they ship -- I'm going to say no.  

 BUT -- I'll double check WASM the next time I run the Compatibility chart on the ios v8 egnine -- http://nativescript.rocks/compat/nativescript/

**Comment by luiguild** [comment]
Thank you for your quick response :)

I stay here, hoping and praying that iOS, Safari and the entirely Apple development ecosystem was extintend from humanity as soon as possible :)
