### ISSUE TITLE
compile error in xcode 10.2.21

### ISSUE THREAD

**Issue by azureplus** [NativeScript/ios-runtime#1146]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - iOS Runtime:
 - Android Runtime (if applicable):
 - Plugin(s):

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by NickIliev** [comment]
@azureplus can you share the detailed error log you are receiving? Also please share as much as possible information on your environment & project settings and the commands used to build the project.

**Comment by azureplus** [comment]
ok
