### ISSUE TITLE
Generated typing declaration incorrect when parameters declared with __autoreleasing

### ISSUE THREAD

**Issue by Yermo** [NativeScript/ios-runtime#1164]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.4.2 version and is up to date.
✔ Component tns-core-modules has 5.4.3 version and is up to date.
✔ Component tns-android has 5.4.0 version and is up to date.
✔ Component tns-ios has 5.4.2 version and is up to date.✔ Getting NativeScript 

**Describe the bug**

I am attempting to wrap this Background Geolocation Library for iOS in a NativeScript plugin:

https://github.com/Yermo/background-geolocation-ios

BackgroundGeolocation.a is linked as a "FAT" file.

module.modulemap is here:

https://github.com/Yermo/nativescript-background-geolocation-fbs/blob/ios_integration/src/platforms/ios/include/BackgroundGeolocation/module.modulemap

I am am using the plugin seed and have generated typings using:

`TNS_TYPESCRIPT_DECLARATIONS_PATH="$(pwd)/tsc" tns build ios`

It appears the entry generated for this method 

https://github.com/Yermo/background-geolocation-ios/blob/9689cdcf1ae371d2916a821d7712fe5a6ba0a03d/BackgroundGeolocation/MAURBackgroundGeolocationFacade.m#L105

`- (BOOL) configure:(MAURConfig*)config error:(NSError * __autoreleasing *)outError`

gets generated as:

`configureError(config: MAURConfig): boolean;`

https://github.com/Yermo/nativescript-background-geolocation-fbs/blob/00f95ba4dcc3efcbea398b46c3d81a22acd80350/src/platforms/ios/BackgroundGeolocation.ios.d.ts#L1223

It should be:

`configureError( config: MAURConfig, error: NSError )`
 
**To Reproduce**

clone the plugin project:

https://github.com/Yermo/nativescript-background-geolocation-fbs/tree/ios_integration

`
cd src
npm run plugin.prepare
cd ../demo-angular
TNS_TYPESCRIPT_DECLARATIONS_PATH="$(pwd)/tsc" tns build ios
`
**Expected behavior**

I expect correct typings to be generated for all methods.

I suspect the typings issues are related to the use of __autoreleasing. If I change the source Objc code and remove __autoreleasing, I notice that the typings are correctly generated.

**Comment by mbektchiev** [comment]
@Yermo NSError ** out arguments are treated specially by the {N} Runtime. The behavior is documented [here](https://docs.nativescript.org/core-concepts/ios-runtime/Marshalling-Overview#nserror--marshalling). Basically, you can optionally omit this argument and in case the call returns an error, it will be thrown as a JS exception. This is the preferred way of handling such errors instead of passing a reference and having to manually check whether it was null or not, and that's the reason why in the TS typings we don't generate a second overload which accepts an argument of type `interop.Reference`.

**Comment by Yermo** [comment]
@mbektchiev I apologize that I missed that. I scoured the documentation for hours and did not see that paragraph. That sounds like an excellently designed solution for this scenario. I continue to be very impressed with the work that's been done on NativeScript.
