### ISSUE TITLE
ES6 Features Support List

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#122]
Add a public table with support status for ES6 features.
Start with the:
 - WeakMap
 - WeakRef
 - Map
 - typed arrays

**Comment by fealebenpae** [comment]
This is a good idea for when we migrate to out-of-band versions of JavaScriptCore, but since our current version is the one that shipped with Safari 8, [this should do](http://kangax.github.io/compat-table/es6/#safari71_8).

**Comment by PanayotCankov** [comment]
Since we will be migrating to new JSC version quite soon we'd better postpone this for the 1.2.0 milestone.

**Comment by jasssonpet** [comment]
Here are the JavaScriptCore features for 1.6: https://github.com/NativeScript/webkit/blob/ios/Source/JavaScriptCore/features.json
