### ISSUE TITLE
Icons from inner resource bundle named as its framework are missing

### ISSUE THREAD

**Issue by jibon57** [NativeScript/ios-runtime#1252]
**Environment**
✔ Component nativescript has 6.4.0-2020-01-30-145311-14104 version and is up to date.
✔ Component tns-core-modules has 6.3.2 version and is up to date.
✔ Component tns-android has 6.3.1 version and is up to date.
✔ Component tns-ios has 6.3.0 version and is up to date.

**Describe the bug**
I am trying to implement [DKImagePickerController](https://github.com/zhangao0086/DKImagePickerController) library in one of my project. I have added in my app's `Podfile` like this:
`pod 'DKImagePickerController'`
It's working as expected but camera icon is missing. But if you run demo project from that library then that icon will show. Please check the attached screenshorts
```
let picker = DKImagePickerController.new();
picker.assetType = DKImagePickerControllerAssetType.AllPhotos;
picker.singleSelect = true;
picker.showsCancelButton = true;

picker.didSelectAssets = ((res) => {
})
```
| **From NativeScript:** | **Demo project from repo:** |
|------------------------------------------------------------------------------------------------------------|-----------|
| <img alt="Simulator Screen Shot - iPhone 11 - 2020-02-11 at 19 36 20" src="https://user-images.githubusercontent.com/6080277/74241651-a9ac3800-4d06-11ea-9dc4-b9e02c825845.png" height="350" /> | <img alt="Simulator Screen Shot - iPhone 11 - 2020-02-11 at 19 36 42]" src="https://user-images.githubusercontent.com/6080277/74241672-b466cd00-4d06-11ea-941f-6599687b8d4e.png" height="350" /> |
| | |

What may be the reason? Please give me advice. 

Thanks

**Comment by jibon57** [comment]
I have noticed one interesting thing.. I tried with `beta v8 runtime` by 
`tns platform add ios@beta-v8`
Now that icon is showing 

![Simulator Screen Shot - iPhone 11 - 2020-02-11 at 19 52 13](https://user-images.githubusercontent.com/6080277/74242403-078d4f80-4d08-11ea-950e-a860118c7a1c.png)

**Comment by mbektchiev** [comment]
Hi @jibon57 I tested and cannot reproduce this issue. You haven't shown how you present the image picker. But in my project it works fine with this snippet:
```ObjC
const rootVC = application.ios.nativeApp.keyWindow.rootViewController;
const visibleVC = rootVC.visibleViewController;
visibleVC.presentViewControllerAnimatedCompletion(picker, true, null );
```

**Comment by mbektchiev** [comment]
It turned out I've tried with the latest version. Indeed in 6.3.0 there's an issue, probably it has been fixed along with some other fixes from the 6.4.0 milestone. That's why you've received it when using the v8 version.

**Comment by jibon57** [comment]
@mbektchiev thanks. I just tried in my project again using `6.4.1` but still having same issue. To present picker I was using:

```
let viewController = UIApplication.sharedApplication.keyWindow.rootViewController;
viewController.presentViewControllerAnimatedCompletion(picker, true, null);
```
If you want then I can send you my project by email.

**Comment by jibon57** [comment]
Please check attached project from blank template

[Archive.zip](https://github.com/NativeScript/ios-runtime/files/4199349/Archive.zip)

**Comment by jibon57** [comment]
Please check attached project that I have created from blank template 

[Archive.zip](https://github.com/NativeScript/ios-runtime/files/4199359/Archive.zip)

**Comment by mbektchiev** [comment]
I managed to reproduce it. It seems that as soon as you modify any property of `picker` it starts happening.

**Comment by mbektchiev** [comment]
I'll continue to investigate

**Comment by mbektchiev** [comment]
I tried it from Swift to make sure that this bug isn't related to the DKImagePicker framework itself and it didn't happen, so definitely related to NativeScript in some way

**Comment by mbektchiev** [comment]
@jibon57 The fix should be live with `tns-ios@next` in about an hour. You can test that it works in your project after it's been published.

**Comment by jibon57** [comment]
@mbektchiev thank you! It's working now :)
