### ISSUE TITLE
Fix unit tests CI

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/ios-runtime#126]
At the moment we are using [run-tests.js](https://github.com/NativeScript/ios-runtime/blob/master/build/scripts/run-tests.js) which is using `ios-deploy`. For some reason it is failing to deploy and debug our TestRunner application.

**Comment by PanayotCankov** [comment]
This has been fixed, however we still need to integrate the tns-ios-PR with the tns-ios-pr-tests. We will have to research how to integrate these two in our Jenkins build properly. #149
