### ISSUE TITLE
Problem with MicrosoftCognitiveServicesSpeech

### ISSUE THREAD

**Issue by jibon57** [NativeScript/ios-runtime#1260]
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 6.4.0 and the latest available version is 6.4.1.
✔ Component tns-core-modules has 6.4.2 version and is up to date.
✖ Component tns-android is not installed.
✔ Component tns-ios has 6.4.2 version and is up to date.

I am trying to implement azure Speech SDK for NativeScript iOS following [here][1] but I am getting this error message during build:

    ld: warning: ignoring file /Users/UserName/speechservice/nativescript-azure-cognitiveservices/platforms/ios/MicrosoftCognitiveServicesSpeech.framework/MicrosoftCognitiveServicesSpeech, missing required architecture i386 in file /Users/UserName/speechservice/nativescript-azure-cognitiveservices/platforms/ios/MicrosoftCognitiveServicesSpeech.framework/MicrosoftCognitiveServicesSpeech (2 slices)

I am able to use the service but having that problem. I have created a custom plugin & added in `Podfile`

    pod 'MicrosoftCognitiveServicesSpeech-iOS', '~> 1.9.0'

As it was `static frameworks` so I have added necessary `module.modulemap`. I am OK to use the service but getting error message during build. Also in apple `appstoreconnect` showing `This build is invalid.` Any suggestion please? Thanks

  [1]: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/objective-c/ios/speech-samples

**To Reproduce**
Please check attached project. Run `tns build ios`

**Sample project**
[Archive.zip](https://github.com/NativeScript/ios-runtime/files/4278954/Archive.zip)

**Comment by jibon57** [comment]
@mbektchiev will you please have a look?

**Comment by mbektchiev** [comment]
`MicrosoftCognitiveServicesSpeech` framework is built only for `arm64` and `x86_64`. I suppose you should disable 32-bit architectures via `build.xcconfig` like this:
```
VALID_ARCHS[sdk=iphoneos*] = arm64
VALID_ARCHS[sdk=iphonesimulator*] = x86_64
```

**Comment by jibon57** [comment]
Thank you so much!
