### ISSUE TITLE
Unable to properly marshall data in iOS for type coordinates: interop.Pointer | interop.Reference<CLLocationCoordinate2D>

### ISSUE THREAD

**Issue by Tyler-V** [NativeScript/ios-runtime#1263]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.4.0
 - Cross-platform modules:
 - Android Runtime: 6.4.1
 - iOS Runtime: 6.4.2
 - Plugin(s): 
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.6.2'
pod 'Mapbox-iOS-SDK', '~> 5.6.1'

**Describe the bug**
When attempting to call methods in the mapbox sdk, I am unable to marshall the data into the correct format shown in the examples depicted in Mapbox's documentation for iOS.

In this [documentation provided:](https://docs.mapbox.com/ios/api/maps/5.7.0/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)setVisibleCoordinates:count:edgePadding:direction:duration:animationTimingFunction:completionHandler:)

I am unable to create an object of type `coordinates: interop.Pointer | interop.Reference<CLLocationCoordinate2D>`

```
  setCameraToCoordinates(latLngs: LatLng[], padding?: number, duration?: number): Promise<void> {
    return new Promise((resolve, reject) => {
      const mapView: MGLMapView = this.view.mapView;

      let insets: UIEdgeInsets = {
        top: padding ? padding : 0,
        left: padding ? padding : 0,
        bottom: padding ? padding : 0,
        right: padding ? padding : 0,
      };

      const coordinates: CLLocationCoordinate2D[] = [];
      for (let latLng of latLngs) {
        const coordinate = CLLocationCoordinate2DMake(latLng.lng, latLng.lat);
        coordinates.push(coordinate);
      }

      const array: any = NSArray.arrayWithArray([coordinates]);

      mapView.setVisibleCoordinatesCountEdgePaddingDirectionDurationAnimationTimingFunctionCompletionHandler(
        array,
        coordinates.length,
        insets,
        0,
        duration / 1000,
        CAMediaTimingFunction.functionWithName(kCAMediaTimingFunctionEaseInEaseOut),
        () => {
          resolve();
        }
      );
    });
  }
```

This calls the method without error, but what is passed in is an array of CLLocationCoordinate2D that is marshalled incorrectly. I know this because instead of the provided latLngs array taking me to a central part of the US which works on Android, it takes me off the coast of Africa.

![image](https://user-images.githubusercontent.com/3893234/77192882-4b176e00-6aab-11ea-9d88-648d28d112af.png)
![image](https://user-images.githubusercontent.com/3893234/77192895-4fdc2200-6aab-11ea-8f82-04f24b26c750.png)

**To Reproduce**
Try to create a coordinates object of type interop.Pointer | interop.Reference<CLLocationCoordinate2D>, inspect the values created and coordinates are not correct.

**Expected behavior**
I should be able to create an object of type interop.Pointer | interop.Reference<CLLocationCoordinate2D> where the value is properly mapped and doesn't result in an improper object.

**Sample project**
I would be more than happy to invite you into my plugin's project which has a branch already setup and a demo-angular app which will let you bootstrap and debug this issue with minimal effort to see for yourself. Please let me know otherwise this should be easily reproducible given the steps listed above.

**Comment by mbektchiev** [comment]
I cannot quickly test this, but I think that you should not wrap the JS array in another JS array. If you replace `const array: any = NSArray.arrayWithArray([coordinates]);` with `const array: any = NSArray.arrayWithArray(coordinates);` in the above snippet, I think it should work.

**Comment by mbektchiev** [comment]
Also, you can create a more generic helper function like this:

```TS
function toReferenceToCArray<T>(a: T[], type: interop.Type<T>): interop.Reference<T> {
    const ref = new interop.Reference<T>(type, interop.alloc(interop.sizeof(CLLocationCoordinate2D) * coordinates.length));
    for (let i = 0; i < coordinates.length; i++) {
        ref[i] = coordinates[i];
    }

    return ref;
}

const coordinates: CLLocationCoordinate2D[] = [CLLocationCoordinate2DMake(1, 2), CLLocationCoordinate2DMake(60, 190)];

const refCoords = toReferenceToCArray(coordinates, CLLocationCoordinate2D);
```

**Comment by hazalozturk** [comment]
@mbektchiev Thank you so much, that worked!

**Comment by Tyler-V** [comment]
```
export function toReferenceToCArray<T>(input: T[], type: interop.Type<T>): interop.Reference<T> {
  const ref = new interop.Reference<T>(type, interop.alloc(interop.sizeof(CLLocationCoordinate2D) * input.length));
  for (let i = 0; i < input.length; i++) {
    ref[i] = input[i];
  }

  return ref;
}
```

That indeed marshalls javascript arrays into `interop.Reference<T>` thank you very much for the example, I couldn't find anything in the documentation this is great thanks again @mbektchiev

**Comment by mbektchiev** [comment]
Oops, I noticed an error, if you intend to use this function with other types you should replace `CLLocationCoordinate2D` with `type` ... 😆
