### ISSUE TITLE
Runtime does not support iOS 14.0

### ISSUE THREAD

**Issue by replygirl** [NativeScript/ios-runtime#1273]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - macOS: 10.15.5
 - Xcode: 12.0 beta
 - CLI: 6.7.4
 - Cross-platform modules: 6.5.8
 - iOS Runtime: 6.5.1 (also tested on 6.3.0)
 - Android Runtime (if applicable): N/A
 - Plugin(s):
    ```json
    {
        "nativescript-angular": "^8.21.0",
        "nativescript-animate-sass": "0.0.2",
        "nativescript-appversion": "^1.4.4",
        "nativescript-carousel": "^6.1.1",
        "nativescript-datetimepicker": "^1.2.2",
        "nativescript-fancyalert": "^3.0.9",
        "nativescript-geolocation": "^5.1.0",
        "nativescript-local-notifications": "^4.2.1",
        "nativescript-lottie": "^4.0.1",
        "nativescript-orientation": "^2.2.4",
        "nativescript-permissions": "^1.3.9",
        "nativescript-perms": "^2.0.11",
        "nativescript-plugin-badge": "^1.0.0",
        "nativescript-plugin-firebase": "^10.5.2",
        "nativescript-theme-core": "^2.0.24",
        "nativescript-uuid": "0.0.1",
        "nativescript-web-image-cache": "^5.0.0",
    }
    ```

**Describe the bug**
After an update to Xcode 12 & iOS 14:
- The app builds and installs on the target device, but opens to a blank screen
- `EXC_BAD_ACCESS` is encountered on line 95 of `<...>/platforms/ios/internal/main.m` (`[runtime executeModule:@"./"];`)

**To Reproduce**
_Via Xcode UI:_
1. `tns prepare ios`
2. Open the Xcode workspace
3. Run on an iPhone running iOS 14

_Via tns:_
1. `tns run ios`

**Expected behavior**
The app will behave identically as it did in prior versions of iOS

**Sample project**
Sorry can't share

**Additional context**
I assume this is known/expected and is a general iOS 14 compatibility thing with the runtime

**Comment by rigor789** [comment]
Hey @replygirl - I just published an alpha version with a fix for ios14.

You can give it a try by setting the ios version to `6.6.0-alpha.0-ios14-2020-07-02-159364-01`

Let us know if you run into any issues!

**Comment by rigor789** [comment]
Update: https://github.com/NativeScript/NativeScript/issues/8665#issuecomment-653522656

Closing this issue - to keep the conversation/feedback in a single place.
