### ISSUE TITLE
I cannot see my ios14 device when running tns devices

### ISSUE THREAD

**Issue by RilRil** [NativeScript/ios-runtime#1277]
**Environment**
 - CLI: 6.8.0
 - core: 6.5.12
 - iOS Runtime: 6.5.2
 - Android Runtime (if applicable):

**Describe the bug**
I don't see my iOS 14 simulator when running `tns devices` or `tns debug ios`

**To Reproduce**
install xcode beta 3, launch iOS 14 simulator (iPhone SE 2nd gen) then run `tns devices` in your console
**Expected behavior**
to see my iOS 14 simulator and be able to launch my app on it

thank you in advance

**Comment by mbektchiev** [comment]
Hi, Cyril. You need to make sure that Xcode 14 beta is the selected version when running `xcodebuild` from the command line. You can check the current setting with `xcode-select -p` and change it with `sudo xcode-select -s <path>`.

**Comment by RilRil** [comment]
> Hi, Cyril. You need to make sure that Xcode 14 beta is the selected version when running `xcodebuild` from the command line. You can check the current setting with `xcode-select -p` and change it with `sudo xcode-select -s <path>`.

ah didn't know that. Thanks, I'll try and update this thread

**Comment by RilRil** [comment]
@mbektchiev it works ! thanks a lot
