### ISSUE TITLE
iOS Extensions: Metadata Extensions Availability

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#128]
[This is related to iOS Extensions](https://github.com/NativeScript/ios-runtime/issues/96).

The metadata generator should emit information about the availability in extensions.

**Comment by fealebenpae** [comment]
The current version of the Clang compiler doesn't support the application extension platform. We will have to wait for 3.7.

**Comment by ivanbuhov** [comment]
For now, in "extension mode" we will use the availability information for "app mode". There are few cases where this approach fails and will be fixed with the Clang 3.7 release.
