### ISSUE TITLE
NativeScript could not load bundle file:///<...>/Library/Frameworks/SensorKit.framework

### ISSUE THREAD

**Issue by jessorlisa** [NativeScript/ios-runtime#1281]
**Environment**
 - CLI: 
`├── nativescript@7.0.11`
 - Cross-platform modules: 
`├── @nativescript/core@7.0.13`
 - iOS Runtime: 
`├── @nativescript/ios@7.0.4`
 - XCode Version: 
`12.1 (12A7403)`
 - Plugins:
`├── @nativescript/angular@10.1.7`

**Describe the bug**
When running `ns run ios` on any simulator or device with iOS < 14 the following error occurs:
`NativeScript could not load bundle file:///Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%2013.5.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/SensorKit.framework`

This happens not with iOS 14.
_(From my understanding `SensorKit.framework` is only available in iOS 14.0+, so this is expected.)_

**To Reproduce**
Run NativeScript aoo on any simulator or device with iOS < 14:
```
% ns create test-ios-sensorkit --ng
% cd test-ios-sensorkit
% ns run ios --no-hmr
```

**Expected behavior**
No error or any advice how to find the culprit ;)

**Additional context**

**Comment by jessorlisa** [comment]
Update: This is not happening with the **JSC** runtime `@nativescript/ios@6.5.3`.

**Comment by NathanaelA** [comment]
Please note this is a warning that I believe only happens on Simulators.   This has NO effect on a running application on a simulator OR a real device.    If someone wants to trace down why the warning appears on a simulator; we would accept some fixes; but otherwise it creates no issue against a running application.
