### ISSUE TITLE
Xcode 14 build issue

### ISSUE THREAD

**Issue by kanclalg** [NativeScript/ios-runtime#1298]
I've updated Xcode to 14 and started getting this error:

`error: Build input file cannot be found: '....platforms/ios/build/Debug-iphonesimulator/metadata-x86_64.bin'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'myapp' from project 'myapp')`

versions:
nativescript: 8.3.3
nativescript/ios: 8.2.3

**Comment by rigor789** [comment]
Upgrade your `nativescript/ios: 8.2.3` to `8.3.3`

**Comment by kanclalg** [comment]
Tried yesterday just by removing platforms folder and it didn't worked - got the same error. Tried today with `ns clean` and it started working. Thank you. Closing it.
