### ISSUE TITLE
CFTypeRef marshalling from create or copy function

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/ios-runtime#13]
Currently `CFUUIDCreateString` returns a JS string primitive, which can't be `CFRelease`-d.

More info:
* [Create rule](https://developer.apple.com/library/mac/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029)
* [`CFUUIDCreateString`](https://developer.apple.com/library/mac/documentation/CoreFoundation/Reference/CFUUIDRef/index.html#//apple_ref/c/func/CFUUIDCreateString)

This should also be applicable to `CFDateRef` and `CFNumberRef`.

**Comment by jasssonpet** [comment]
So there are still some functions like `CGPathCreateMutable()` which are not memory managed by the runtime. I'll have a look at them.

**Comment by jasssonpet** [comment]
So it turns out that Swift has hardcoded the following types to be bridged: https://gist.github.com/anonymous/02bdf73ede2f68a6432a

**Comment by jasssonpet** [comment]
We will memory manage only functions in `CF_IMPLICIT_BRIDGING_ENABLED` blocks. I'll modify the metadata generator to respect it.

**Comment by jasssonpet** [comment]
Here is an update with other functions removed: https://gist.github.com/jasssonpet/327862790a058523179c/revisions

**Comment by fealebenpae** [comment]
What's wrong with `UTTypeCopyDescription`? It's memory-managed even though it's not in an `CF_IMPLICIT_BRIDGING_ENABLED` block?

**Comment by jasssonpet** [comment]
`UTTypeCopyDescription` returns JavaScript string which can't be released in NativeScript.

**Comment by fealebenpae** [comment]
I'll create the `JSString` subclass that was supposed to manage primitives in the first place. However, do you think we might have to deal with `CFNumbeRef` values? The subclass-the-primitive approach won't work for numbers.

**Comment by jasssonpet** [comment]
Well, there is `CFNumberCreate()`.

**Comment by fealebenpae** [comment]
I meant to say `CFNumberRef`s returned from functions that would require a manual `CFRelease`.

**Comment by jasssonpet** [comment]
All functions from the list above return `CFStringRef` only, so we shouldn't worry for `CFNumberRef` and `CFDateRef`, imo.

**Comment by fealebenpae** [comment]
We have decided to adopt Swift's [`Unmanaged<Instance>` approach](http://nshipster.com/unmanaged).

**Comment by fealebenpae** [comment]
Fixed by implementing the Unmanaged return type in #386
