### ISSUE TITLE
.dSYM not available in latest releases

### ISSUE THREAD

**Issue by jnorkus** [NativeScript/ios-runtime#1300]
This [documentation](https://v7.docs.nativescript.org/core-concepts/ios-runtime/how-to/dsym-package) specifies that .dSYM files should be available as release assets.

However, they are only available up to version 6.5.1.

Is there any other way to obtain these files?

**Comment by rigor789** [comment]
They should be inside the `NativeScript.xcframework` in newer releases (in the published package, so either in `node_modules/@nativescript/ios` or after preparing/building the project, it would get copied to the `platforms/ios` folder.
