### ISSUE TITLE
Handle memory pressure like WebProcess does

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/ios-runtime#136]
We should trigger GC when a low memory notification is recieved.

Remove this when done: https://github.com/NativeScript/ios-runtime/blob/36258e534faea66a6aa05a7f3f9e87cdeeef9b22/tests/TestRunner/app/ApiTests.js#L255

**Comment by jasssonpet** [comment]
Looks like there are no memory notifications sent in this test, so the `collect` call should stay.

Also in iOS simulator memory warnings seem not to be supported.

**Comment by fealebenpae** [comment]
When and what `malloc` call fails? If it is an allocation that we control perhaps we will be able to catch it and force a collection and then try again, similar to what the JavaScriptCore heap does?

**Comment by jasssonpet** [comment]
This is the one: https://github.com/WebKit/webkit/blob/master/Source/bmalloc/bmalloc/VMAllocate.h#L127

**Comment by fealebenpae** [comment]
Thanks, I'll take a look and see if anything can be done.
