### ISSUE TITLE
Optimize require of JavaScript modules

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/ios-runtime#139]
We could try to make fewer file systems operations on each require if possible. This takes about 100ms of about 1000ms startup time on iPhone 5 at the moment.

An alternative is: https://github.com/NativeScript/nativescript-cli/issues/489

**Comment by fealebenpae** [comment]
I've been looking at [SystemJS](https://github.com/systemjs/systemjs) for some time and they have support for bundles. It's worth taking a look.
