### ISSUE TITLE
3rd party static libraries: Integrate Static Frameworks with the CLI Plugins Mechanism

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#147]
Subtask of #62

It only seems convenient to ask the users wrap static libraries that go with headers in a framework.

For example in case you have the libMyLibrary.a and a few headers that go with it (like the [MagTek](http://www.magtek.com/support/software/programming_tools/) library) you can wrap it as:
```
MyLibrary.framework
├── MyLibrary <- libMyLibrary.a with the "lib" prefix and ".a" extension stripped
└── Headers
    ├── MyLibrary.h <- An umbrella header that eventually includes ClassA.h and ClassB.h
    ├── ClassA.h
    └── ClassB.h
```
In any case it seems more convenient to use this convention rather than inventing a home made package.json configuration.

So packed frameworks will be usable in nativescript.

**Comment by jasssonpet** [comment]
Moved to: https://github.com/NativeScript/nativescript-cli/pull/828

**Comment by linzhiqi** [comment]
@PanayotCankov 
Hi,

I created a framework following the structure you mentioned:
>MyLibrary.framework
├── MyLibrary <- libMyLibrary.a with the "lib" prefix and ".a" extension stripped
└── Headers
    ├── MyLibrary.h <- An umbrella header that eventually includes ClassA.h and ClassB.h
    ├── ClassA.h
    └── ClassB.h

But when I was trying to add it by tns library add ios <the path of the framework>, I got this error:
`The bundle at <the path of the framework> does not contain an Info.pllist file.`

Could you help me with this? I am trying to use WeChat's ios sdk in NS, however the sdk only provides the header files and the static library file(.a file).

**Comment by jasssonpet** [comment]
Hello, @linzhiqi,

A correct plugin structure for your case would be:
```
.
├── package.json
└── platforms
    └── ios
        ├── include
        │   └── wechat
        │       ├── WXApi.h
        │       └── WXApiObject.h
        └── wechat.a
```

And in packages.json:
```json
{
  "name" : "nativescript-wechat-sdk",
  "version": "0.0.1",
  "nativescript": {
    "platforms": {
      "ios": "1.4.1"
    }
  }
}
```

I'm using the WeChat SDK (which includes the arm64 architecture) provided [here](http://stackoverflow.com/a/24879548/477981).

**Comment by linzhiqi** [comment]
Thank you @jasssonpet ! It works for my experiment project. I will try the WeChat library you mentioned.

**Comment by priyangamani** [comment]
**i'm trying to add a nativescript plugin.It got a error like this...**

Intellects-MBP:HelloWorld macadmin$ tns plugin add ../nativescript-payment
(node:11797) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm ERR! addLocal Could not install /Users/macadmin/nativescript-payment
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "../nativescript-payment" "--save"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path /Users/macadmin/nativescript-payment
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/macadmin/nativescript-payment'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/macadmin/nativescript-payment'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/macadmin/HelloWorld/npm-debug.log
Command npm failed with exit code 254
# plugin add
