### ISSUE TITLE
NSTimer.alloc() crashes

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#152]
It appears the NSTimer was designed to be used as:
```Objective-C
[[NSTimer alloc] initWithFireDate:interval:target:selector:userInfo:repeats:]
```
And Apple cut some corners there. The init method is unusable in NativeScript. It also is unusable in Objective-C if alloc-ed and assigned to an ivar and init-ed later.

**Comment by jasssonpet** [comment]
Is this the same case as `UIFontDescriptor`?

**Comment by fealebenpae** [comment]
@jasssonpet It appears so. The placeholder returned by `alloc` in both cases does not like when `retain` or`release` are sent to it. Using JavaScript `new` on these classes also exhibits the same problem, but https://github.com/NativeScript/ios-runtime/pull/151 fixes that.

**Comment by jasssonpet** [comment]
Fixed in https://github.com/NativeScript/ios-runtime/issues/214
