### ISSUE TITLE
Interop Marshalling Bug?

### ISSUE THREAD

**Issue by Nathanaela** [NativeScript/ios-runtime#158]
I've recently been working on converting my Android SQLite wrapper onto the IOS side.  And I ran into a Marshalling issue that I'm not sure how to fix as it seems to be a bug in the IOS runtime.  The Repo is https://github.com/Nathanaela/nativescript-sqlite

The issue is https://github.com/Nathanaela/nativescript-sqlite/blob/master/sqlite.ios.js#L478
The prototype for this function is: **const unsigned char* *sqlite3_column_text(sqlite3_stmt*, int iCol);**
The ios-runtime apparently marshall's this into a Interop.Reference() type.    In this case the **ref.value** ends up being only the First Character (and in numeric form so "A" = 65) of the result string rather than the full string.   I can't seem to figure a way to get the full string back.   

Test Code, you just need to run "database_code();" :

```javascript
var sqlite = require('./node_modules/nativescript-sqlite/sqlite');

var database_code = function() {
    var dbp = new sqlite("test.db", function(err, ndb) {
        if (err) {
            console.error("Sqlite returned error", err);
        }
        console.log("Callback db is good");
    });

    dbp.then(function(db) {
        console.log("Then called with db", typeof db, sqlite.isSqlite(db) ? "Yes" : "No");
        db.execSQL("create table if not exists test (id integer, data text)");
        db.execSQL("insert into test (id, data) values (?,?)", [1, "blah"]);
        db.execSQL("insert into test (id, data) values (?,?)", [2, "cing"]);
        db.all("select * from test where data=?", "cing", function(err, data) {
            if (err) console.log("Error", err);
            for (var i = 0; i < data.length; i++) {
                console.log("Get Data", data[i]);
            }

            db.close();
        });

    }, function(err) {
        console.error("Promise failed", err);
    });
};
```

**Comment by jasssonpet** [comment]
Hi, you can see how to convert a `char*` or `interop.Reference` to a string in the [examples](http://docs.nativescript.org/runtimes/ios/types/C-Pointers#examples).

**Comment by NathanaelA** [comment]
Awesome and THANKS! -- That is EXACTLY what I needed to know.   I hope you had that Gist already made; because you didn't have to do all that work to answer my question.   Just your line **NSString.stringWithUTF8String(statement)** is what I needed.     My sqlite wrapper works perfectly except for retrieving the text column. 

   We might need to clean up the docs a little -- even with the information you provided I still don't really see where I would make that conclusion from the docs -- or that we can even do that to a Interop.Reference to a C Pointer..

**Comment by jacargentina** [comment]
@jasssonpet I've looked on this and the gist also, but had no luck with my code to get the error message from **sqlite3_errmsg**

The code is:

```javascript
...
var res = sqlite3_bind_text( ... );
// above gives an error, so try to show the error complete message
if (res)
{
  var errMsg = sqlite3_errmsg(db_instance);
  var message = NSString.stringWithUTF8String(errMsg.value);
  console.log('SQLITE.Binding Error', res, message);
}

```

Any advice?

**Comment by jacargentina** [comment]
Sorry've found it: the call should be:

````javascript
  var message = NSString.stringWithUTF8String(errMsg);
````

Cheers!
