### ISSUE TITLE
ios-metadata-generator is not public?

### ISSUE THREAD

**Issue by caiguo37** [NativeScript/ios-runtime#16]
Submodule path 'src/jsc': checked out '9cd6d7947270a7059c8f766ebea15d20543e4e2e'
Cloning into 'src/metadata-generator'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:NativeScript/ios-metadata-generator.git' into submodule path 'src/metadata-generator' failed

**Comment by PanayotCankov** [comment]
We are rewriting it in C++ as we want to lower its runtime dependencies and have focused on performance. We will open it shortly so you can build it, but I would suggest to wait for the mid-April version if you have contribution in mind.

**Comment by PanayotCankov** [comment]
The C# version of the repo with dependency on mono is now public.
