### ISSUE TITLE
Drop the static NativeScript lib

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#162]
Apple devices upgrade to latest iOS versions quite fast. At some point when we can drop support for iOS7 we should delete the static libraries with the NativeScript framework for iOS and use the dynamic NativeScript.framework.

**Comment by fealebenpae** [comment]
iOS 8 has a 86% installed base as of [August 17, 2015](https://developer.apple.com/support/app-store/). With the imminent iOS 9 release we can afford to drop iOS 7 support in the beginning of 2016, IMO.

**Comment by ligaz** [comment]
I just checked the AppBuilder Companion app stats and it looks like about 5% of the user base is using iOS 7. Will have data for the {N} companion app in the following weeks.

I guess we should be more open if we decide to drop support for iOS 7, even we might want to run a survey of some kind. Also it will be good to know what is the "cost" of supporting it in the runtime and CLI.

**Comment by PanayotCankov** [comment]
The code branching (read cost) for iOS7 and iOS8+ is **B** **I** **G**.

**Comment by fealebenpae** [comment]
At the runtime level we don't do anything specific to support a certain iOS version. We could go back all the way to iOS 5 if we wanted to. The only 7-vs-8 difference right now is that we build the runtime both as a static library and as a dynamic framework, but that is a mild annoyance at most. It wouldn't be an undue burden on the runtime to keep supporting iOS 7.

**Comment by PanayotCankov** [comment]
It does require extra efforts to support both a static and dynamic framework. [It involves extra care for things like this](https://github.com/NativeScript/ios-runtime/pull/275#issuecomment-133426124). It adds extra builds, extra binaries in the tns-ios package. If you opt in for dynamic frameworks to reduce the app size when used with extensions, you will have to support an update path, along with documentation for the developers when to upgrade to dynamic frameworks. You will have to explain pros and cons for each of the two types. It will also involve some QA time for extra testing.

If iOS7 is not a must, it would be easier to deliver just the dynamic framework.

**Comment by fealebenpae** [comment]
None of our downstream supported scenarios include extensions right now, so if you think building both the static library and dynamic framework is such a hassle why not simply drop the dynamic framework from the package?

**Comment by PanayotCankov** [comment]
Please do not do anything right now.
We currently have clients that are like:
```
 - Hi, what iOS version will you target?
 - Hi, we belive that 8 would be fine...
```
So I kind of support your statement from 5 days ago.

**Comment by fealebenpae** [comment]
I'm not about to do anything. I simply explained, and let me reiterate, that the "maintenance cost" of supporting older iOS versions at the runtime level is negligible. With this in mind, the runtime simply doesn't care whether it has to retain iOS 7 compatibility for the foreseeable future or not - it's not like there are large swaths of code or exotic dependencies that we need for the sole purpose of iOS 7 support.

IMO, the real and immediate benefit of dropping iOS 7 support would be felt in the cross-platform modules, what with the varying UIKit behavior across even minor iOS versions and the mass conversion of Objective-C methods to properties that happened in iOS 8 which is an API-breaking change in NativeScript and thus needs branches to support all API iterations. For this reason alone I think that the sooner NativeScript can drop iOS 7, the better. But from the runtime's point of view? It can keep on supporting iOS 7 indefinitely, frameworks and all.

**Comment by PanayotCankov** [comment]
Are we there yet? We are moving to iOS8+ support so do can we keep just the framework and iOS8 project template now?

**Comment by ivanbuhov** [comment]
@PanayotCankov we are almost there: https://github.com/NativeScript/ios-runtime/pull/548.

**Comment by ivanbuhov** [comment]
Since NativeScript 2.1.0 we no longer include the static library in the runtime package: https://github.com/NativeScript/ios-runtime/pull/587, https://github.com/NativeScript/ios-runtime/pull/588.
