### ISSUE TITLE
Typescript declarations for ReferenceType, FunctionReferenceType and BlockType.

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#168]
We have these three types `ReferenceType`, `FunctionReferenceType` and `BlockType` which are rarely used. (And may also be subject to change.) If they will be promoted and officially used we should add them in the interop.d.ts.

**Comment by jasssonpet** [comment]
Moved to https://github.com/NativeScript/ios-runtime/issues/282
