### ISSUE TITLE
iOS 9 Support: Use a single metadata file

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/ios-runtime#179]
Research if there could be a way to ship only one metadata file for the right architecture.

**Comment by PanayotCankov** [comment]
As suggested by @fealebenpae we can include the JavaScript files in the executable upon build. The app thinning will strip the fat binaries to a single slice on the AppStore when the app is distributed to the client devices. This will leave a single copy of the metadata in the actual download from the AppStore.

**Comment by ivanbuhov** [comment]
Fixed https://github.com/NativeScript/ios-runtime/commit/1f9e76eac62e6f2a4cc21fcca6c1a9162aa40432
