### ISSUE TITLE
iOS 9 Support: Generics in TypeScript definitions

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#181]
Since Objective-C has now generics support, we can check if it would be suitable to introduce the type parameters in the TypeScript declarations. We should also check if the type information suffers type erasure at runtime (similar to Java) and if the typed collections are guarded in some way.

**Comment by fealebenpae** [comment]
The problem with this is that variance rules, the `__kindof` attribute and generic constraints cannot be expressed in TypeScript. Thus translating Objective-C's lightweight generics to TypeScript will be limited to a large degree.

This is also blocked until a stable version of Clang that includes the `ObjCTypeParamDecl` API is released.

**Comment by fealebenpae** [comment]
Implemented in #341
