### ISSUE TITLE
Transform (NSError **) parameters to JavaScript error throw

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/ios-runtime#186]
Obj-C methods which return `BOOL` and have(`NSError **`/`CFErrorRef*`) as last parameter should be exposed as methods without the last parameter and have to throw JavaScript error on failure (the same convention is used in Swift 2).

PRs:
* https://github.com/NativeScript/ios-runtime/pull/208
* https://github.com/NativeScript/ios-metadata-generator/pull/8
* https://github.com/NativeScript/ios-metadata-generator/pull/9
* https://github.com/NativeScript/ios-runtime-docs/pull/33
* https://github.com/NativeScript/NativeScript/pull/404

Subtasks:
* [x] Research Swift 2 projection
* [x] Discuss possible NativeScript projections
* [x] Implement calling of such methods
* [x] Implement overriding of such methods
* [x] Implement exposing of such methods
* [x] Implement swizzling of such methods
* ~~Implement constructor calls of such initializers~~
* [x] Update TypeScript definitions
* [x] Write tests for all cases
* [x] Update documentation
* [x] Make PR in modules to use the new features

**Comment by jasssonpet** [comment]
In case of collisions:

```objective-c
@interface MyInterface : NSObject
+ (BOOL)myMethod:(int)x;
+ (BOOL)myMethod:(int)x error:(NSError**)outError;
@end
```

Swift prefers the first method, but the second one is still callable with it's full name. What should we do in JavaScript if such an issue occurs?

**Comment by jasssonpet** [comment]
We have agreed that the following will be supported:

```javascript
MyInterface.myMethod(2); // Calls myMethod:
MyInterface.myMethodError(2); // Calls myMethod:error: and implicitly checks for error - throws JS error
MyInterface.myMethodError(2, errorRef); // Calls myMethod:error: works like now
```

**Comment by fealebenpae** [comment]
> has more than one parameters

Having a single parameter of type `NSError**` should also be a supported scenario.

**Comment by jasssonpet** [comment]
@fealebenpae what is the best way to handle such APIs:

```objective-c
- (NSURLSessionDataTask *)dataTaskWithRequest:(NSURLRequest *)request
                            completionHandler:(void (^)(NSData *data,
                                                        NSURLResponse *response,
                                                        NSError *error))completionHandler;
```

Is there anything we can do here to throw JS errors?

**Comment by fealebenpae** [comment]
I think those are fine as they are. Besides, this pattern already has a counterpart in JavaScript.

**Comment by jasssonpet** [comment]
@fealebenpae Should we marshall the result of `MethodCallback` if a JS error is thrown?

**Comment by fealebenpae** [comment]
There shouldn't be a return value in this case. You can test this yourself, but I believe the result of `JSC::call` when there is an exception, is the exception itself or `undefined`.

**Comment by jasssonpet** [comment]
I'll make it to marshall `undefined` as the return value.

**Comment by jasssonpet** [comment]
It turns out that Objective-C initializers could take `NSError **` parameters. We should reconsider our logic for choosing the right initializer.

**Comment by fealebenpae** [comment]
@jasssonpet: I think the current overloading mechanism when `new`-ing Objective-C classes in JavaScript is brittle enough and this change might turn out to be too complex for it. Until we either retire it, or replace it with something better, we should steer clear of any extra features in that particular area.

**Comment by PanayotCankov** [comment]
@fealebenpae I would agree with that. The "new" is pesky at times and may be subject to change. We recommend `.alloc().init()`. With that I think this issue is close to completion?

**Comment by jasssonpet** [comment]
I'll update the modules PR.
