### ISSUE TITLE
User-defined launch images in project template

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/ios-runtime#188]
The user should be able to set a custom launch image in their NativeScript application.

**Comment by fealebenpae** [comment]
We've decided that the way to implement this is to teach the CLI to respect asset catalogs (as described in https://github.com/NativeScript/nativescript-cli/issues/683) found in `App_Resources/iOS` and insert them in the project when preparing it for build. Asset catalogs can then be used to describe app icons and launch images.
