### ISSUE TITLE
Remove the pre-packaged metadata

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#19]
Once we have the metadata-generator's performance improved enough to run before build, we should drop the metadata from the npm package and run the tool before build. This should help us keep up with new iOS versions and native libraries.

**Comment by ivanbuhov** [comment]
The metadata generator is rewritten in C++ and is merged to MetadataMerger tool (there is no more MetadataMerger tool, there is only MetadataGenerator tool). The new MetadataGenerator tool is part of our npm package. There is no more merge step. The tool gets headers as input and produces binary metadata (there is no intermediate yaml files any more). We don't distribute any metadata in our npm package. The metadata generation process takes place entirely on the client machine. It is integrated as build step in the project template, so there is no need to run it manually. Actually, there should be no case in which metadata generation must be run manually. The build step script collects all the needed information for metadata generation (path to the sdk folder, architectures, header include paths, framework include paths etc.) from Xcode proeject environment variables and pass it to metadata generator. The output of the metadata generator is single binary file for each architecture the app is builded for (architectures are retrived from Xcode environment variables). These files are copied in the app bundle and are used at runtime from the NativeScript iOS Runtime.
