### ISSUE TITLE
Backward compatible @nativescript scope modules

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#194]
To support the backward compatibility after ["Publish NativeScript JavaScript modules as npm packages"](https://github.com/NativeScript/NativeScript/issues/317#issuecomment-111679932), we will need to alter the logic in the _require_ to look in the `@nativescript` scope as a last resort. So that a `require("geolocation")` could continue to work along with `require("@nativescript/geolocation")`.

**Comment by jasssonpet** [comment]
Moved to: https://github.com/NativeScript/ios-runtime/issues/118
