### ISSUE TITLE
Unique all instances of Metadata::TypeEncodingsList in metadata

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/ios-runtime#216]
If all signature objects in metadata are uniqued we could decrease many calculations which happen per method call (offsets calculation of arguments, construction of `ffi_cif`s etc). Instead of per method call they will happen per method signature.

**Comment by fealebenpae** [comment]
This can greatly simplify the way the runtime deals with type information from the API metadata. For example, it can help compact all the type caches in our `TypeFactory`. Alright, let's do it.

**Comment by tdermendjiev** [comment]
As unifying ffi signatures in metadata-generator would lead to insufficient ffi metadata in ios-runtime only ffi_cif caching in FFICall initialization is implemented: https://github.com/NativeScript/ios-runtime/pull/795
