### ISSUE TITLE
Remove tokens stripping in metadata generator by migrating to Clang 3.7

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/ios-runtime#227]
We generate metadata for iOS 9 by stripping all Objective-C syntax from the header files which are not supported by Clang 3.6 (generics, `__kindof`, nullability modifiers). The stripping happens on the fly. It's a temporary(and ugly) solution. Clang 3.7 (it will be released at the end of August) is expected to support all these new Objective-C features and we have to migrate our metadata generator to use the new version of Clang. This will require some changes in our metadata generator. We will have to retrieve the generic information from the new APIs instead of stripping it on tokens level.
Although Clang 3.7 is not already released we can try to build it from its repo (where the needed changes are already merged) and spike (or fully implement) our metadata generator changes.

* [x] Try building Clang from latest source code (with homebrew)
* [x] Replace tokens stripping from metadata generator with the help of new APIs in Clang.
* [x] Migrate to Clang 3.7 when released officially.

**Comment by ivanbuhov** [comment]
To build and configure the metadata generator to use the latest LLVM from the repo:
1. Run `brew update`
2. Run `brew install llvm --with-clang --with-rtti --HEAD`. This will install the latest LLVM in `/usr/local/Cellar/llvm/HEAD`.
3. Create symlink `/usr/local/bin/llvm-config` pointing to `/usr/local/Cellar/llvm/HEAD/bin/llvm-config`
4. Change `LLVM_CONFIG_EXE` Cmake option in metadata generator project from `/usr/local/bin/llvm-config-3.6` to `/usr/local/bin/llvm-config`

**Comment by ivanbuhov** [comment]
I mananaged to generate valid metadata with the latest Clang (all tests pass). However, there are some issues to be fixed. The newest Clang is better in recognising toll-free bridged types, but for some of them we can't find the bridged type.

**Comment by fealebenpae** [comment]
LLVM 3.7 was supposed to be out on August 21, but as of August 25 they are [still at rc3](http://lists.llvm.org/pipermail/llvm-dev/2015-August/089600.html). Unfortunately we won't be able to ship the newest Clang with the 1.3 release.

**Comment by ivanbuhov** [comment]
Resolved: https://github.com/NativeScript/ios-runtime/pull/332
