### ISSUE TITLE
Crash in TNSRuntime dealloc

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/ios-runtime#229]
Happens in iOS 8 and iOS 9 simulators:

`EXC_BAD_ACCESS`: https://github.com/NativeScript/ios-runtime/blob/afcd175dc22ce6024af8cd45970c5df31c3ae4e9/src/NativeScript/TNSRuntime.mm#L137

**Comment by fealebenpae** [comment]
Technically, this is the `TNSRuntime` dealloc :Д
