### ISSUE TITLE
Expose a conversion between ArrayBuffers and NSData

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#231]
In some scenarios where Objective-C APIs are used to implement JavaScript specs we have provide utilities to easily, with low performance overhead and low memory footprint:

 1. Create ArrayBuffers from NSData
 2. Create NSData from ArrayBuffers

Currently our marshaling supports the second scenario, when ArrayBuffer object is passed as argument somewhere NSData is expected it gets wrapped by the marshaling service. We should check if this is sufficient.

**Comment by NathanaelA** [comment]
Do you actually have code that does the conversion between nsdata to ArrayBuffer?   I'm actually running into this where I'm getting a nsdata object and can't do anything with it.  If you point me to where you are creating the arraybuffer i might be able to reuse that code to get the data into js in a usable form.

**Comment by fealebenpae** [comment]
You can check my pull request https://github.com/NativeScript/ios-runtime/pull/235

**Comment by fealebenpae** [comment]
Implemented in #235.
