### ISSUE TITLE
Unable to generate metadata for header 

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/ios-runtime#241]
The following `module.modulemap` file sets `Additional.h` header as its umbrella header. In `Additional.h` we have `#include "ifaddrs.h"` directive. 

```
module Additional {
  umbrella header "Additional.h"
  export *
  module * { export * }
}
```
As a result metadata is generated for all declarations in `Additional.h` but not for `ifaddrs.h`. We have to check if the issue is in our metadata generator or maybe in Clang (and whether in Clang 3.7 the bug is fixed).

**Comment by ivanbuhov** [comment]
It turns out that Clang processes the header in question and all declarations in it, but Clang can't find the module (actually the submodule) which these declarations belong to. [Here](https://github.com/NativeScript/ios-metadata-generator/blob/master/src/Meta/IdentifierFactory.cpp#L71) the returned module is `null`. If we include the header in the module map explicitly the top level module (in this case `Additional`) is recognised as the owner of the declarations.
```
module Additional {
  umbrella header "Additional.h"
  header "path/to/sdk/usr/include/ifaddrs.h"
  export *
  module * { export * }
}
```
I will check if this is fixed with the latest version of Clang (built from the repo).

**Comment by ivanbuhov** [comment]
This is not a bug in metadata generator or clang, it is desired behavior, so I think the issue can be closed. ping @fealebenpae

**Comment by fealebenpae** [comment]
This makes sense. I think listing the system header implicitly in the modulemap is a good enough way to do it.

**Comment by ivanbuhov** [comment]
P.S. You can also set the system header to be an umbrella header as long as you don't have another umbrella header as part of your module.
