### ISSUE TITLE
Merge metadata file in the app's exutable file

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/ios-runtime#243]
Merge metadata file in the app's executable file. Because of [App Thinning](https://developer.apple.com/library/prerelease/ios/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html), only one slice of the binary will be installed on the phone, so unnecesery metadata will be strpipped as part of unnecessary slice. This is will reduce the NativeScript app size.

**Comment by jasssonpet** [comment]
Is this the same as https://github.com/NativeScript/ios-runtime/issues/179 ?

**Comment by ivanbuhov** [comment]
Yes, I thougth there is no issue for this. I will remove it.

**Comment by ivanbuhov** [comment]
Unfortunately, there is no way to completely delete an issue in github :). I will remove all labels and close it.
