### ISSUE TITLE
Location issue with iOS

### ISSUE THREAD

**Issue by edimoldovan** [NativeScript/ios-runtime#26]
Hi everyone,

I am using a beta Yosemite, 10.3.3. and am trying to implement a simple location retrieve and I am getting this error when running the app in the emulator. The code is this:
```
if (LocationManager.isEnabled()) {
	locationManager.startLocationMonitoring(function (location) {
		mainViewModel.set("latitude", location.latitude);
		mainViewModel.set("longitude", location.longitude);
	}, function (error) {
		console.log('Location error received: ' + error);
	});
}
```
`ERROR: org.nativescript.mobile is depending on legacy on-demand authorization, which is not supported for new apps`

The other thing I tried is a simple latest location retreival:
```
location.getLocation({ maximumAge: 30000, timeout: 30 }).then(function (location) {
	console.log('Location received: ' + location);
}, function (error) {
	console.log('Location error received: ' + error);
});
```
Is there a way to make location work? I assume I should also request permission, but I don’t know how to do that.

Thanks,
Eduárd

**Comment by jasssonpet** [comment]
Hello, can you move your issue to: https://github.com/NativeScript/cross-platform-modules
