### ISSUE TITLE
Possible memory leaks when using the iOS API native-style?

### ISSUE THREAD

**Issue by moll** [NativeScript/ios-runtime#260]
Hey,

I forwent using NativeScript's UI wrappers and just wrote a basic R&D demo using a Storyboard and the iOS API. It's pretty much the same what you get from Xcode's "New Project -> Page View Application", but in JavaScript. Uses delegates, data sources, protocols and a static UITableView inside the pages. The usuals.

Now, swiping between pages increases the used memory from an initial 12.9MB by a fairly constant ~400kB. Small valleys do occur on the Memory Report page in Xcode, but overall it climbs. Up to 65MB right now. The same bare logic and storyboard implemented in Swift hovers around 4MB and stays there, no matter how many swipes I do.

**What I'm wondering, are there some known memory leaks when going all-iOS with NativeScript?** Perhaps assigning delegates to views or controllers instantiated from the storyboard? I'm up for debugging this, but some pointers on how to start tackling it welcome. I'm not too home in Instruments.app or Xcode.

Thanks!

**Comment by TheBrousse** [comment]
Can you push the code somewhere so everyone is on the same foothold?

**Comment by moll** [comment]
I'll try to. And also simplify the test case further. Do you know off the top of your head how to force GC or go about debugging? Would help pinpoint the earliest call that leaks. Thanks!

**Comment by fealebenpae** [comment]
You can trigger a memory warning in your app - either by using Hardware > Simulate Memory Warning menu options in the iOS Simulator or by manually posting a `UIApplicationDidReceiveMemoryWarningNotification` on the default `NSNotificationCenter`.

There are no known memory leaks right now. The behavior you describe can be a bug and I'll welcome a test case that can reproduce it so we can fix it.

A little background: a JavaScript application will never have the same memory footprint and behavior as its Swift or Objective-C equivalent. The main difference is that JavaScript relies on garbage collection, whereas Swift and Objective-C have Automatic Reference Counting. While the garbage collector can be a good thing in that it frees you from thinking about ownership and retain cycles, unlike ARC it doesn't get rid of objects in memory as soon as possible. The GC tries to run more seldom so as to conserve the battery, and it doesn't really know the cost of the native objects it manages so it can't really see the jump in memory. This means that, depending on the app, the memory can build up until the app receives a low memory warning and triggers a full garbage collection. In this sense, it's not that JavaScript apps behave wrongly as much as they behave differently to Swift or Objective-C apps when it comes to memory.

**Comment by moll** [comment]
Thanks for the thorough response. Oh, I agree. I didn't expect it to run at the rate of reference counting, merely to drop back to a few dozen megs at some point. I'll try to put together a simpler file and storyboard to test it out. Unfortunately, right now it seems that after swiping a little, a Simulated Memory Warning throws a `EXC_BAD_ACCESS` around `___ZN12NativeScriptL22attachDerivedMachineryEPNS_12GlobalObjectEP10objc_classN3JSC7JSValueE_block_invoke20`. I'm not running debug builds of NativeScript, so it's all assembly at the exception point. ^_^

PS. Wouldn't too lax of a GC cause other running apps to be evicted from the memory, thereby causing more work when switching back to them and draining more battery overall than a bit more aggressive GC?

**Comment by fealebenpae** [comment]
You are right, potentially a lazy garbage collector can pile up memory, leading the system to suspending other apps. I'm not aware of the "right" way to handle this, however. So far we rely on the default behavior Apple has in JavaScriptCore on mobile. Really, the only missing piece is reporting the cost of an Objective-C object to the garbage collector so it can have a more complete picture of RAM usage, but there isn't a "right" way to do that either.

You can tweak the GC behavior of your app with several environment variables that JavaScriptCore respects. This isn't a documented feature of the NativeScript runtime, but if it proves useful we can expose the [Options API](https://github.com/NativeScript/webkit/blob/c385766edf9fdee3f01978fe67cd314a22e1b38e/Source/JavaScriptCore/runtime/Options.h) on `TNSRuntime`.

**Comment by moll** [comment]
Lo again,

So, let's get to the bottom of this. Please see https://github.com/moll/nativescript-disco for the first order of business, the crash on Simulate Memory Warning. I did my best to make it as simple as possible to build and reproduce. Are you seeing this too? Is the API use code sensible? Thanks!

**Comment by fealebenpae** [comment]
Well, it appears you've drawn the short straw on this one - there is indeed a bug which I've fixed in #262.

Otherwise, we have the same kind of application internally - storyboard included. You can find it [here](https://github.com/NativeScript/ios-runtime/tree/master/examples/Gameraww). Based on that, I think your app works pretty much like ours and while this isn't the target scenario of NativeScript what with cross-platformness and all, it should still work. I can prepare a build of the tns-ios package for you with the fix so you can test it out on your app and see how the memory warnings behave.

**Comment by moll** [comment]
Super! Can't wait to test the memory usage after GC.

Thanks for the build offer! I wouldn't be against if you cut those iOS releases from `master` more often in general and perhaps published them as NPM alphas/betas. Now would be a good time to start. :-)
Speaking of `master`, is the requirement of OS X v10.10 a hard dependency or can I build it with Xcode 6 on v10.9, too?  

Ironically, I find using native APIs from JavaScript precisely the sweet spot between rewriting business logic in Swift and abstracting too much and fighting with intermediate frameworks. So far I'm quite pleased with it, so thanks for your work! I think building an app for one platform's APIs first and then seeing which UI bits need abstracting or replacing for the other. Saves you from premature generalization. :)

**Comment by fealebenpae** [comment]
10.10 is a dependency of Xcode 6.3+, but AFAIK building with Xcode 6.2 on 10.9 might work. Depends on if JavaScriptCore can be build with Xcode 6.2, which I think it should, so I think you can try building on 10.9 and see how it goes.

[Here's](https://drive.google.com/file/d/0Bzw2K8LvCXN_bHpTZFgwWnRBbzA/view?usp=sharing) the build our CI made for the PR I linked. You need to extract it and pass the path to the `package` folder inside to the NativeScript CLI's `tns platform add ios` command with the `--frameworkPath` option.

**Comment by moll** [comment]
I'll check the build out. Thanks! Are those public somewhere by default too? Like for every commit on `master`.

**Comment by fealebenpae** [comment]
No, our CI is private right now, but it would help if they were public, yes.
