### ISSUE TITLE
console.dump()

### ISSUE THREAD

**Issue by jbristowe** [NativeScript/ios-runtime#261]
Currently, the console does not expose a dump() instance methods through the iOS runtime. This is non-optimal because it provides a useful mechanism for developers to discover the state of objects. Also, providing an implementation for console.dump() would provide better alignment with the implementation available on Android.

Request: Provide an implementation of console.dump() for the iOS runtime.

**Comment by fealebenpae** [comment]
The console that is part of NativeScript for iOS actually comes from the JavaScriptCore engine and as such we have little control over it. This means that adding new methods on the `console` object is not top among the list of things we can easily do without a non-insignificant maintenance cost involved. I think however that `console.dir` will do what you need. The complete API available on the JavaScriptCore console is listed in [the Apple docs](https://developer.apple.com/library/mac/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/Console/Console.html#//apple_ref/doc/uid/TP40007874-CH6-SW3).

**Comment by ligaz** [comment]
Can this be monkey-patched in the modules?

**Comment by jbristowe** [comment]
`console.dir()` does not generate the same output as `console.dump()`. Currently, it only appears to emit the type name.

**Comment by fealebenpae** [comment]
I would advise against modifying `console` in any way because of its relationship with the inspector.

@jbristowe: in the terminal `console.dir` is equivalent to `console.log`, but it should print the whole object in the inspector.

**Comment by jasssonpet** [comment]
Moved to https://github.com/NativeScript/NativeScript/issues/805
