### ISSUE TITLE
Unicode console logs in stderr

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/ios-runtime#28]
When using `console.log()` with non-ASCII characters the output in stderr is trash. (The output in the console client is fine though.) The reason for this seems to come from [`utf8ForRange`](https://github.com/WebKit/webkit/blob/90a597dee01955026e591bc77317e9227f960d0a/Source/WTF/wtf/text/StringImpl.cpp#L2192) which calls `convertLatin1ToUTF8`.

**Comment by KristinaKoeva** [comment]
Fixed with this one #340
