### ISSUE TITLE
ES6 modules support

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/ios-runtime#291]
Integrate the built in ES6 modules which comes with the newest JavaScriptCore.

**Comment by fealebenpae** [comment]
- [ ] Implement the hooks needed by JavaScriptCore to fetch and instantiate modules
- [ ] Implement a CommonJS compatibility layer on top
- [ ] Make Clang modules importable

**Comment by jasssonpet** [comment]
Implemented in https://github.com/NativeScript/ios-runtime/pull/468
