### ISSUE TITLE
Debug ios --debug-brk does not launch completely the application and does not stop at the initial breakpoint

### ISSUE THREAD

**Issue by vchimev** [NativeScript/ios-runtime#293]
`node_modules/.bin/tns debug ios --frameworkPath package --debug-brk --path TNS_App1` does not launch completely the application - it stops at the flash screen. Also the debugger does not stop at the initial breakpoint.

**Comment by fealebenpae** [comment]
We found out that this is due an unexpected `break` statement inserted in a critical section of the debugging code in the CLI while linting it.

**Comment by rclai** [comment]
I'm finding this to still happen. It sometimes stops at the initial breakpoint and sometimes it doesn't. Is anyone getting this?

**Comment by jasssonpet** [comment]
Is this on a device or simulator? Also can you try it on the just released 1.5 version of NativeScript.

**Comment by rclai** [comment]
This is on the device and I am using the new version.
