### ISSUE TITLE
Enable requiring of JSON files

### ISSUE THREAD

**Issue by atanasovg** [NativeScript/ios-runtime#294]
*Copied from nativescript/android-runtime#217*

Node has the feature to read and automatically parse JSON files through its require routine. This is a handy little feature that Node developers are used to, so we may consider implementing it.

See nativescript/android-runtime#215 for more information.

**Comment by jasssonpet** [comment]
Moving this to 1.5.1 since Android is implementing it: https://github.com/NativeScript/android-runtime/issues/217

**Comment by jasssonpet** [comment]
After a live discussion with @slavchev we decided that JSON objects should be cached.
