### ISSUE TITLE
Inspector web socket crashes when the message is big

### ISSUE THREAD

**Issue by KristinaKoeva** [NativeScript/ios-runtime#306]
We rely on the browser web socket to communicate with the inspector frontend and when the message that comes from the profiler is large enough, the browser web socket crashes. 
As a solution to this problem we should remove the web socket dependency and use the integrated inspector communication method - register a native object that would send/receive all messages that comes or goes to the device. 

The issue could be easily reproduced if you try to profile [sample-Tasks](https://github.com/NativeScript/sample-Tasks)

**Comment by fealebenpae** [comment]
Fixed in #317
