### ISSUE TITLE
Move runtime files in project template

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/ios-runtime#308]
When the CLI updates a project, the following items should be easily replaced, so moving them in an internal folder will make this easier.

* `metadataGenerator`
* `NativeScript`
* `NativeScript.framework`
* `TNSDebugging.h`

**Comment by jasssonpet** [comment]
@fealebenpae Should we also move `main.m` and `build.xcconfig`?

**Comment by fealebenpae** [comment]
Well, `build.xcconfig` is supposed to be user-editable, so perhaps it would be best to leave it where it is so it doesn't get updated by the CLI.

I'm torn about `main.m`, though. My gut feeling says we should leave it where it is, but I'm afraid there will  come a time when we have to update it if we change the way the runtime is initialized (like scheduling it on a runloop, for example). @Fatme, your thoughts?

**Comment by jasssonpet** [comment]
@fealebenpae What do you think if we move all NativeScript specific settings from the Xcode project to a separate nativescript-build.xcconfig?

For example:
* Link libraries (libNativeScript.a, libc++, libz, libicucore, MobileCoreServices)
* Other linker flags (-ObjC -sectcreate ...Metadata...)
* Header search paths (NativeScript/include)
* Library search paths (NativeScript/lib)

**Comment by fealebenpae** [comment]
Sounds awesome. Would `build.xcconfig` include this new file?

**Comment by jasssonpet** [comment]
We can also add three generic NativeScript build steps in the project template: `PRE_BUILD` `PRE_LINK` `POST_BUILD` to future proof any changes. We can also make the scripts language agnostic, by removing the `bash nativescript-pre-build.sh` and change it to `./nativescript-pre-build` for example.

**Comment by fealebenpae** [comment]
+ aleph-one

**Comment by jasssonpet** [comment]
There are some conflicts with our CocoaPods integration, that I'm currently looking at.

**Comment by jasssonpet** [comment]
https://github.com/CocoaPods/CocoaPods/issues/1761#issuecomment-32890062
