### ISSUE TITLE
Debugger does not stop at some breakpoints when --start option is in use on iOS7

### ISSUE THREAD

**Issue by vchimev** [NativeScript/ios-runtime#315]
Tested on iPad iOS7, not reproducible on iOS8 device.

Scenario - I use Cuteness app for testing purposes.
I execute `tns debug ios` which launches the debugger with the default *--debug-brk* option. Than I put two breakpoints in main-page.js file:
- 1st breakpoint at pageLoaded() function,
- 2nd breakpoint at listViewItemTap() function.

To verify that the debugger hits the breakpoints I tap on any item in the list (2nd breakpoint) and navigate back (1nd breakpoint) - it works as expected.

The issue is when I execute `tns debug ios --start` in order to attach to the running application. When open an item and go back the debugger stops at the 1st breakpoint, but it does not at the 2nd.

**Comment by fealebenpae** [comment]
Is this a 7.0 device, or 7.1?

**Comment by vchimev** [comment]
7.1

**Comment by speigg** [comment]
:+1:  same problem here

**Comment by KristinaKoeva** [comment]
Looks related to this one #521
