### ISSUE TITLE
Missing console.dump on ios...

### ISSUE THREAD

**Issue by enchev** [NativeScript/ios-runtime#326]
_From @NathanaelA on September 19, 2015 8:6_

I copied some code over from Android to ios; and found out the console.dump doesn't work.   Shouldn't we take the same dump routine that is available on the ios and patch the console prototype to use it?   

_Copied from original issue: NativeScript/NativeScript#778_

**Comment by jasssonpet** [comment]
`console.dump()` isn't implemented in any of the following popular APIs:

* [Node.js Console](https://nodejs.org/api/console.html)
* [Chrome Console](https://developer.chrome.com/devtools/docs/console-api)
* [Firefox Console](https://developer.mozilla.org/en-US/docs/Web/API/Console)
* [Safari Console](https://developer.apple.com/library/mac/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/Console/Console.html)
* [Opera Console](http://www.opera.com/dragonfly/documentation/console/)

IMO, if we want to support it on iOS, the same as we do on Android, we have to add the same [implementation from the modules](https://github.com/NativeScript/NativeScript/blob/v1.3.0/console/console.ts#L382-L384) in the runtime, which is a suboptimal and error-prone decision. I think, that the `dump` method (and any other custom one) should be added in the NativeScript modules to the existing console, provided by the runtime.

Also, related to: https://github.com/NativeScript/ios-runtime/issues/261

**Comment by enchev** [comment]
This issue was moved to NativeScript/NativeScript#805

**Comment by fealebenpae** [comment]
@jasssonpet we should use `console.dir()`, which is supported by the Inspector.

**Comment by jasssonpet** [comment]
@fealebenpae `console.dir()` is an excellent method, but as said in the previous discussion, it doesn't work without the inspector. Sometimes you just want to use the terminal, and something like `console.dump()` would be invaluable.

**Comment by fealebenpae** [comment]
@jasssonpet We can override the current `ConsoleClient` and implement `stdout` logging for `dir`, `table`, and some other methods.

**Comment by jasssonpet** [comment]
I totally agree with this if we can, and we can change `console.dir()` for Android too to be on par with iOS.

But I think, that it would still be useful to have something like `util.inspect()` for dumping to a file or `alert` call.
