### ISSUE TITLE
Launch screen does not work on iOS9.0

### ISSUE THREAD

**Issue by vchimev** [NativeScript/ios-runtime#330]
The launch screen does not show up before starting the application.

```
Error generating launch image for org.nativescript.testApp: Error Domain=UILaunchStoryboardErrorDomain Code=1 "No such interface found."
```

Output: https://gist.github.com/vchimev/02f7d19d905a9812b86d

**Comment by fealebenpae** [comment]
Could this be related to the LaunchScreen storyboard discussed in #281? Could you please try removing the LaunchScreen in `platforms/ios` and rebuilding?

**Comment by x4080** [comment]
Maybe its an xcode 7 issue since when i ran it on my real iphone 4s with ios 8.1 still have black screen, i will try your suggestion fealebenpae
