### ISSUE TITLE
Expose version number

### ISSUE THREAD

**Issue by e2l3n** [NativeScript/ios-runtime#333]
Having exposed the version number of the nativescript iOS runtime will provide better flexibility for the ION companion app.

**Comment by fealebenpae** [comment]
How would the companion app use the version number?

**Comment by galexandrov** [comment]
The version number will be used just for information purposes. The companion app needs to show the used ns-runtime version in settings.

**Comment by fealebenpae** [comment]
Wouldn't it be easier to just hardcode the version string in the package.json manifest of the tns-ios package the companion is built with in the companion's settings bundle?

**Comment by jasssonpet** [comment]
https://github.com/NativeScript/ios-runtime/issues/123
