### ISSUE TITLE
Promises seem slow to reject on iOS

### ISSUE THREAD

**Issue by maknz** [NativeScript/ios-runtime#346]
It seems that on iOS, promises take a while to reject for some reason. When comparing the time it takes for a `.catch` to get called after `reject()` is hit inside the promise, iOS can take a great deal of time for the `.catch()` callback to get run, whereas it's instantaneous on Android. I suspect this could be a problem with JavaScriptCore vs V8?

I have provided videos via our Slack with the {N} team (see @valentinstoychev), and can provide a project to reproduce on there if needed.

**Comment by fealebenpae** [comment]
Promise reactions on iOS run on the resolving thread's runloop, but prior to 1.4 they don't cause the runloop to be spun. What you're most probably seeing is that the promise reaction is queued but not executed until something causes the runloop to run, such as a touch input or a timer.

Starting with 1.4, promises will trigger the runloop if it's idle.

**Comment by maknz** [comment]
That does indeed sound consistent with the symptoms. The time it takes for the reject to execute is variable, can be *really* long, or short, or a bit longer, etc.

Excellent, we look forward to 1.4 :) thanks guys, we appreciate it!
