### ISSUE TITLE
Builds fail with XCode 7 on El Capitan

### ISSUE THREAD

**Issue by enchev** [NativeScript/ios-runtime#348]
_From @manijak on October 4, 2015 16:35_

Hi, Is there anything specific I need to do to get Nativescript to build my app on El Capitan with xcode 7?
https://groups.google.com/forum/#!topic/nativescript/6dvxXLF93QE

Running latest nightly from http://nativescript.rocks

_Copied from original issue: NativeScript/NativeScript#879_

**Comment by enchev** [comment]
_From @fealebenpae on October 4, 2015 20:0_

Hi @manijak,

The metadata generation process in the master branch of the iOS runtime was indeed broken for a time while we were [migrating to Clang 3.7](https://github.com/NativeScript/ios-runtime/pull/332) but it should be alright now. That is to say, I believe you must have gotten a bad build, instead of El Capitan breaking anything. Things in master do and will break, unfortunately.

It will help to confirm my assertion that El Capitan is not to blame if you could try to build an app with the official NativeScript release from npm on the same machine.

**Comment by manijak** [comment]
Ok so I tried first with a new master build (from 2015-10-05), and I got the same error. So I removed everything, and installed latest stable from npm 1.3.0. 

Now the build completes without errors, but the simulator does not load the app. The app is not deployed at all. 

Very weird that now I have to run ALL  commands with 'sudo' in front. Otherwise it fails. 

This is what I get after building via Sublime3:
(The last line regarding timeout is only when running with iOS 9 emulator)

```
Using  /Users/Nedim/Desktop/soccer-app/platforms/ios/build/emulator/soccerapp.app
Cleaning up before starting the iOS Simulator
Starting iOS Simulator
2015-10-06 12:38:23.958 node[7306:121998] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-8208/DVTFoundation/PlugInArchitecture/PlugInManager/DVTPlugInManager.m:257
Details:  Requested but did not find extension point with identifier Xcode.DVTFoundation.DevicePlatformMapping
Object:   <DVTPlugInManager: 0x1016115e0>
Method:   -extensionPointWithIdentifier:
Thread:   <NSThread: 0x10160c2e0>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
Session started with error  Error Domain=DTiPhoneSimulatorErrorDomain Code=2 "Timed out waiting for device to boot" UserInfo={NSLocalizedDescription=Timed out waiting for device to boot}
```

**Comment by fealebenpae** [comment]
I think this could be related to the NativeScript CLI's support of Xcode 7 on El Capitan. @teobugslayer, do you have an idea what could have gone wrong?

**Comment by Fatme** [comment]
It seems that this issue is related to https://github.com/NativeScript/nativescript-cli/issues/955. We're currently working on resolving the problem and will provide a fix in 1.4.1 release.

**Comment by manijak** [comment]
I wish I knew that before upgrading to El Capitan. Should have read the issues on cli... my bad.

Forgot to post this while I was testing.
Update: I removed the platform\ios again. Changed file-permissions to the package.json file (me as owner). Then re-added platform ios again without 'sudo' command. This time it worked. 

Ran both 'emulate' and 'run ios' to test. This time the app is deployed to emulator, but does not run, just goes back to homescreen with no errors. I get the following in the output window:
```
Session started without errors.
NativeScript loaded bundle file:///Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%208.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/UIKit.framework
NativeScript loaded bundle file:///Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%208.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework
NativeScript loaded bundle file:///Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%208.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreImage.framework
NativeScript loaded bundle file:///Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%208.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/QuartzCore.framework
NativeScript loaded bundle file:///Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%208.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/iAd.framework
NativeScript loaded bundle file:///Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%208.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/AVFoundation.framework
NativeScript loaded bundle file:///Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%208.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/MapKit.framework
NativeScript loaded bundle file:///Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%208.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/SceneKit.framework
NativeScript loaded bundle file:///Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%208.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/QuickLook.framework
NativeScript loaded bundle file:///Users/Nedim/Library/Developer/CoreSimulator/Devices/1D0BF9E1-6D1F-47CF-8525-C8F0D3B058CB/data/Containers/Bundle/Application/91E11A31-4494-4097-9AB5-16D2BAE9677A/soccerapp.app/Frameworks/TelerikUI.framework
NativeScript loaded bundle file:///Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%208.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreGraphics.framework
NativeScript loaded bundle file:///Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%208.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreText.framework
Session ended without errors.
[Finished in 26.2s]
```

I've read somewhere that nativescirpt is depentend on 'ios-sim-portable' module in order to deploy apps to the emulator? I've cheked my system and there is no such module installed, or is this embeded in the nativescript cli?

**Comment by manijak** [comment]
Update 2.  Ok I got it running :-)
I decided to open the .xcodeproj with Xcode and run the build there. To see if there are any errors that the terminal isn't showing. And yes there was. 

Right after the above mentioned 'Nativescript loaded bundle file:...' lines, there is this:
```
file:///app/tns_modules/ui/core/dependency-observable.js:302:89: JS ERROR Error: Invalid value E603396c for property backgroundColor
1   0x10d01366e NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0x10d5d36c9 ffi_closure_unix64_inner
3   0x10d5d64be ffi_closure_unix64
4   0x10e61c3ce -[UIViewController view]
5   0x10e537289 -[UIWindow addRootViewControllerViewIfPossible]
6   0x10e53764f -[UIWindow _setHidden:forced:]
7   0x10e543de1 -[UIWindow makeKeyAndVisible]
8   0x10d5d633c ffi_call_unix64
9   0x7fff52c1d8f0
```
Wrong color-value in a ListView on my main-page, missing a # in front. After fixing that, everything works. I can run builds via Sublime, sweet. 
The DVTAssertions - warning is still present but does not seem to affect the build.
