### ISSUE TITLE
Network agent for the Inspector

### ISSUE THREAD

**Issue by fealebenpae** [NativeScript/ios-runtime#354]
Add an implementation of the Network inspector domain that will instrument the `http` module.

**Comment by KristinaKoeva** [comment]
A spike is available here https://github.com/NativeScript/NativeScript/tree/KristinaKoeva/NetworkSpike so I am closing this one.
All network requests that are made with the http module are reported to the Network Agent. 
I was also able to show some other events in the Timelines tab like click event or a custom defined one. I would be happy to demonstrate it on our next master scrum :)
