### ISSUE TITLE
Update JavaScriptCore

### ISSUE THREAD

**Issue by fealebenpae** [NativeScript/ios-runtime#355]
Bump the WebKit submodule to a later, greater version. We need this for the ES6 modules and the Network agent.

**Comment by jasssonpet** [comment]
There is some incomplete progress here: https://github.com/NativeScript/ios-runtime/tree/webkit-update

**Comment by ivanbuhov** [comment]
Implemented https://github.com/NativeScript/ios-runtime/pull/362.
