### ISSUE TITLE
Add support for nightly builds using npm

### ISSUE THREAD

**Issue by hshristov** [NativeScript/ios-runtime#357]
We can upload nightly builds (untested) and mark them with @next.

**Comment by NathanaelA** [comment]
Btw, for anyone looking for compiled nightlies, http://nativescript.rocks already does nightlies of all the pieces.

**Comment by dtopuzov** [comment]
We already have official @next package.

**Comment by valentinstoychev** [comment]
For more information how to use it - http://docs.nativescript.org/releases/running-latest
