### ISSUE TITLE
Debugger - load the breakpoints from the previous session

### ISSUE THREAD

**Issue by vchimev** [NativeScript/ios-runtime#360]
It would be great to load the breakpoints from the previous debugging session.

**Comment by jasssonpet** [comment]
Should the breakpoints be sandboxed per application?

**Comment by jasssonpet** [comment]
@vchimev found out that this wasn't working in 1.5. The reason for this is that PR https://github.com/NativeScript/ios-runtime/pull/374 didn't update the NativeScript Inspector binary that is in our repo.

@NativeScript/nativescript-for-ios Maybe the time for https://github.com/NativeScript/ios-runtime/issues/368 has come.

**Comment by jasssonpet** [comment]
This should be fixed in the master branch.
