### ISSUE TITLE
Change enum syntax

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/ios-runtime#37]
In the current implementation enumerations are exposed as:
```javascript
var v1 = HMCharacteristicValueHeatingCooling.HMCharacteristicValueHeatingCoolingOff;
```

We should instead support both:

```javascript
var v2 = HMCharacteristicValueHeatingCooling.Off;
var v3 = HMCharacteristicValueHeatingCoolingOff;
```

This way the code isn't so verbose and looks closer both to C/Objective-C and JavaScript.

This is a breaking API change, so it should be done sooner.

**Comment by ivanbuhov** [comment]
Now all enum fields are exposed as three different ways. You can access an enum field:
1. through its full name (without prefixing with enum name).
2. through  its parent enum object, using field's full name. (deprecated, in feature this may be removed)
3. through  its parent enum object, using field's short name.
```javascript
var value1 = NSOrderedAscending; // value = -1
var value2 = NSComparisonResult.NSOrderedAscending; // value = -1 (deprecated, in feature this may be removed)
var value = NSComparisonResult.Ascending; // value = -1
```

**Comment by jasssonpet** [comment]
We should update the documentation also.

**Comment by ivanbuhov** [comment]
Documentation updated: https://github.com/NativeScript/ios-runtime-docs/commit/6ecc385842c707ef0d17f57a399750ea4bc419e8
