### ISSUE TITLE
NativeScript apps crash on iPhone 6s

### ISSUE THREAD

**Issue by maknz** [NativeScript/ios-runtime#371]
We've tested this with our own app, and with a brand new {N} application. The app will crash when you try and run it, with some random memory error:

<img width="746" alt="screen shot 2015-10-14 at 5 43 07 pm" src="https://cloud.githubusercontent.com/assets/992356/10475060/5f8edc9a-729b-11e5-8332-58995fe1fada.png">

It *does* work fine with an iPhone 6s simulator, but **not** on a real iPhone 6s device.

**Comment by fealebenpae** [comment]
Is there anything in the app's standard output?

**Comment by maknz** [comment]
Doesn't seem to be. It has the output that the app usually has, up until it stops and highlights that line.

**Comment by fealebenpae** [comment]
Alright, I'll try to reproduce it locally. I guess you're using CLI version 1.4.1, which is the latest on npm, the runtime should be 1.4.0, which is also the latest on npm, and Xcode 7.0.1, right? Are you running OS X Yosemite or El Capitan?

**Comment by maknz** [comment]
Yes - 1.4.1 (latest) CLI, Xcode 7.0.1 from Mac App Store, OS X Yosemite.

If it's helpful, this crash occurred in the 1.3.0 environment (CLI and runtimes). We were, however, using an updated version of the core modules (master at the time, which became 1.4.0) as there were bugfixes in there that we needed.

**Comment by fealebenpae** [comment]
Oh. Does the crash occur with the 1.3.0 modules and runtime? Also, can you give me the git commit SHA of the modules version you're using?

**Comment by maknz** [comment]
I haven't tried with the 1.3.0 modules (haven't currently got the project in front of me, sorry). When we were using the 1.3.0 CLI and runtimes, we were using, at the time the crash was present on the 6s, the modules at https://github.com/NativeScript/NativeScript/commits/a396fd397ef71984a145f4c96256f6accacd9f12.

**Comment by fealebenpae** [comment]
Unfortunately I don't have access to a 6s device yet, so I'm afraid I'll need to do some blind debugging.

I'm trying to determine whether I should look into the modules or the runtime for the reason behind the crash. To that end, I need to ask you to try to run a simple app sans modules on the phone: https://gist.github.com/fealebenpae/b48f18f2c40e0c1d3fd3.

**Comment by maknz** [comment]
Didn't work, unfortunately. I did `tns create iostest`, replaced the `app/app.js` file with the one in the Gist, `tns prepare ios`, opened the Xcode project and hit play:

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application windows are expected to have a root view controller at the end of application launch'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000106964f65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001063dedeb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000106964dca +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x000000010482bae2 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   UIKit                               0x0000000104bfd275 -[UIApplication _runWithMainScene:transitionContext:completion:] + 2875
	5   UIKit                               0x0000000104bf9ff0 -[UIApplication workspaceDidEndTransaction:] + 188
	6   FrontBoardServices                  0x0000000107cc07ac -[FBSSerialQueue _performNext] + 192
	7   FrontBoardServices                  0x0000000107cc0b1a -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	8   CoreFoundation                      0x00000001068910a1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	9   CoreFoundation                      0x0000000106886fcc __CFRunLoopDoSources0 + 556
	10  CoreFoundation                      0x0000000106886483 __CFRunLoopRun + 867
	11  CoreFoundation                      0x0000000106885e98 CFRunLoopRunSpecific + 488
	12  UIKit                               0x0000000104bf998d -[UIApplication _run] + 402
	13  UIKit                               0x0000000104bfe676 UIApplicationMain + 171
	14  iostest                             0x0000000103da504c ffi_call_unix64 + 76
	15  ???                                 0x000000010f3dc720 0x0 + 4550674208
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by maknz** [comment]
We don't have an iPhone 6s either, the crash was reported by one of our public testers. It won't be practical for us to have access to one to debug unfortunately.

**Comment by maknz** [comment]
This is working for us again as of 1.4.1 tns-ios.
