### ISSUE TITLE
Loading static frameworks as shared frameworks

### ISSUE THREAD

**Issue by maknz** [NativeScript/ios-runtime#373]
We're trying to use Raygun4iOS, which is a crash reporting library. I've tried specifying it in a plugin's Podfile, and just putting the framework into platforms/ios in the plugin. Regardless, when the app is starting, we are told that NativeScript could not load the framework -- as a log line when the app is starting and listing the frameworks it's loading. There's no other error detail though, so I don't know why this would be happening.

Instructions for setting up Raygun in a regular iOS application are here: https://raygun.io/docs/languages/ios.

**Comment by jasssonpet** [comment]
Hello @maknz,

It seems that the Raygun4iOS is distributed as a static framework, but we are trying to load it as a shared framework. This is a bug on our side.

If you ignore the erroneous console warning, the app should be able to use the APIs just fine.

Thank you for reporting this bug, we will be fixing it shortly.

**Comment by ligaz** [comment]
Hey @maknz,

I'm very interested why you have chosen Raygun for crash reporting. Have you tried or considered Telerik's own [Analytics solution](https://www.nativescript.org/blog/details/adding-analytics-to-your-nativescript-app) which apart from providing app insights has a crash reporting built into it as well?

**Comment by maknz** [comment]
I didn't actually know about it -- but we'd like to keep all our error reporting across the board (Ruby, iOS, Android) consolidated which is something Raygun provides. Of course it doesn't delve too much into analytics outside of error reporting, we haven't looked too far into that yet.

**Comment by fealebenpae** [comment]
We've determined that even though the runtime complains it can't find the Raygun4iOS.framework because it it static, classes in it should still be available in JavaScript through the fallback mechanism. You can disregard the error message unless Raygun APIs are not available in JavaScript.

However, it would be better to use either a Cocoa framework, or a Podfile that references the Raygun4iOS pod.

**Comment by maknz** [comment]
We are using the Podfile method currently. We're fine with ignoring the error, it does all work :)

**Comment by jasssonpet** [comment]
One thing we can do forn now is to report the error message only the first time we try to load the framework, not on each call to it. Also we can modify the message to suggest, that this is expected until we find a way to include in the metadata whether a framework is static or shared.

**Comment by jasssonpet** [comment]
This is also the case for the googleads-mobile-ios CocoaPod.
