### ISSUE TITLE
Ios black splash screen 

### ISSUE THREAD

**Issue by vchimev** [NativeScript/ios-runtime#378]
_From @x4080 on October 21, 2015 5:18_

Is this intended? How to display splash screen in ios? I thought that the files in app resources is for the icon and splash screen? 

Xcode 7, iPhone 4s ios 9 simulator 

Thanks 

_Copied from original issue: NativeScript/NativeScript#964_

**Comment by x4080** [comment]
So is it a bug ? :)

**Comment by fealebenpae** [comment]
I think this is related to #330. Please describe your issue there.
