### ISSUE TITLE
CocoaPods /platforms/ios/Podfile generation

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/ios-runtime#382]
This generated Podfile (tns command builds it) is built it can get lots of duplicates.   Each time you do something that internally does a **tns prepare ios** or if you manually do a **tns prepare ios** you will get a duplicate begin, pod and end lines into this file.   
Maybe this file should be truncated before adding them back.   As when I was fixing my pod file; I ended up getting several of the same pods in the file, but all with different :path variables which then caused it to choke...

**Comment by jasssonpet** [comment]
This issue was moved to NativeScript/nativescript-cli#1096
