### ISSUE TITLE
Warnings when targeting a lower version than iOS 9 since 1.4.1

### ISSUE THREAD

**Issue by maknz** [NativeScript/ios-runtime#389]
> ld: warning: object file (.../platforms/ios/internal/NativeScript/lib/libNativeScript.a(Allocator.o)) was built for newer iOS version (9.0) than being linked (8.0)

Seems to have started happening with 1.4.1.

**Comment by fealebenpae** [comment]
Hi @maknz,

The build of JavaScriptCore that we shipped with 1.4.1 doesn't correctly set its iOS deployment target version. This is a benign (if verbose) warning and we will fix it in a future release.
