### ISSUE TITLE
Weird stack trace in the console (as compared to the identical stack trace for Android)

### ISSUE THREAD

**Issue by ikoevska** [NativeScript/ios-runtime#392]
I am playing with unit testing in the {N} CLI and I have stumbled upon weird stack trace behavior for iOS.

Here is the iOS stack trace:

```
NativeScript / 8.1 (8.1; iPhone Simulator) A suite is just a function Check counter FAILED
	TypeError: undefined is not an object (evaluating 'mainViewModel.mainViewModel.HelloWorldModel.HelloWorldModel') in file:///app/tests/example.js (line 6)
	file:///app/tests/example.js:6:55
	attemptSync
	run
	execute
	queueRunnerFactory
	execute
	fn
	attemptAsync
	run
	execute
	queueRunnerFactory
	fn
	attemptAsync
	run
	execute
	queueRunnerFactory
	execute
	execute
	runTests@file:///app/tns_modules/nativescript-unit-test-runner/main-view-model.js:224:23
	file:///app/tns_modules/nativescript-unit-test-runner/main-view-model.js:192:101
	tick@file:///app/tns_modules/timer/timer.js:16:23
	UIApplicationMain@[native code]
	start@file:///app/tns_modules/application/application.js:191:26
	anonymous@file:///app/tns_modules/nativescript-unit-test-runner/app.js:4:18
	__executeModule
	__loadModule
```

And here is the identical stack trace for Android.
```
NativeScript / 21 (5.0; Google Nexus 9 - 5.0.0 - API 21 - 2048x1536) A suite is just a function Check counter FAILED
	TypeError: Cannot read property 'HelloWorldModel' of undefined
	    at Object.<anonymous> (/data/data/org.nativescript.jasmine/files/app/tests/example.js:14:55)
	    at attemptSync (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1789:24)
	    at QueueRunner.run (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1777:9)
	    at QueueRunner.execute (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1762:10)
	    at Spec.Env.queueRunnerFactory (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:627:35)
	    at Spec.execute (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:353:10)
	    at Object.fn (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:2360:37)
	    at attemptAsync (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1819:24)
	    at QueueRunner.run (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1774:9)
	    at eval (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1801:16)
```

Note how the iOS stack trace sequence corresponds to the Android stack trace sequience

iOS | Android
---|---
attemptSync | at attemptSync (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1789:24)
run | at QueueRunner.run (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1777:9)
execute | at QueueRunner.execute (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1762:10)
queueRunnerFactory | at Spec.Env.queueRunnerFactory (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:627:35)
execute | at Spec.execute (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:353:10)
fn | at Object.fn (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:2360:37)
attemptAsync | at attemptAsync (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1819:24)
run | at QueueRunner.run (eval at <anonymous> (/data/data/org.nativescript.jasmine/files/app/tns_modules/nativescript-unit-test-runner/main-view-model.js:211:21), <anonymous>:1774:9)

After the last run line from above, there's an additional sequence on iOS:
execute
queueRunnerFactory
fn
attemptAsync
run
execute
queueRunnerFactory
execute
execute

It seems that some information from the stack trace gets stripped on iOS.

**Comment by fealebenpae** [comment]
You mean the class names from the functions, as in `QueueRunner.run` vs. `run`?

**Comment by fealebenpae** [comment]
Oh, and addresses also.

**Comment by fealebenpae** [comment]
Well, stack traces are dependent on the JavaScript engine (JavaScriptCore or v8), so there isn't really much we can do to change or unify the behavior, save for using the same engine.

**Comment by fealebenpae** [comment]
I guess this could be fixed if the unit test runner doesn't [`eval`](https://github.com/NativeScript/nativescript-unit-test-runner/blob/d601dcef1879a77efd6410c3f439af1ac151c4f7/main-view-model.ts#L264) code. `eval` makes JavaScriptCore treat code as anonymous and it loses information about its location.

If you look into the Android stack trace, the location for each frame on the call stack is actually the location of the `eval` call, not the actual source code itself. It seems to me that even though the test runner prints more information on Android, the extra info is nonsensical and of little use.

**Comment by tailsu** [comment]
It makes more sense to filter the stack trace to keep only user code in both runtimes, but that's something that should be done in the test runner, not in the runtime.

**Comment by fealebenpae** [comment]
I think the problem here is using `eval`. The iOS runtime tests are jasmine-based, but each suite is a module that's `require`d, which presserves source location information in stack traces.

**Comment by fealebenpae** [comment]
@tailsu I've been thinking about providing a stack walker API, because right now we can only get the current call stack as a string in JavaScript. This could help with filtering non-user frames on the stack, at least on iOS. What do you think?

**Comment by tailsu** [comment]
I'm inclined to replace the eval's with require's and then filter the stack by file name. The test runner we use has built-in support for that.
