### ISSUE TITLE
UIEdgeInsetsMake missing from iOS typedef

### ISSUE THREAD

**Issue by enchev** [NativeScript/ios-runtime#405]
_From @rclai on November 13, 2015 14:28_

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIKitFunctionReference/#//apple_ref/c/func/UIEdgeInsetsMake

Was this intentionally left out because you can create one using a JS object literal?

_Copied from original issue: NativeScript/NativeScript#1098_

**Comment by jasssonpet** [comment]
Hello, @rclai,

The `UIEdgeInsetsMake` function is an inline function not available at runtime. You can learn more about limitations of C functions [in the docs](https://docs.nativescript.org/runtimes/ios/types/C-Functions.html#inline-functions-are-not-available).

**P.S.** `UIEdgeInsetsMake` is actually available in NativeScript for iOS but isn't declared in the TypeScript declarations: https://github.com/NativeScript/ios-runtime/issues/256.

**Comment by rclai** [comment]
Thanks.
