### ISSUE TITLE
File path format in require Error messages

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#407]
The require errors point absolute paths in Error messages generated by a failed `require`.

If the paths points to location inside the [applicationPath](https://github.com/NativeScript/ios-runtime/blob/master/build/project-template/internal/main.m#L18) it sound reasonable to cut the leading directories and print the original file and the computed paths in the error message like:

```
file:///app/tns_modules/ui/builder/component-builder.js
```

This will:
 - Make them easier to read
 - Display links in the WebInspector that open the source file when clicked
 - Be possible to generate the same error messages for iOS and Android
 - Be possible to assert in tests by error messages

**Comment by jasssonpet** [comment]
> Display links in the WebInspector that open the source file when clicked

It seems that the Web Inspector isn't available to navigate from paths in the error message of a thrown JavaScript error.

**Comment by PanayotCankov** [comment]
We have to double check this, since in works on my machine with paths to XMLs.
