### ISSUE TITLE
Implement the Metadata Generator in C++

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#42]
We want to lower the dependencies for the end devs, and increase the performance of the metadata generator, so we are rewriting the metadata generator in C++. It will link statically all dependencies. The result should be a self contained command line tool.

**Comment by ivanbuhov** [comment]
The metadata generator is rewritten in C++ and is merged to MetadataMerger tool. The metadata generation is no more two step process. The tool parses header files and produces binary metadata.
