### ISSUE TITLE
Framework detection in metadata generator is not working for every case

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/ios-runtime#420]
On device (iPhone 6) `CoreSpotlight` framework is not considered to be a shared framework by metadata generator and thus is not loaded at runtime by the `SymbolLoader`. It turns out that Clang can't find binary file coresponding to `CoreSpotlight` framework and we throw an error [here](https://github.com/NativeScript/ios-metadata-generator/blob/master/src/Binary/binarySerializer.cpp#L189). This happens only on device.

**Comment by jasssonpet** [comment]
I suggest that we always load system frameworks then.

**Comment by ivanbuhov** [comment]
I agree, but which varaint do you prefer:
1. The metadata generator to check if it is system framework and if true - set the framework flag to true.
2. Do not touch metadata generator. At runtime if isFramework() or isSystem() returns true - try to load it.

**Comment by jasssonpet** [comment]
The first  variant looks better to me.

**Comment by ivanbuhov** [comment]
:+1:
