### ISSUE TITLE
Undefined error when trying to load a native cocoapod object

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/ios-runtime#429]
https://groups.google.com/forum/#!topic/nativescript/GSQmabN0Rz0

https://developer.zendesk.com/embeddables/docs/ios/gettingstarted#using-the-sdk

Trying to create a zendesk plugin, but the method they say to use just crashes {N}, however the one they say to use for iPad seems to kinda work... why does {N} hate it so much?

```
var frameModule = require("ui/frame");
 
var isAnonymous = true;
var isInitalized = false;
 
var account = {
    appId: "",
    url: "",
    clientId: "",
}
 
exports.init = function(appId, url, clientId, isAnonymous){
    account.appId = appId;
    account.url = url;
    account.clientId = clientId;
    isInitalized = true;
    isAnonymous = isAnonymous;
}
 
/// Style from https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIViewController_Class/#//apple_ref/c/tdef/UIModalPresentationStyle
exports.openHelpCenter = function (style){
    if(isInitalized){
        ZDKConfig.instance().initializeWithAppIdZendeskUrlClientIdOnSuccessOnError(account.appId, account.url, account.clientId,
            //SUCCESS 
            function(){
                try{ 
                    if(isAnon){
                        loadAnonUser();
                    }
                     
                    var controller = frameModule.topmost().ios.controller;
                     
                    if(style === undefined){
                        controller.modalPresentationStyle = UIModalPresentationFormSheet;
                    } else{
                        controller.modalPresentationStyle = style;
                    }
                     
                    // THIS LINE WORKS FINE
                    ZDKHelpCenter.presentHelpCenterWithNavController(controller);
                   
                   // THIS ONE TANKS
                   //ZDKHelpCenter.showHelpCenterWithNavController(controller);
                } catch(args){
                    console.log(args);
                }
            }, 
            //ERROR 
            function zenDeskError(args){
                 console.log(args);
            });
    } else{
        console.log("Zendesk account info not initalized, please call the init function on the module");    
    }
}
 
exports.setLocale = function(locale) {
    ZDKConfig.instance().userLocale = locale;
}
 
function loadAnonUser(){
    var anonymousIdentity = new ZDKAnonymousIdentity();
    ZDKConfig.instance().setUserIdentity(anonymousIdentity);
}

```

**Comment by fealebenpae** [comment]
Hi @sitefinitysteve,

What sort of error do you get when calling `ZDKHelpCenter.showHelpCenterWithNavController(controller)`? Could you please attach the device log?

**Comment by sitefinitysteve** [comment]
This is what I see with -log

Project successfully built
Using  /Users/steve/Dropbox/Projects/Apps/OutbreakHelp/OutbreakHelp/platforms/ios/build/emulator/OutbreakHelp.app
Starting iOS Simulator
spawn: /usr/local/bin/node "/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/ios-sim.js" "launch" "/Users/steve/Dropbox/Projects/Apps/OutbreakHelp/OutbreakHelp/platforms/ios/build/emulator/OutbreakHelp.app" "ca.leaplearning.OutbreakHelp" "--logging"
Dec  7 10:19:37 deli-pc4 backboardd[12309]: SecTaskCopyDebugDescription: OutbreakHelp[13264]

Dec  7 10:19:37 deli-pc4 backboardd[12309]: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
Dec  7 10:19:37 deli-pc4 backboardd[12309]: SecTaskCopyDebugDescription: OutbreakHelp[13264]
Dec  7 10:19:37 deli-pc4 backboardd[12309]: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
Dec  7 10:19:37 deli-pc4 backboardd[12309]: SecTaskCopyDebugDescription: OutbreakHelp[13264]
Dec  7 10:19:37 deli-pc4 backboardd[12309]: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
Dec  7 10:19:37 deli-pc4 backboardd[12309]: SecTaskCopyDebugDescription: OutbreakHelp[13264]
Dec  7 10:19:37 deli-pc4 backboardd[12309]: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
Dec  7 10:19:37 deli-pc4 backboardd[12309]: SecTaskCopyDebugDescription: OutbreakHelp[13264]

Dec  7 10:19:37 deli-pc4 OutbreakHelp[13264]: assertion failed: 15B42 13B137: libxpc.dylib + 71730 [D938B614-A290-3D25-8032-8DEF8A01913A]: 0x7d

Dec  7 10:19:41 --- last message repeated 3 times ---
Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: file:///app/tns_modules/ui/frame/frame.js:229:31: JS ERROR TypeError: undefined is not an object (evaluating 'newEntry.resolvedPage')

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 1   0x1024c0 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 2   0x7085b6 ffi_closure_SYSV_inner

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 3   0x708002 .LCFI7

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 4   0x1da00da -[UINavigationController _startCustomTransition:]

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 5   0x1db1bf5 -[UINavigationController _startDeferredTransitionIfNeeded:]

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 6   0x1db2e3b -[UINavigationController __viewWillLayoutSubviews]

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 7   0x1f8e193 -[UILayoutContainerView layoutSubviews]

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 8   0x1c63eb7 -[UIView(CALayerDelegate) layoutSublayersOfLayer:]

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 9   0x326d059 -[NSObject performSelector:withObject:]

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 10  0x116380a -[CALayer layoutSublayers]

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 11  0x11574ee CA::Layer::layout_if_needed(CA::Transaction*)

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 12  0x1157352 CA::Layer::layout_and_display_if_needed(CA::Transaction*)

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 13  0x1149e8b CA::Context::commit_transaction(CA::Transaction*)

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 14  0x117de03 CA::Transaction::commit()

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 15  0x117e6c4 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*)

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 16  0x36b161e __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 17  0x36b157e __CFRunLoopDoObservers

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 18  0x36a6efc __CFRunLoopRun

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 19  0x36a6706 CFRunLoopRunSpecific

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 20  0x36a651b CFRunLoopRunInMode

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 21  0x4d8b664 GSEventRunModal

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 22  0x4d8b4a1 GSEventRun

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 23  0x1b9a1eb UIApplicationMain

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 24  0x707f1d .LCFI1

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 25  0x7084ff ffi_call

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 26  0xd1e43 NativeScript::FFICall::call(JSC::ExecState*)

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 27  0x4a1e54 JSC::LLInt::setUpCall(JSC::ExecState*, JSC::Instruction*, JSC::CodeSpecializationKind, JSC::JSValue, JSC::LLIntCallLinkInfo*)

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 28  0x49e6a6 llint_slow_path_call

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 29  0x4a6ae3 llint_entry

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 30  0x4a6af3 llint_entry

Dec  7 10:19:41 deli-pc4 OutbreakHelp[13264]: 31  0x4a6af3 llint_entry

Dec  7 10:19:41 deli-pc4 com.apple.CoreSimulator.SimDevice.3607EE15-7B8D-46AE-9DE4-2526D5E91E1F.launchd_sim[12291] (UIKitApplication:ca.leaplearning.OutbreakHelp[0x87a1][13264]): Service exited due to signal: Segmentation fault: 11

**Comment by fealebenpae** [comment]
Looking at the log there seems to be a JavaScript error:
```
Dec 7 10:19:41 deli-pc4 OutbreakHelp[13264]: file:///app/tns_modules/ui/frame/frame.js:229:31: JS ERROR TypeError: undefined is not an object (evaluating 'newEntry.resolvedPage')
```

This means that the crash isn't in the call to the `+[ZDKHelpCenter showHelpCenterWithNavController:]` method itself, but might be caused by something related to it. Judging by the stack trace, it looks as if the method is trying to perform a transition which crashes the NativeScript layout logic. @hshristov, can you take a look, please?

**Comment by hshristov** [comment]
@sitefinitysteve Could you send me zip with the project and I will take a look into it?
We do have some requirements but I might be able to reduce them.

**Comment by sitefinitysteve** [comment]
Here's the plugin
https://github.com/sitefinitysteve/nativescript-zendesk

Everything should come in on gradle build

If you need credentials shoot me an email and I'll be happy to share
http://www.sitefinitysteve.com/contact

**Comment by sitefinitysteve** [comment]
This all works fine now
