### ISSUE TITLE
[Responder window]: unrecognized selector sent to instance 0x7b195820

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/ios-runtime#430]
Here's the plugin:
https://github.com/sitefinitysteve/nativescript-zendesk

Contact me http://www.sitefinitysteve.com/contact if you need some zendesk app keys to try it, I'd rather not post them :)

So just load it, and try to create a new ticket
http://www.screencast.com/t/NqCOOHYZ

Dec  5 19:22:57 Steves-MBP OutbreakHelp[5318]: -[Responder window]: unrecognized selector sent to instance 0x7b08bfc0

Dec  5 19:22:57 Steves-MBP OutbreakHelp[5318]: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[Responder window]: unrecognized selector sent to instance 0x7b08bfc0'
	*** First throw call stack:
	(
		0   CoreFoundation                      0x037faa84 __exceptionPreprocess + 180
		1   libobjc.A.dylib                     0x032bbe02 objc_exception_throw + 50
		2   CoreFoundation                      0x03803dd3 -[NSObject(NSObject) doesNotRecognizeSelector:] + 275
		3   CoreFoundation                      0x03741cdd ___forwarding___ + 1037
		4   CoreFoundation                      0x037418ae _CF_forwarding_prep_0 + 14
		5   OutbreakHelp                        0x0012933d -[ZDKCreateRequestViewController shouldEnableAttachments] + 770
		6   OutbreakHelp                        0x00128d88 -[ZDKCreateRequestViewController tableView:cellForRowAtIndexPath:] + 1003
		7   UIKit                               0x01d82a19 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 782
		8   UIKit                               0x01d82b47 -[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 90
		9   UIKit                               0x020dcad8 -[_UITableViewUpdateSupport(Private) _setupAnimationsForExistingOffscreenCells] + 1106
		10  UIKit                               0x020e083e -[_UITableViewUpdateSupport _setupAnimations] + 197
		11  UIKit                               0x01d56fd3 -[UITableView _updateWithItems:updateSupport:] + 3653
		12  UIKit                               0x01d4ec91 -[UITableView _endCellAnimationsWithContext:] + 17491
		13  UIKit                               0x01d68f57 -[UITableView endUpdatesWithContext:] + 51
		14  UIKit                               0x01d68f85 -[UITableView endUpdates] + 41
		15  OutbreakHelp                        0x00124f57 -[ZDKCreateRequestViewController sizeTextViewToContent:] + 998
		16  OutbreakHelp                        0x00124b61 -[ZDKCreateRequestViewController layoutTextView] + 378
		17  OutbreakHelp                        0x0012465a -[ZDKCreateRequestViewController layoutContent] + 69
		18  OutbreakHelp                        0x00124430 -[ZDKCreateRequestViewController viewWillAppear:] + 127
		19  UIKit                               0x01dcd50f -[UIViewController _setViewAppearState:isAnimating:] + 659
		20  UIKit                               0x01dcdbff -[UIViewController __viewWillAppear:] + 147
		21  UIKit                               0x01e13c86 -[UINavigationController _startTransition:fromViewController:toViewController:] + 1075
		22  UIKit                               0x01e14ce0 -[UINavigationController _startDeferredTransitionIfNeeded:] + 1038
		23  UIKit                               0x01e15e3b -[UINavigationController __viewWillLayoutSubviews] + 68
		24  UIKit                               0x01ff1193 -[UILayoutContainerView layoutSubviews] + 252
		25  UIKit                               0x01cc6eb7 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 813
		26  libobjc.A.dylib                     0x032d0059 -[NSObject performSelector:withObject:] + 70
			27  QuartzCore                          0x011c680a -[CALayer layoutSublayers] + 144
		28  QuartzCore                          0x011ba4ee _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 388
		29  QuartzCore                          0x011ba352 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 26
		30  QuartzCore                          0x011ace8b _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 317
		31  QuartzCore                          0x011e0e03 _ZN2CA11Transaction6commitEv + 561
		32  QuartzCore                          0x011e2674 _ZN2CA11Transaction17flush_transactionEv + 50
		33  UIKit                               0x01c2dc8a _afterCACommitHandler + 197
		34  CoreFoundation                      0x0371461e __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 30
		35  CoreFoundation                      0x0371457e __CFRunLoopDoObservers + 398
		36  CoreFoundation                      0x03709efc __CFRunLoopRun + 1340
		37  CoreFoundation                      0x03709706 CFRunLoopRunSpecific + 470
		38  CoreFoundation                      0x0370951b CFRunLoopRunInMode + 123
		39  GraphicsServices                    0x04dee664 GSEventRunModal + 192
		40  GraphicsServices                    0x04dee4a1 GSEventRun + 104
		41  UIKit                               0x01bfd1eb UIApplicationMain + 160
		42  OutbreakHelp                        0x0076af1d .LCFI1 + 26
		43  OutbreakHelp                        0x0076b4ff ffi_call + 132
		44  OutbreakHelp                        0x00134e43 _ZN12NativeScript7FFICall4callEPN3JSC9ExecStateE + 275
		45  OutbreakHelp                        0x00504e54 _ZN3JSC5LLInt9setUpCallEPNS_9ExecStateEPNS_11InstructionENS_22CodeSpecializationKindENS_7JSValueEPNS_17LLIntCallLinkInfoE + 516
		46  OutbreakHelp                        0x005016a6 llint_slow_path_call + 182
		47  OutbreakHelp                        0x00509ae3 llint_entry + 17078
		48  OutbreakHelp                        0x00509af3 llint_entry + 17094
		49  OutbreakHelp                        0x00509af3 llint_entry + 17094
		50  OutbreakHelp                        0x00509af3 llint_entry + 17094
		51  ???                                 0x28330817 0x0 + 674433047
		52  OutbreakHelp                        0x0049b48c _ZN3JSC7JITCode7executeEPNS_2VMEPNS_14ProtoCallFrameE + 172
		53  OutbreakHelp                        0x0047bdd9 _ZN3JSC11Interpreter11executeCallEPNS_9ExecStateEPNS_8JSObjectENS_8CallTypeERKNS_8CallDataENS_7JSValueERKNS_7ArgListE + 425
		54  OutbreakHelp                        0x005e6401 _ZN3JSC4callEPNS_9ExecStateENS_7JSValueENS_8CallTypeERKNS_8CallDataES2_RKNS_7ArgListERN3WTF8NakedPtrINS_9ExceptionEEE + 97
		55  OutbreakHelp                        0x0016fb9b -[TNSRuntime executeModule:] + 1611
		56  OutbreakHelp                        0x000b17ae main + 1006
		57  libdyld.dylib                       0x0815fa21 start + 1
	)
Dec  5 19:22:57 Steves-MBP SpringBoard[381]: HW kbd: Failed to set (null) as keyboard focus

Dec  5 19:22:57 Steves-MBP com.apple.CoreSimulator.SimDevice.3607EE15-7B8D-46AE-9DE4-2526D5E91E1F.launchd_sim[364] (UIKitApplication:ca.leaplearning.OutbreakHelp[0x5461][5318]): Service exited due to signal: Abort trap: 6

**Comment by fealebenpae** [comment]
Hi @sitefinitysteve,

It seems that `-[ZDKCreateRequestViewController shouldEnableAttachments]` calls `[UIApplication sharedApplication].delegate.window`. The default `UIApplicationDelegate` that ships with NativeScript does not implement the `window` property, because it is required for storyboards, and NativeScript does not use storyboards at this time.

This is a bug in the Zendesk SDK - it is entirely possible that the application delegate does not implement the `window` property, or that there isn't an application delegate in the first place. The Zendesk SDK fails to account for these scenarios and tries to access the key window using the application delegate, instead of the `+[UIWindow keyWindow]` accessor which is far more appropriate.

Normally in an application you could circumvent this by simply implementing the `window` property on the application delegate, but since NativeScript plugins can't influence the application delegate class, you'd have to use a version of the Zendesk SDK that fixes the `window` bug.

**Comment by sitefinitysteve** [comment]
Thx!  Put in a support ticket with Zen

**Comment by AntonioCuevaUrraco** [comment]
Hei, @fealebenpae is there a way to implement the window property on the application delegate manually with NativeScript? It would be a workaround to make zendesk work in the meanwhile

**Comment by fealebenpae** [comment]
@AntonioCuevaUrraco: check out our example [here](https://github.com/NativeScript/ios-runtime/blob/master/examples/Gameraww/app/index.js).

**Comment by AntonioCuevaUrraco** [comment]
Great I got it to work :-) I will talk with @sitefinitysteve to ask the users of the plugin to add the window to the delegate if they want to use it right now

**Comment by NathanaelA** [comment]
Just a FYI for anyone I just ran into this same issue on another plugin, wasted several hours trying to figure out what it was as it was a "random" crash.   Going to do a PR so that hopefully nobody else runs into this in the future.  :grinning:
