### ISSUE TITLE
Wrong font of same name being loaded 

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/ios-runtime#445]
I add the following font files

"Lato.ttf"
"Lato-Light.ttf"
"Lato-Bold.ttf"

In my code if I do this
```
var font = UIFont.fontWithNameSize("Lato", 16)
```
The value of font seems to be "Lato-Light"

I can also specify Lato-Light and Lato-Bold in fontWithNameSize to get the right one back, but the only way to seemingly load Lato regular is to delete Lato-Light from /fonts.

**Comment by N3ll** [comment]
@sitefinitysteve , this seems to be an iOS problem. What I can suggest is to try renaming the files:
Lato-Light.ttf -> LatoLigt.ttf and check if this will work. Another thing that you can try is to use this [CocoaPod](https://www.cocoacontrols.com/controls/latofont) in a plugin.

**Comment by sitefinitysteve** [comment]
Yeah I saw it was a native call, was just hoping that MAYBE in some way it was the runtime that was doing something wrong :)  Okay thanks!
