### ISSUE TITLE
Keep the app bundle and build versions in source control

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#448]
We need a convenient way to set the versionCode and versionName of an app when we are sending it to the AppStore. Currently it can be set manually in the ios project generated in the platforms folder but we try to keep it out of source control.

So a few options are to keep them in:
 - app/App_Resources/ios/Info.plist
 - package.json
 - anywhere appropriate for source control

**Comment by fealebenpae** [comment]
+1 for App_Resources: https://github.com/NativeScript/nativescript-cli/issues/1089

**Comment by PanayotCankov** [comment]
Info.plist in App_Resources is the first thing in my todo list for the next year. When the android is ready with their counterpart we'll just have to document this.

**Comment by atanasovg** [comment]
This is already implemented, closing the issue.
