### ISSUE TITLE
Allow inherited Objective-C classes in TypeScript to be minified

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/ios-runtime#451]
We currently register a native class with the name of the provided JavaScript class. However, during minification, class names become `a`, `b`, `c`... and sometimes collisions occur.

This is required for the Angular integration - https://github.com/NativeScript/nativescript-angular/wiki/Benchmarks#startup-time

**Comment by fealebenpae** [comment]
I have an idea - let's deprecate inheriting from native classes in TypeScript's ES5 output and remove it in 2.0 :grin: 

But seriously, this causes problems every orher release.

**Comment by jasssonpet** [comment]
We can also use the `--reserved` or `--reserved-file` flags of [UglifyJS](https://github.com/mishoo/UglifyJS2).

> ... you can use `--reserved-file` to pass a filename that should contain the names to be excluded from mangling. This file can be used both for excluding variable names and property names.

**Comment by jasssonpet** [comment]
The implementation with custom static property name/decorator for the Objective-C class name seems to be not possible at the moment, because it isn't accessible by the time our custom `__extends` function is called.
