### ISSUE TITLE
Separate Debugger UI into a dedicated npm package

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/ios-runtime#474]
The goal is to improve the user experience. Due to the size of the tns-ios package, people are noticing that operations are slow, especially when using slow connection.

High-level overview of tasks:

 - [x] Extract debugger UI into dedicated package
 - [x] Publish the debugger package to npmjs.org
 - [x] Change the CLI to consume the new package

See https://github.com/NativeScript/nativescript-cli/issues/1382 and https://github.com/NativeScript/nativescript-cli/pull/1385 for example why this change would be beneficial.

**Comment by teobugslayer** [comment]
ping @fealebenpae

**Comment by jasssonpet** [comment]
Do you think it's worth it to make it to a separate repo, like the metadata generator has one?

**Comment by fealebenpae** [comment]
@jasssonpet our build infrastructure would blow up because of the new webkit submodules that would spawn :grin:

**Comment by jasssonpet** [comment]
We already have a separate build for the App Inspector, so I don't see how a separate repository has to do with our build infrastructure.

**Comment by fealebenpae** [comment]
We do on the build machines, not on the dev workstations. Would it enhance our workflow or help in any way if we spin off the inspector?

**Comment by jasssonpet** [comment]
I see the App Inspector as a separate tool with it's own build and distribution. I was just asking if it would make sense to have it's own repo. If we agree that it's too much of a hassle to separate it - I'm fine with leaving it as it is :smile:

**Comment by fealebenpae** [comment]
I think I understand - I don't really perceive a "single distributable deliverable by repository" constraint. In all fairness, I'm against separating the code of the inspector at this point both because I can't think of anything we'd gain by this and because I regret splitting the metadata generator in its own repository - all that gained us was countless "updating metadata generator" pull requests.

**Comment by teobugslayer** [comment]
Can we do this in the 1.6 time frame? The CLI team has the capacity to do it.

**Comment by fealebenpae** [comment]
@teobugslayer Yes, @KristinaKoeva has committed to it.

**Comment by teobugslayer** [comment]
Great news!

**Comment by teobugslayer** [comment]
Note for testing: builds of ios runtime from master are treated like "beta" and semver considers them less than 1.6.0. To test, one need to manually adjust their version to 1.6.0 or later.
