### ISSUE TITLE
Global/App Lifetime iOS View?

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/ios-runtime#481]
Does the normal view get totally destroyed when switching pages; or does only part of the view get destroyed?  Apparently a WKWebView must be attached to a view for it to do any processing; is their a global view I can attach it to (the WKWebView doesn't actually need to be visible)?    

This is for the NativeScript-webworkers project; I'd rather use WKWebView on iOS than UIWebView; but UIWebView will work being totally unattached.

**Comment by fealebenpae** [comment]
The runtime doesn't know about views. You're better off asking in https://github.com/NativeScript/NativeScript.

I would try adding the WKWebView as a child of the key window (`UIWindow.keyWindow()`) with a frame such that it is off-screen.

**Comment by NathanaelA** [comment]
@fealebenpae thanks for the pointers.

**Comment by roblav96** [comment]
@NathanaelA You can use `CGRectZero` as the frame for your `WKWebView`:
```typescript
let config = WKWebViewConfiguration.new()
this._ios = WKWebView.alloc().initWithFrameConfiguration(CGRectZero, config)
```

**Comment by NathanaelA** [comment]
@roblav96 - Yeah, I've had this working since Jan of last year.   ;-)    I didn't want to attach it to the current display because I needed the webview to continue running even when navigating to any other pages.   

However, in the grand scheme of things v2.4 of NativeScript actually depreciates this ns-webworkers plugin as the real webworkers are WAY WAY better than my polyfil.  ;-)
