### ISSUE TITLE
Eval-ing modules twice when [supposedly] using relative paths in `require`

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/ios-runtime#490]
First reported in NativeScript/nativescript-angular#38. It appears that in Angular projects we can require `rxjs/Observable` twice. This leads to some issues when attaching extension operators (e.g. `map` to the Observable prototype):

- Operator methods get attached to the first prototype definition when requiring `rxjs/add/operator/map`. Done in application code (as documented in the RXJS and Angular docs).
- The second require (inside `angular2/src/facade/async`) redefines the `Observable` function and prototype, of course without the extension methods. That causes a crash in client code that relies on `map` being available.

The problem is reproducible [in this project](https://github.com/hdeshev/test_mobile/tree/login-http-get) (use the `login-http-get` branch).

My observations so far:

1. This doesn't happen on Android.
2. The problem goes away if I change all `../Observable`, `../../Observable`, etc requires to `rxjs/Observable` in the application, `rxjs/add/operator/map` and the Angular async facade code.

**Comment by fealebenpae** [comment]
Is this behavior observed on the latest 1.5 release, or in the master branch?

**Comment by hdeshev** [comment]
Official 1.5 release.
