### ISSUE TITLE
NSDate types need to be updated in ios.d.ts

### ISSUE THREAD

**Issue by enchev** [NativeScript/ios-runtime#496]
_From @speigg on January 25, 2016 20:1_

Due to auto-marshalling, many of the api's defined in `ios.d.ts` are now incorrectly declared as returning `NSDate` objects when they should instead be declared to return `Date` objects. I'm not sure if this is also needed the other way around (presumably apis that are declared as accepting `NSDate` objects should be changed to declare that they accept `Date` objects?). 

_Copied from original issue: NativeScript/NativeScript#1436_

**Comment by fealebenpae** [comment]
The `ios.d.ts` file you refer to was generated a long time ago by an external tool and has now fallen somewhat out of sync with the runtime.

The NativeScript Objective-C metadata generator can generate typings that describe native APIs and it handles `NSDate` correctly. You can see how to generate typings [here](http://docs.nativescript.org/runtimes/ios/how-to/Use-Native-Libraries#troubleshooting).
