### ISSUE TITLE
Generate TypeScript Declarations for Modules with the C++ Generator

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#52]
We are working on polishing the MetadataGenerator by rewriting it in C++.
Also we are planning to introduce a mechanism to "require" modules.
(e.g classes from _UIKit_ will be available by using a `require("UIKit")`)

So we will need the TypeScript declarations generator ported from the C# project to the C++ one.

**Comment by jasssonpet** [comment]
The following definition fails with TypeScript 1.5
```
declare class NSExpression extends NSObject implements NSSecureCoding, NSCopying {
    // ...
    arguments: NSArray;
    // ...
```

**Comment by PanayotCankov** [comment]
This one now waits for #165 that will change the implementation of how clang modules are exposed in the JavaScript.

**Comment by PanayotCankov** [comment]
This issue is now irrelevant.
