### ISSUE TITLE
Update iOS TypeScript definitions for the NativeScript modules

### ISSUE THREAD

**Issue by atanasovg** [NativeScript/ios-runtime#523]
After https://github.com/NativeScript/ios-runtime/issues/318 was introduced, the way enum fields are accessed has changed. We need to update the modules definition file to eliminate issues like https://github.com/NativeScript/NativeScript/pull/1689#issuecomment-191724984.

**Comment by vbresults** [comment]
Done: https://github.com/vbresults/NativeScript/blob/ios-definition-armageddon/ios.d.ts

I goofed when forking by not creating a branch first, so when the pull request you mentioned is merged, I'll reset my repo so it's not ahead of master by X commits and make a new branch.

Then I'll upload the updated definitions into that branch and open a pull request.  Something's been on my mind though -- backwards compatibility with the old format.  How does the runtime handle this?

**Comment by jasssonpet** [comment]
I totally agree, that the iOS declarations are dated and should be updated, but at the moment enums are exposed in the following (backwards compatible with the current ios.d.ts file) way:

```javascript
global.UIWebViewNavigationType = {
  "UIWebViewNavigationTypeLinkClicked": 0,
  "UIWebViewNavigationTypeFormSubmitted": 1,
  "UIWebViewNavigationTypeBackForward": 2,
  "UIWebViewNavigationTypeReload": 3,
  "UIWebViewNavigationTypeFormResubmitted": 4,
  "UIWebViewNavigationTypeOther": 5,

  "LinkClicked": 0,
  "FormSubmitted": 1,
  "BackForward": 2,
  "Reload": 3,
  "FormResubmitted": 4,
  "Other": 5,

  "0": "UIWebViewNavigationTypeLinkClicked",
  "1": "UIWebViewNavigationTypeFormSubmitted",
  "2": "UIWebViewNavigationTypeBackForward",
  "3": "UIWebViewNavigationTypeReload",
  "4": "UIWebViewNavigationTypeFormResubmitted",
  "5": "UIWebViewNavigationTypeOther",
};
```
