### ISSUE TITLE
Add additional header search path in the project template

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/ios-runtime#526]
[Sometimes when consuming third-party libraries or pods](https://github.com/NativeScript/ios-runtime/issues/524), an additional `module.modulemap` file must be added somewhere in the header search paths of the underlying Xcode project. Currently, all header search paths are pointing to folders in `platforms/ios` and none of them is suitable for `module.modulemap` files coming from plugins (e.g.`platforms/ios/Pods/Headers` is cleaned by `pod install`). Currently, the solution is  to add the `module.modulemap` file manually in a specific path under `platforms/ios` after every cloning of the app codebase (and maybe after `plugin add`).
A possible solution is to add a header search path in the project template pointing to a path in `platforms/ios`, which can be used by plugins to store their custom `module.modulemap` files e.g. `/platforms/ios/headers`.

**Comment by sitefinitysteve** [comment]
+1 platforms folder should be volatile, don't want to have to keep merging in module.modulemap or whatever else.

**Comment by sitefinitysteve** [comment]
I've been trying to build a plugin with this all morning, and it's just endlessly frustring... module.modulemap just keeps getting blown away *sometimes* on debug, and I never know until I get into the debug and get the cant find variable error.

**Comment by ivanbuhov** [comment]
Hi @sitefinitysteve 
Lets continue the discussion of the concrete problem [here](https://github.com/NativeScript/ios-runtime/issues/524). I believe that your problem [has a solution](https://github.com/NativeScript/ios-runtime/issues/524#issuecomment-194748217) which doesn't require this feature.

**Comment by ivanbuhov** [comment]
Since we came up with a [working solution for such a scenario](https://github.com/NativeScript/ios-runtime/issues/524#issuecomment-194748217) I am closing the issue.
