### ISSUE TITLE
Building Today extension for Release

### ISSUE THREAD

**Issue by AntonioCuevaUrraco** [NativeScript/ios-runtime#528]
So we have been working in enabling a today extension for our NS app, once we solved the communication between the NS app and the extension everything was more or less easy (We want to write and article once this last problem is solve to help others).

So the problem is that if I build with the current schema the app works for Debug but not for release.
If I archive the build itunnes complains about the code not being sign. and if In the project/info/Configuration I change the Extension (MyStats) from none to build-release I get this errors. 
![screen shot 2016-03-14 at 9 52 04 am](https://cloud.githubusercontent.com/assets/13554060/13738113/3605362e-e9cb-11e5-8bc1-a9292ab56cce.png)
![screen shot 2016-03-14 at 9 54 23 am](https://cloud.githubusercontent.com/assets/13554060/13738120/3979a2ae-e9cb-11e5-8a28-5e673c25d734.png)

My nose is telling me that I have to add some build phases to the Today as in this article https://www.nativescript.org/blog/details/making-a-today-widget-in-ios-with-nativescript-and-ui-for-nativescript
But in my project there is no build metadata phase but 3 phases Prelink Prebuild PostBuild
So before I start fooling around maybe you guys know the answer to this :-D
@nikolay-diyanov

**Comment by ivanbuhov** [comment]
Hi @AntonioCuevaUrraco 
The metadata generation step mention in the blog post was replaced by the Prebuild phase which is doing the same thing (generates metadata file). The message on your screenshot says that it can't find metadata file. I suggest copying the Prebuild phase in the extension target. 
In case this doesn't make it work, can you describe the performed steps in the process of creating the project. I tried to reproduce the same issue by following the steps from the [blog post](https://www.nativescript.org/blog/details/making-a-today-widget-in-ios-with-nativescript-and-ui-for-nativescript) but I didn't managed to do it.

**Comment by jasssonpet** [comment]
Also here is the updated guide to using NativeScript extensions: https://github.com/NativeScript/ios-runtime-docs/blob/extensions-today-view/extensions/TodayExtension.md.

**Comment by AntonioCuevaUrraco** [comment]
Thank you for the answer guys, I will come back with feedback as soon as I have time to try it. 
@ivanbuhov the thing is that the Today extension was actually programmed on objective C as the developer has more knowledge of native development probably that's why you can't reproduce it.

 Also on the topic, I am trying to somehow source control the extensions because the platform of course have to be removed now and then. Is there some plan to help the developers about this? I don't mind to re-write everything in .js if I can have the extension plug automatically, especially now that I am working on get all this in Continuous Integration

**Comment by ivanbuhov** [comment]
Currently the NativeScript CLI doesn't support iOS extensions. If you think that this should have higher priority you can log it as an idea [here](https://nativescript.ideas.aha.io/ideas). However, you still can achieve the desired result by using [NativeScript CLI hooks](https://github.com/NativeScript/nativescript-hook). You can create plugin which declares an after-prepare hook. It will be called by the CLI after every execution of the prepare step. The hook should do all the manual work needed to set up the extension project. For example, you can store your `.h` and `.m` files under `{my-app}/native` and the hook will copy them in the correct folder in `platforms/ios`. You can edit the Xcode project file with [this](https://www.npmjs.com/package/xcode) to bring in all needed changes to make the extension project buildable.

**Comment by AntonioCuevaUrraco** [comment]
I used the updated guide for extensions and my project configuration is this one:
![screen shot 2016-03-18 at 8 59 13 am](https://cloud.githubusercontent.com/assets/13554060/13870875/58105f1c-ece8-11e5-8a2c-b3159243e350.png)

It was not archiving with the same error but I made two changes and I got it to work 

- Moved the pre-build script phase up
![screen shot 2016-03-18 at 8 58 37 am](https://cloud.githubusercontent.com/assets/13554060/13870852/2382391e-ece8-11e5-982e-96fab2fec347.png)

- And no bitcode
![screen shot 2016-03-18 at 8 58 54 am](https://cloud.githubusercontent.com/assets/13554060/13870864/38926522-ece8-11e5-84cc-25b691aaa606.png)

The problem is that apple won't accept it when I try to submit to app store. I export the app and then use application loader because xcode always reject with reason "try again". Also before I started to add the extension I submitted a version of the app with no problem using this method.
![screen shot 2016-03-18 at 8 57 50 am](https://cloud.githubusercontent.com/assets/13554060/13870930/e4c9f4cc-ece8-11e5-805d-3098aa820f0b.png)

I have been trying changing the provisioning profiles generating new certificates and all the checks of the first answer to this thread http://stackoverflow.com/questions/29859996/error-itms-90035
Even removing the platform and starting all over adding the extension the building is done but there is some problem with signing.

do you have some suggestion guys to try @ivanbuhov @jasssonpet ?   
do you know if someone successfully added an extension to NS platform and got to app store?

**Comment by ivanbuhov** [comment]
Hi @AntonioCuevaUrraco,
The error says "Code object is not signed at all". Make sure that you are signing your app with a distribution certificate. Check this in the build settings of the target (not the project) under `Code Signing Identity`. Follow [these steps](http://stackoverflow.com/questions/25837722/provisioning-profile-for-today-widget-extension/25981474#25981474) to configure your provisioning profiles. Also, make sure you are not skipping any step from [app publishing guide](https://docs.nativescript.org/core-concepts/publishing-ios-apps).

**Comment by AntonioCuevaUrraco** [comment]
Then thing is that there is "some code" that is not signed so I check what is being copied to the extension and I decided to give it a try with no app folder as I am just using the icons from the NS app and they communicate on the group.
- Skiped
Last but not least, select MYTodayApp/app and from the right hand pane file inspector, from the 'Target Membership' section check also the 'MYTodayExtension'.  

And the app when through I am starting the testing process now and I will come back with the final apple decision as well as our testing results.

Thank you guys for all the help

**Comment by dmatora** [comment]
>once we solved the communication between the NS app and the extension everything was more or less easy
@AntonioCuevaUrraco so how did you solve it?
