### ISSUE TITLE
Library must clean cashed metadata 

### ISSUE THREAD

**Issue by karaahmed** [NativeScript/ios-runtime#53]
I'm developing custom iOS framework for NativeScript . Once library added , the metadata folder is not updated anymore and have to be deleted by hand to apply new changes.

**Comment by fealebenpae** [comment]
Do you mean the `platforms/iOS/Metadata/Metadata-${ARCH}` folders? If you add, delete, or modify a metadata .yaml file within them, the Xcode project should register the change and recreate the final metadata package in the application executable automatically.

I'm afraid I can't understand the exact nature of the problem. Could you please walk me through the steps needed to reproduce it?

**Comment by PanayotCankov** [comment]
We have completely rewritten the metadata generator. It no longer involves the YAML files. The generation is Xcode build phase now. The metadata build fast enough to build every time and as far as I am aware they are not cached now.
