### ISSUE TITLE
Allow Objective-C classes extended in TypeScript to be declared with decorators

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#552]
The current implementation uses the TS __extend function to locate the constructor function in the parent scope of the __extend call and replace it. This fails some tools (fondue) we try to use because they wrap the __extend call in another function.

The TS decorator can look similar to the android `@JavaProxy`: https://github.com/NativeScript/NativeScript/blob/master/ui/frame/frame.android.ts#L569

This will allow our classes such as:
https://github.com/NativeScript/NativeScript/blob/master/ui/gestures/gestures.ios.ts#L10

To be prefixed with `@NSClass` or something and avoid the replacement that happens in __extend.

**Comment by PanayotCankov** [comment]
This can be implemented in pure JS on top of the existing <NSClass>.extend JS functionality.

**Comment by NathanWalker** [comment]
I didn't see this last year but definitely would have shared this with others to gather more interest. Really great idea here and I'd consider reopening and I would imagine interest would be much different at this time. I like @PeterStaev suggestion `@ObjCProtocols`, etc.
