### ISSUE TITLE
Question:overidden func from swift is not called by original class

### ISSUE THREAD

**Issue by enchev** [NativeScript/ios-runtime#553]
_From @x4080 on April 23, 2016 4:3_

Hello, my problem :
- I create a class in swift for example 
```
public class SwiftClass:NSObject {
    public init() {
		dosomething()
	}
	
	public func dosomething() { // override this
        NSLog("dosomething parent should not called !")
    }	
	
}
```

And I override it in NS using 
```
var MySwiftClass = SwiftClass.extend({
	dosomething: function () {
                    console.log('Success with overriding function');
                }
});
```

Then I create the object (NS)
```
           newclass = new MySwiftClass();

```

The output is "dosomething parent should not called !" and not 'Success with overriding function'

But if I call using
```
newclass.dosomething();
```

The output is correct which is 'Success with overriding function'

So is the problem because of the swift, or I missing something for overriding method in class?

Thanks

_Copied from original issue: NativeScript/NativeScript#2021_

**Comment by enchev** [comment]
_From @x4080 on April 23, 2016 4:7_

Oh and it works if I inherit the class in Swift project BTW

**Comment by KristinaKoeva** [comment]
Hey,

If you want to override a swift method you must mark your method with the ```dynamic``` attribute.

<pre>
public class SwiftClass:NSObject {
    public init() {
        dosomething()
    }

    public <b>dynamic</b> func dosomething() { // override this
        NSLog("dosomething parent should not called !")
    }   

} 
</pre>

For more information check [Using Swift with Cocoa and Objective-C](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html#//apple_ref/doc/uid/TP40014216-CH4-XID_38)

**Comment by x4080** [comment]
Thanks I'll try it

**Comment by x4080** [comment]
it works thanks

**Comment by KristinaKoeva** [comment]
I am glad it worked :)
