### ISSUE TITLE
Sending HTTP request while debugging is throwing error

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/ios-runtime#557]
using NativeScript Inspector with **tns debug ios** and http requests is throwing :
```
this.dispatchMessage is not a function. (In 'this.dispatchMessage', 'this.dispatchMessage' is undefined)
```
Code used to reproduce the behaviour: 
```
http.request({
        url: config.baseUrl,
        method: "POST",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        content: data
    }).then(function (response) {
        // Success
    }, function (e) {
        // error occur
    });
```

Related to [https://github.com/NativeScript/ios-runtime/pull/472](https://github.com/NativeScript/ios-runtime/pull/472)

**Comment by terreb** [comment]
Any updates on this? It's quite a serious issue, nor fetch or http module work in debug mode on iOS.

**Comment by terreb** [comment]
Any news on that? Please fix this guys, this issue is really annoying...

**Comment by KristinaKoeva** [comment]
There is an open PR that fixes the issue https://github.com/NativeScript/NativeScript/pull/2301 . Once it gets merged you can install the next version of NativeScript modules in the following way
``` tns plugin add tns-core-modules@next ```

**Comment by atanasovg** [comment]
PR merged, closing the issue.
