### ISSUE TITLE
Are the Build instructions correct still?

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/ios-runtime#559]
I've been attempting to get my local machine to build the full ios runtimes; and the instructions seems to possibly be out of date for llvm and the meta data generator.

Are you sure that llvm 3.8 is supposed to be used?   If you do a *brew install llvm38*, it is actually missing dozens of headers you need.   If I do a *brew install llvm38 --HEAD* I get most the headers, but still more are missing.   If I manually build llvm 3.8 from the repo I get all the headers finally; but then I'm missing LLVMCoverage which I assume your scripts are pulling in as I can't find any reference to this library anywhere in LLVM 3.8 -- Any pointers on where to find this missing file?

**Comment by ivanbuhov** [comment]
@NathanaelA, to build the metadata generator download a [pre-build llvm3.8 binary](http://www.llvm.org/releases/download.html#3.8.0). More detailed instructions how to install the binary you can find [here](https://github.com/NativeScript/ios-runtime/pull/547#issue-148688757).

**Comment by NathanaelA** [comment]
Awesome, thanks for the pointer.  I will try that out today.

**Comment by NathanaelA** [comment]
Thanks that worked!
