### ISSUE TITLE
Install Plugin failed archive to ITunes

### ISSUE THREAD

**Issue by enchev** [NativeScript/ios-runtime#567]
_From @yclau on May 24, 2016 8:20_

Hi 

### Tell us about the problem
I trying using plugin nativescript-material-loading-indicator and nativescript-loading-indicator, When I try to archive and publish to ITunes,it show me error below. After I remove loading-indicator and nativescript-material-loading-indicator, it work fine. 

```
ld: warning: directory not found for option '-F/Users/bae-nb-050/Library/Developer/Xcode/DerivedData/SL-fbodsjqbjvdhcgeemiobyapkoekm/Build/Intermediates/ArchiveIntermediates/SL/BuildProductsPath/Release-iphoneos/MBProgressHUD'
    ld: framework not found MBProgressHUD
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.0.1
- Cross-platform modules: 2.0.0
- Runtime(s): 2.0.0
- Plugin(s): 
1) nativescript-material-loading-indicator : 1.0.0
2) nativescript-loading-indicator 2.0.1
-cocoapods : 1.0.0

_Copied from original issue: NativeScript/NativeScript#2167_

**Comment by yclau** [comment]
Hi,

any update? I got urgent deployment for IOS. 
isn't got other method to by pass this case ?

**Comment by jasssonpet** [comment]
Hi @yclau,

I tried creating a new app and adding those plugins, but there were no build errors.
Are you trying to publish your app from the CLI or from Xcode. Also what's your Xcode version?

**Comment by yclau** [comment]
I using Xcode to publish and my xcode version : 7.2.1

**Comment by jasssonpet** [comment]
In such case, make sure that you open the `<project_name>.xcworkspace` and not the `<project_name>.xcodeproj` file. I receive the same error when building from the `xcodeproj` file.

**Comment by yclau** [comment]
Thank you, for helping solving. After I publish using Xcode, it showing this error
![screen shot 2016-05-26 at 3 51 28 pm](https://cloud.githubusercontent.com/assets/4135524/15567640/fcd07062-2359-11e6-970e-594fa313ea03.png)

**Comment by yclau** [comment]
Hi, any update? sorry for rushing

**Comment by yclau** [comment]
Hi,
I trying this https://github.com/NativeScript/nativescript-cli/issues/888 , still the same

**Comment by yclau** [comment]
Hi,
I try to take out below 2 line code in plist and success upload, but it show me missing status.

```
<key>UILaunchStoryboardName</key>
<string>LaunchScreen</string>
```
![untitled1](https://cloud.githubusercontent.com/assets/4135524/15696770/69a50c12-27e6-11e6-8383-1574f80ea19f.png)

**Comment by KristinaKoeva** [comment]
Have you look at this [stackoverflow entry](http://stackoverflow.com/questions/35841117/missing-compliance-in-status-when-i-add-built-for-internal-testing-in-test-fligh)

**Comment by atanasovg** [comment]
Closing this for now, @yclau if you still experience some issues let us know.
