### ISSUE TITLE
Custom swift library with custom plugin Error

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/ios-runtime#581]
_From @nor-bu on June 16, 2016 7:24_

I want create a custom plugin for Nativescript this plugin contains a custom shared universal framework written in Swift.

When i add my test framework to a test xcode project then it works fine. But when i add this framework to my nativescript test app and i call the library i get this error:

`File:///app/tns_modules/hello/index.js:8:15: ReferenceError: Metadata for "hello.Hello" found but symbol not available at runtime.`

I don't know what is the problem, pleas help me to understand this.

Here my repos for the test products:

[iOS Framework Github Repo](https://github.com/nor-bu/ios-framework-hello-world.git)

[Test App Github Repo](https://github.com/nor-bu/ns-hello-world-custom-plugin-library.git)

_Copied from original issue: NativeScript/NativeScript#2325_

**Comment by jasssonpet** [comment]
Hey @nor-bu,

I see that the compiled framework is built only for x86_64 architecture. Are you testing it on the iPhone 6 simulator or similar? That maybe the problem.

**Comment by nor-bu** [comment]
Thank you very very much, it works
