### ISSUE TITLE
Incorrect behavior when uncaught exception of type NS Exception is thrown and the phone is connected with cable

### ISSUE THREAD

**Issue by vhristov5555** [NativeScript/ios-runtime#591]
1. Create App which throws an uncaught exception of type NS Exception:
var arr = new NSArray();
var o = arr.objectAtIndex(5); 
2. Connect IPhone with cable
3. Deploy the app to the phone:
tns run ios

Actual Result: The App will be stuck and it will remain open. If you disconnect the phone from the cable the App will be closed

Expected Result: The App to be closed because uncaught exception is raised

Note: Reproduce it with IPhone 5S - IOS 8.3

**Comment by jasssonpet** [comment]
This is because the process is being stopped with `SIGABRT` and the `GDBSignalWatcher` is waiting only for `SIGKILL`.

**Comment by jasssonpet** [comment]
This issue was moved to NativeScript/nativescript-cli#2053
