### ISSUE TITLE
Cannot run on iOS emulator

### ISSUE THREAD

**Issue by N3ll** [NativeScript/ios-runtime#613]
I am receiving an error when running on iOS platform. What I did is just creating a default project and adding the platforms. I have recently upgraded to NativeScript 2.1.1 and I am using Xcode Version 7.1 (7B91b). If you need any other info please let me know (^_^)

The error is the following:

> Nellys-MacBook-Pro:test Nelly$ tns emulate ios
> Successfully prepared plugin tns-core-modules for ios.
> The iOS Deployment Target is now 8.0 in order to support Cocoa Touch Frameworks.
> Successfully prepared plugin tns-core-modules-widgets for ios.
> Command failed: /bin/sh -c ruby -e "require 'xcodeproj'; Xcodeproj::Config.new('/Users/Nelly/Developerin/test/platforms/ios/plugins-debug.xcconfig').merge(Xcodeproj::Config.new('/Users/Nelly/Developerin/test/app/App_Resources/iOS/build.xcconfig')).save_as(Pathname.new('/Users/Nelly/Developerin/test/platforms/ios/plugins-debug.xcconfig'))"
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- xcodeproj (LoadError)
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from -e:1:in `<main>'

**Comment by KristinaKoeva** [comment]
Hey Neli, hope you are doing well :)
We have a dependency to [xcodeproj ruby gem](https://github.com/CocoaPods/Xcodeproj) that is required in order to  build you project for iOS. You may install it manually in the following way 
```
$ [sudo] gem install xcodeproj
```
Let us know if this doesn't resolve your problem

**Comment by N3ll** [comment]
Thank you for the fast answer, Kris! It works like a charm now! :)
