### ISSUE TITLE
Returning certain values from native iOS code results in immediate crash

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/ios-runtime#622]
_From @bnussey on August 11, 2016 6:25_

Since the latest NativeScript release (2.2.0) returning certain values from native iOS code results in a crash. I contribute to nativescript-videoplayer and since the new release, this line of code are resulting in an immediate crash:

```        
return this._player.currentTime().value
```
`this._player` is `AVPlayer`
`currentTime` relates to this method on the AVPlayer - https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVPlayer_Class/#//apple_ref/occ/instm/AVPlayer/currentTime
Full code can be reviewed here: https://github.com/bradmartin/nativescript-videoplayer/blob/master/videoplayer.ios.ts#L113

This is the crash message:

```
com.apple.CoreSimulator.SimDevice.7D812403-FB85-469B-9C88-1B286BC7DF9F.launchd_sim[11559] (UIKitApplication:com.stageme.app[0x6ba9][12379]): Service exited due to signal: Segmentation fault: 11
```

This was working absolutely fine before the upgrade.

In terms of doing some research about the error message, I found this: http://stackoverflow.com/a/23798704/3900606

_Copied from original issue: NativeScript/NativeScript#2568_

**Comment by jasssonpet** [comment]
Hi @bnussey,
Thanks for reporting this bug. The problem seems to be related to how the iOS runtime handles struct marshalling on x86_64 architecture. The 2.2 NativeScript CLI now builds for this architecture by default.

In the meantime you can use a 32-bit simulator, like the iPhone 4s one. We'll provide a fix shortly.

**Comment by NathanaelA** [comment]
Does this affect real devices or just the Emulator?

**Comment by bnussey** [comment]
Hey @jasssonpet no problems at all. Thanks for the prompt response. @NathanaelA only tested on the emulator, so not sure.

**Comment by jasssonpet** [comment]
@NathanaelA I have tested on an armv7 and arm64 device and there marshalling seems to be working fine.

**Comment by bnussey** [comment]
hey @jasssonpet do you know when this will be released? Thanks

**Comment by jasssonpet** [comment]
Hi, we are expecting to release a hotfix in the next few days.

**Comment by vchimev** [comment]
@bnussey, @jasssonpet, 
tns-ios@2.2.1 was just published to npm.

**Comment by bnussey** [comment]
Hey @vchimev and @jasssonpet confirming issue is fixed, thanks so much!
