### ISSUE TITLE
Calling dialogsModule.alert inside a custom modal page

### ISSUE THREAD

**Issue by roblav96** [NativeScript/ios-runtime#636]
Currently it is not possible to call `modalModule.alert` while a custom modal page is open.

Error:
```
Sep  3 00:12:21 Robs-MBP client[17765]: Warning: Attempt to present <UIAlertController: 0x7ff2e60c89a0> on <UIViewControllerImpl: 0x7ff2e378dda0> whose view is not in the window hierarchy!
```
I'm not sure if this a bug or an iOS limitation, but I thought I'd post an issue just in case.

Thank you!

**Comment by jasssonpet** [comment]
This issue was moved to NativeScript/NativeScript#2675
