### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by roblav96** [NativeScript/ios-runtime#637]
I can't get this to build for some reason. On my macbook I could run `git submodule update --init` no problem but on my mac desktop I can't.

I tried cloning via `https` and the desktop app but I still get this error:
```
roblav96@Roberts-iMac:/Volumes/OSX HD/Projects/ios-runtime$ git submodule update --init
Cloning into 'src/libffi'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:NativeScript/libffi.git' into submodule path 'src/libffi' failed
```

**Comment by roblav96** [comment]
Fixed by following this guide:

> https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

**Comment by Lelelo1** [comment]
Yes it seems it was needed to add a ssh key to GitHub account
