### ISSUE TITLE
build.sh does not produce a dist/tns-ios-*.tgz file

### ISSUE THREAD

**Issue by roblav96** [NativeScript/ios-runtime#639]
Instead, it produces a `dist/TKLiveSync.framework` file.

And when I try:
```
tns platform add ios --framework-path /Users/roblav96/Downloads/ios-runtime/dist/TKLiveSync.framework
```
I get this error:
```
Failed to retrieve data from npm. Please try again a little bit later.. Error: Error: EISDIR: illegal operation on a directory, read
```
makes me think the `TKLiveSync.framework` is not the `tns-ios-*.tgz` I'm looking for.

I also tried adding `--symlink` and I get this error:
```
The project file is corrupted. Additional technical information: SyntaxError: Unexpected token } in JSON at position 237
```

Git cloned off `master` branch.

**Comment by jasssonpet** [comment]
The build script should also produce NativeScript.framework and tns-ios package. Can you copy the last few lines of the `build.log` file in the root of the repo? That would give more clues to what's happening.

**Comment by roblav96** [comment]
Here's the terminal:
![terminal](http://i.imgur.com/BYjXVyz.png)
`ios-runtime/cmake-build`
![ios-runtime/cmake-build](http://i.imgur.com/rPQ9CYD.png)
![ios-runtime/dist](http://i.imgur.com/BhjoGMy.png)
`build.log`
```
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/roblav96/Downloads/ios-runtime/cmake-build
Build settings from command line:
 ```

**Comment by jasssonpet** [comment]
What version of CMake are you using? We have some issues with newer ones.

Also try installing [xcpretty](https://github.com/supermarin/xcpretty) and running the build again. I remember this fixing such issues on some terminals.

**Comment by roblav96** [comment]
```
cmake version 3.6.1
```
![build](http://i.imgur.com/CC9jadv.png)
It looks like I'm getting closer, but the directories look the same as posted above with no `.tgz` or `.framework` files.

**Comment by jasssonpet** [comment]
CMake 3.6 has some incompatibilities with our JavaScriptCore build. Can you try with the one listed in the README (`cmake --version` should be 3.1.3).

**Comment by roblav96** [comment]
15 minutes later, and 40% battery gone, still building...
I'm gonna say it's working. 🍰  😄 

Thank you!!!
