### ISSUE TITLE
LiveEdit

### ISSUE THREAD

**Issue by KristinaKoeva** [NativeScript/ios-runtime#649]
LiveEdit lets you make changes to your JavaScript source files and see those changes applied without restarting the application. 
_Note: All changes would be applied the next time you evaluate the changed code_
- [x] Change existing function code and event handlers
- [ ] Introduce new functions

**Comment by KristinaKoeva** [comment]
The feature is still in beta version so it is hidden behind a flag. To enable it execute the following command in your project directory
```
tns livesync ios --watch --live-edit
```

**Comment by NathanaelA** [comment]
@KristinaKoeva - I assume this is still currently iOS only; has the research been done for Android since parts of the diff code was borrowed from the v8 engine.

**Comment by Natalia-Hristova** [comment]
Closing in favor of NativeScript/NativeScript#6398.
