### ISSUE TITLE
xCode project needs to be updated

### ISSUE THREAD

**Issue by hshristov** [NativeScript/ios-runtime#65]
CLI generates xcode project that targets iOS 7.0. The project should be updated to latest (at the moment 8.2). And more important is to add Launch Screen File in the default template otherwise applications that run on iPhone 6 Plus are zoomed.

**Comment by fealebenpae** [comment]
I agree about the new Launch Screen size for 6+ devices, but do we need to change the deployment target? The deployment target version in the CLI template Xcode project is 7.0, because that's the minimum iOS version we support.

**Comment by PanayotCankov** [comment]
The deployment target will be left 7.0. The screen size has been addressed.
