### ISSUE TITLE
error TS2304: Cannot find name 'UIBarStyle'

### ISSUE THREAD

**Issue by KingAndroid** [NativeScript/ios-runtime#659]
export function loaded(args) {
    var page = args.object;
    page.bindingContext = userViewModel;

    if (page.ios) {
        var navigationBar = frameModule.topmost().ios.controller.navigationBar;
        navigationBar.barStyle = UIBarStyle.UIBarStyleBlack;
    }
}

---------------------------------------------------------------------------------------
Executing before-prepare hook from ~/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.0.3
app/views/login/login.ts(26,34): error TS2304: Cannot find name 'UIBarStyle'.

**Comment by KingAndroid** [comment]
Hi, I am working on ns-ts project, but I met below issues.
Compiler didn't find all UI~ and NS~ classes in typescript.
What is wrong?
Thanks for your supporting.

**Comment by jasssonpet** [comment]
The `UIBarStyle` enum is defined in the [UIKit.d.ts](https://github.com/NativeScript/NativeScript/blob/af3fcfb0abb576df8d9b8f243216804ecf9a7647/tns-core-modules/ios/objc-i386/objc!UIKit.d.ts#L2666-L2675) file, make sure that the TypeScript compiler has it visible.

**Comment by KingAndroid** [comment]
hi @jasssonpet 
thanks for your reply.
how can i check ts compiler has UIKit.d.ts visble?

**Comment by jasssonpet** [comment]
This will depend on the version of TypeScript you are using but you can look at the docs for general guidelines: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by ahalls** [comment]
@jasssonpet   I understand that we need to setup some search paths for the TSC compiler.   We are using version 2.0.3  of tsc and can't figure out what to do.

**Comment by jasssonpet** [comment]
Here is an example workflow:

```shell
tns create TestApp --template typescript
TNS_TYPESCRIPT_DECLARATIONS_PATH="$(pwd)/typings" tns build ios
```

Open your `tsconfig.json` file and add:
```json
"include": [
    "typings-i386/*",
    "Interop.d.ts"
]
```

where Interop.d.ts is downloaded from https://github.com/NativeScript/ios-runtime/blob/v2.3.0/src/ts/Interop.d.ts

**Comment by ahalls** [comment]
@jasssonpet  I understand all but the last step ...  "where `Interop.d.ts` is downloaded ...." 

1. Where do I download the file `Interop.d.ts` too? 
2. And the exact syntax of the compile command line

**Comment by ahalls** [comment]
I found my solution with this [stackoverflow](http://stackoverflow.com/a/37524018/690293) answer. 

`npm i tns-platform-declarations --save-dev`

Then add the following entries to the `references.d.ts` file.

```
/// <reference path="../node_modules/tns-platform-declarations/ios.d.ts" />
/// <reference path="../node_modules/tns-platform-declarations/android.d.ts" />
```

How ever there is still a bug.

**Comment by flipperlite** [comment]
Update for NativeScript 7.0 which uses @nativescript/core instead of tns-platform-declarations (NS 6 and before). I used this code because in iOS 15, the backgroundColor of the ActionBar can't be set in XML.

references.d.ts
```
/// <reference path="./node_modules/@nativescript/types/index.d.ts" />
```

tsconfig.json
```
{
    "compilerOptions": {
        "module": "esnext",
        "target": "es2017",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "skipLibCheck": true,
        "lib": [
            "es6",
            "dom",
            "es2017"
        ],
        "baseUrl": ".",
        "paths": {
            "~/*": [
                "app/*"
            ],
            "*": [
                "./node_modules/@nativescript/*",
                "./node_modules/*"
            ]
        },
        "moduleResolution": "node",
        "removeComments": false
    },
    "exclude": [
        "node_modules",
        "platforms"
    ]
}
```

Code example working:
```
import { isIOS,Device, Frame, Color } from "@nativescript/core";

if (isIOS) {
    // https://github.com/NativeScript/NativeScript/issues/2970
    // https://github.com/NativeScript/ios-runtime/issues/659
    // https://developer.apple.com/forums/thread/682420
    const osVersion: number = parseInt(Device.osVersion.split('.')[0]);
    if (osVersion >= 15) {
        let navigationBar = <UINavigationBar> Frame.topmost().ios.controller.navigationBar;
        navigationBar.backgroundColor = new Color('#ff0000').ios as UIColor;
    }
}
```
Code example broken in iOS 15:
```
<Page id="page" xmlns="http://schemas.nativescript.org/tns.xsd">
    <ActionBar backgroundColor="#ff0000">
        <!-- 
        Use the NavigationButton as a side-drawer button in Android
        because ActionItems are shown on the right side of the ActionBar
        -->
        <NavigationButton ios:visibility="collapsed" icon="res://menu" tap="onDrawerButtonTap"></NavigationButton>
        <!-- 
        Use the ActionItem for IOS with position set to left. Using the
        NavigationButton as a side-drawer button in iOS is not possible,
        because its function is to always navigate back in the application.
        -->
        <ActionItem icon="res://menu" android:visibility="collapsed" tap="onDrawerButtonTap" ios.position="left">
        </ActionItem>
        <Label text="My Page Header"></Label>
    </ActionBar>
</Page>
```
