### ISSUE TITLE
CMTime

### ISSUE THREAD

**Issue by bnussey** [NativeScript/ios-runtime#664]
I am having some issues with getting CMTime to work on NativeScript (https://developer.apple.com/reference/coremedia/1669288-cmtime)

It is necessary for when trying to do a seekToTime action on an AVPlayer.

For example:

```
let time = CMTimeMakeWithSeconds(4, 600);
console.log("time " + time);
this._player.seekToTime(time);
```
This correctly results in a CMTime looking variable being logged to the console, but the seekToTime just puts the video back to the very start, as opposed to 4 seconds.

Any ideas whats going on here?

Thanks

**Comment by ivanbuhov** [comment]
@bnussey Based on my Google research, this seems to be a common problem even in native iOS applications. Check if [this solution](http://stackoverflow.com/a/19011874/3968054) is working for you and share the result.

**Comment by bnussey** [comment]
Hey @ivanbuhov thanks for the reply. I saw the same SO link, tried it and it doesn't actually allow that many arguments to be passed in. Do we know for sure this works with NativeScript?

**Comment by bnussey** [comment]
Ah just found the method `seekToTimeToleranceBeforeToleranceAfter` .. looks like it works, nice one!
