### ISSUE TITLE
Command xcodebuild failed with exit code 65

### ISSUE THREAD

**Issue by agrawal-mohit** [NativeScript/ios-runtime#676]
OSX Yosemite 10.10.5 (14F27)
XCode Version 7.0 (7A220)
ios 9.3.5
tns 2.3.0

`$ tns livesync --device 7a3c131309432ebae1a483f134ec8a4f8cdeecf4 --watch`

> Executing before-prepare hook from /Users/mohit/work/Mobile/native/finly-ng/hooks/before-prepare/nativescript-dev-typescript.js
> Found peer TypeScript 2.0.3
> Project successfully prepared (ios)
> Executing before-livesync hook from /Users/mohit/work/Mobile/native/finly-ng/hooks/before-livesync/nativescript-angular-sync.js
> The application with id "org.nativescript.finlyng" is not installed on device with identifier 7a3c131309432ebae1a483f134ec8a4f8cdeecf4.
> Build settings from command line:
>     ARCHS = arm64
>     CONFIGURATION_BUILD_DIR = /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/build/device
>     SDKROOT = iphoneos9.0
>     SHARED_PRECOMPS_DIR = /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/build/sharedpch
>     VALID_ARCHS = arm64
> 
> === BUILD TARGET finlyng OF PROJECT finlyng WITH CONFIGURATION Debug ===
> 
> Check dependencies
> 
> Write auxiliary files
> write-file /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/build/finlyng.build/Debug-iphoneos/finlyng.build/finlyng-own-target-headers.hmap
> write-file /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/build/finlyng.build/Debug-iphoneos/finlyng.build/finlyng-project-headers.hmap
> write-file /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/build/finlyng.build/Debug-iphoneos/finlyng.build/Script-CD62955B1BB2651D00AE3A93.sh
> chmod 0755 /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/build/finlyng.build/Debug-iphoneos/finlyng.build/Script-CD62955B1BB2651D00AE3A93.sh
> write-file /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/build/finlyng.build/Debug-iphoneos/finlyng.build/Script-C97FD7AC1ADE5369004DB2A4.sh
> chmod 0755 /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/build/finlyng.build/Debug-iphoneos/finlyng.build/Script-C97FD7AC1ADE5369004DB2A4.sh
> write-file /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/build/finlyng.build/Debug-iphoneos/finlyng.build/finlyng.hmap
> write-file /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/build/finlyng.build/Debug-iphoneos/finlyng.build/Script-CD3EAD351B05FF060042DBFC.sh
> chmod 0755 /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/build/finlyng.build/Debug-iphoneos/finlyng.build/Script-CD3EAD351B05FF060042DBFC.sh
> /bin/mkdir -p /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/build/finlyng.build/Debug-iphoneos/finlyng.build/Objects-normal/arm64
> write-file /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/build/finlyng.build/Debug-iphoneos/finlyng.build/Objects-normal/arm64/finlyng.LinkFileList
> write-file /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/build/finlyng.build/Debug-iphoneos/finlyng.build/finlyng-all-non-framework-target-headers.hmap
> /bin/mkdir -p /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/build/sharedpch/finlyng-Prefix-exvpmgxsouxwvbeytpnprdfjhhjq
> write-file /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/build/sharedpch/finlyng-Prefix-exvpmgxsouxwvbeytpnprdfjhhjq/finlyng-Prefix.pch.pch.hash-criteria
> write-file /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/build/finlyng.build/Debug-iphoneos/finlyng.build/finlyng-all-target-headers.hmap
> write-file /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/build/finlyng.build/Debug-iphoneos/finlyng.build/finlyng-generated-files.hmap
> 
> Create product structure
> /bin/mkdir -p /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/build/device/finlyng.app
> 
> PhaseScriptExecution NativeScript\ PreBuild build/finlyng.build/Debug-iphoneos/finlyng.build/Script-C97FD7AC1ADE5369004DB2A4.sh
>     cd /Users/mohit/work/Mobile/native/finly-ng/platforms/ios
>     /bin/sh -c /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/build/finlyng.build/Debug-iphoneos/finlyng.build/Script-C97FD7AC1ADE5369004DB2A4.sh
> ~/work/Mobile/native/finly-ng/platforms/ios/internal/metadata-generator/bin ~/work/Mobile/native/finly-ng/platforms/ios
> Generating metadata for arm64
> Error: Unable to generate metadata for arm64.
> dyld: Library not loaded: @rpath/libc++.1.dylib
>   Referenced from: /Users/mohit/work/Mobile/native/finly-ng/platforms/ios/internal/metadata-generator/bin/./objc-metadata-generator
>   Reason: image not found
> 
> Command /bin/sh failed with exit code 1
> 
> *\* BUILD FAILED **
> 
> The following build commands failed:
>   PhaseScriptExecution NativeScript\ PreBuild build/finlyng.build/Debug-iphoneos/finlyng.build/Script-C97FD7AC1ADE5369004DB2A4.sh
> (1 failure)
> Command xcodebuild failed with exit code 65

**Comment by ivanbuhov** [comment]
@agrawal-mohit The metadata generation step fails because the dynamic linker can't find `libc++.1.dylib` library on your machine. The metadata generator expects `libc++.1.dylib` to be placed in one of the system default library search paths. Since `/usr/lib` is certainly one of these paths, I suggest moving `libc++.1.dylib` there. 
If for some reason, you want your `libc++.1.dylib` placed somewhere else, you can add its path to the `DYLD_LIBRARY_PATH` environment variable and the dynamic linker should find it as well.
