### ISSUE TITLE
Double click on file in ios debug inspector throws an error.

### ISSUE THREAD

**Issue by SvetoslavTsenov** [NativeScript/ios-runtime#685]
1. run tns debug ios
2. Double click on some file from resources 

TypeError:​ InspectorFrontendHost.openInNewTab is not a function. (In 'InspectorFrontendHost.openInNewTab(this._resource.url)​', 'InspectorFrontendHost.openInNewTab' is undefined)​ (at ResourceTreeElement.js:​99:​43)​
    ondblclick @ ResourceTreeElement.js:​99:​43
    treeElementDoubleClicked @ TreeElement.js:​314:​48

**Comment by SvetoslavTsenov** [comment]
Removing resource tab and adding it again the inspector crashes with the same error.

**Comment by dtopuzov** [comment]
Can't reproduce with 3.1.*
