### ISSUE TITLE
wkwebview seems to act as uiwebview

### ISSUE THREAD

**Issue by Alphapage** [NativeScript/ios-runtime#688]
Hello,

I'm trying to load a simple html using wkwebview, but it tells me loadHTMLString is undefined or not a function.
It seems to be able to use loadRequest which is implemented in uiwebview and not in wkwebview.

Thanks in advance for your help.

**Comment by KristinaKoeva** [comment]
Hey,

The method that you are trying to call has the following signature
``` - (WKNavigation *)loadHTMLString:(NSString *)string baseURL:(NSURL *)baseURL; ``` 
You can find more information [here]
(https://developer.apple.com/reference/webkit/wkwebview/1415004-loadhtmlstring?language=objc). So to call it in {N} you should execute 
``` wkwebview.loadHTMLStringBaseURL(htmlString, baseUrl); ```

**Comment by Alphapage** [comment]
+1
Thank you. I don't use baseUrl, but that is working now.
