### ISSUE TITLE
Set CFBundleSupportedPlatforms to iPhoneOS on Telerik Framework

### ISSUE THREAD

**Issue by leocaseiro** [NativeScript/ios-runtime#689]
Hi,

@domgaud and I have to use XCode to release our Enterprise App.

To be able to release the app, we run from the command line, so we can create the bundle files:
`tns build ios --release --bundle --for-device`

Than we open the `App.xcworkspace` in XCode to Export an Archive Enterprise App.

We found on that in Telerik Framework the option `CFBundleSupportedPlatforms` was hardcoded to `iPhoneSimulator` in the `info.plist`.

We set to `iPhoneOS` which resolved the follow error as you can see on the screenshot below:
> Info.plist of "App/Frameworks/TelerikAppFeedback.framework" specifies a simulator platform for the CFBundleSupportedPlataforms key

![screen shot 2016-11-15 at 10 28 45 am](https://cloud.githubusercontent.com/assets/940070/20287175/1337b976-ab1f-11e6-882d-50c498c357bf.png)

This error appear in both `./lib/iOS/TelerikAppFeedback.framework/Info.plist` and `./lib/iOS/TelerikUI.framework/Info.plist`

**XCode:** Version 8.1 (8B62)
**nativescript:** 2.3.0
**tns-core-modules:** 2.3.0
**tns-ios:** 2.3.0

## Temporary Solution
After replacing from `iPhoneSimulator` to `iPhoneOS` in both `./lib/iOS/TelerikAppFeedback.framework/Info.plist` and `./lib/iOS/TelerikUI.framework/Info.plist` and the app has been successfully released.

**Comment by jasssonpet** [comment]
Moved to: https://github.com/telerik/nativescript-ui-samples/issues/123

**Comment by leocaseiro** [comment]
Hi @jasssonpet, thanks for checking out this issue.

I'm, quite confused why you're moving something that should be in the core for iOS Runtime to a  repo that has UI Samples and is not related to the core?

Thanks

**Comment by jasssonpet** [comment]
Hey, @leocaseiro,

The iOS runtime is distributed as a single framework (located in `platforms/ios/internal/NativeScript.framework`) which has the correct value of `CFBundleSupportedPlatforms`. Any other framework is added from a plugin and is outside the scope of this repo, in this case the nativescript-ui plugin.

**Comment by leocaseiro** [comment]
Hi @jasssonpet,
Thank you for your reply.

I didn't know that the Telerik Framework was part of the `nativescript-ui`. It makes sense.
