### ISSUE TITLE
NSLayoutConstraint with VisualFormat not working

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/ios-runtime#694]
_From @alexrainman on November 9, 2016 15:20_

Trying to add a UIPageControl programmatically with this code:

```
var viewsDictionary = NSDictionary.dictionaryWithObjectForKey(this._pageControl, "pageControl");

this._ios.addConstraints(NSLayoutConstraint.constraintsWithVisualFormatOptionsMetricsViews("H:|[pageControl]|", NSLayoutFormatOptions.NSLayoutFormatAlignAllCenterX, <any>[], viewsDictionary));

this._ios.addConstraints(NSLayoutConstraint.constraintsWithVisualFormatOptionsMetricsViews("V:[pageControl]|", 0, <any>[], viewsDictionary));
```

But the UIPageControl doesn't goes to bottom as expected, instead is at the top half hidden behind navigation bar.

Any ideas?

_Copied from original issue: NativeScript/NativeScript#3052_

**Comment by NickIliev** [comment]
_From @alexrainman on November 9, 2016 15:37_

I need this or any other way to apply constraints to a view so i can keep it at the bottom but resizable when screen rotates.

**Comment by NickIliev** [comment]
Hey @alexrainman

Can you please share a bit more information about this case!? Or even better - a sample project to reproduce this case.
For example from the snippet above , we are not sure what *_*this._pageControl**_ is and what **_this_** means as well.

**Comment by alexrainman** [comment]
@NickIliev i am trying to add UIPageControl to the bottom of UIView that acts as container for UIPageViewController. I did the same thing in the Xamarin.Forms version of my plugin and it works like a charm. I also verified that the UIView container has the right size but the UIPageControl doesn't stick to the bottom. 

Please, take a look at iOS version of the plugin https://github.com/alexrainman/nativescript-carousel-view/blob/master/carousel-view.ios.ts

I am trying to add the UIPageControll onLoaded() after line 58.

I don't have issues in Android dough, so solving this will allow me to update the plugin including page indicators in both platforms vertically and horizontally.

**Comment by tzraikov** [comment]
@alexrainman I don't see any call to the addConstraints method in your code. Please, could you send us a sample project that demonstrates the issue. In the demo project from your git repo everything looks normal?

**Comment by alexrainman** [comment]
@tzraikov i will create a different repo implementing this.

**Comment by tzraikov** [comment]
Thanks!

**Comment by alexrainman** [comment]
@tzraikov take a look at this repo:
 
https://github.com/alexrainman/nativescript-carousel-view-dev

Notice that page indicators are working in Android already but i cannot make it work in iOS because of this issue.

Thanks

**Comment by alexrainman** [comment]
@tzraikov please review this file https://github.com/alexrainman/nativescript-carousel-view-dev/blob/master/app/carousel-view/carousel-view.ios.ts line 63 to 100.

**Comment by alexrainman** [comment]
Look where UIPageControl shows no matter how i add the constraints

<img width="374" alt="screen shot 2016-12-02 at 8 05 34 am" src="https://cloud.githubusercontent.com/assets/3793554/20836877/f81bdca8-b866-11e6-9d93-3fb4b3540cc5.png">

**Comment by tzraikov** [comment]
@alexrainman I found the issue. You should not set the `translatesAutoresizingMaskIntoConstraints` this way:
`this._pageControl.translatesAutoresizingMaskIntoConstraints = () => false;`
Use this code instead:
`(<any>this._pageControl).translatesAutoresizingMaskIntoConstraints = false;`

This code centers the view horizontally:
`this._ios.addConstraints(NSLayoutConstraint.constraintsWithVisualFormatOptionsMetricsViews("H:|-[pageControl]-|", NSLayoutFormatOptions.NSLayoutFormatAlignAllCenterY, null, viewsDictionary));`

Use this one to center it at the top of the page:
`this._ios.addConstraints(NSLayoutConstraint.constraintsWithVisualFormatOptionsMetricsViews("V:|-[pageControl]", 0, null, viewsDictionary));`

This one will center the view at the bottom of the page:
`this._ios.addConstraints(NSLayoutConstraint.constraintsWithVisualFormatOptionsMetricsViews("V:[pageControl]-|", 0, null, viewsDictionary));`

**Comment by alexrainman** [comment]
It works. Just released a new version of the plugin with page indicators included. Thanks

**Comment by alexrainman** [comment]
Basically it was one line of code issue. Thanks.
