### ISSUE TITLE
Not working in ios

### ISSUE THREAD

**Issue by wmj0cn** [NativeScript/ios-runtime#703]
var WebWorker = require('nativescript-webworkers');
  var myWorker = new WebWorker('~/workder/test.worker.js');
  myWorker.onmessage = function(m) { alert("Webworker said:", m); };

 in workder/test.worker.js:
   onmessage = function(m) {
        postMessage('bye');
  };
  onready = function() {
    postMessage("Hi");
  };

 then i run it nothing happened, what i expect is that a alert will pop up.

**Comment by KristinaKoeva** [comment]
Hey,

You can post all nativescript-webworkers related issues in its [repository](https://github.com/nathanaela/nativescript-webworkers). 
Also you can take a look at this [blog post](https://www.nativescript.org/blog/using-workers-in-nativescript-to-execute-javascript-on-background-threads) that explains how to use the WebWorkers that are officially supported by {N}.
