### ISSUE TITLE
Metadata found but symbol not available at runtime

### ISSUE THREAD

**Issue by bdauria** [NativeScript/ios-runtime#704]
I'm trying to wrap a native C++ library into a iOS Framework, but I'm getting the following error while calling a method out of the library:

`JS ERROR ReferenceError: Metadata for "SuperpoweredExport.Superpowered" found but symbol not available at runtime.`

The related XCode project code is available here: https://github.com/bdauria/SuperpoweredExport
I've basically dropped the resulting .Framework  into the platforms/ios directory of a NativeScript plugin, which I'm in turn importing in my final application. 

I've probably missed some configuration while building the XCode project. Also, you might see some weird stuff in there as my knowledge in this area is really limited.

Thanks in advance for your help.

**Comment by jasssonpet** [comment]
Hello,

I've cloned the repo, downloaded the C++ library, built the framework and created a NativeScript plugin ([Superpowered-plugin.zip](https://github.com/NativeScript/ios-runtime/files/676865/Superpowered-plugin.zip)
) as you described but I can't seem to reproduce the issue. After doing this I get:

```javascript
console.log(global.Superpowered); // function Superpowered() { [native code] }
```

One thing I can think of is to make sure that the plugin you are using is the universal one with all the required architectures.

If you want, you can upload the plugin so we can investigate what's going on with it.

**Comment by bdauria** [comment]
I've created the repository with the plugin: https://github.com/bdauria/tns-superpowered

**Comment by jasssonpet** [comment]
You can check what are architectures the binary is compiled for with the following command:
```shell
$ lipo -info platforms/ios/SuperpoweredExport.framework/SuperpoweredExport
Non-fat file: SuperpoweredExport is architecture: x86_64
```

So this means that the symbol will be there if you are using a 64 bit simulator, but not on device or a 32-bit simulator.

Make sure that you are building the framework project in Release config and use the output in `Release-Universal` that the build script is producing in the project's Xcode derived data folder.

**Comment by bdauria** [comment]
I'm a bit confused, the output built in Release-Universal seems to target x86_64 as well. What's the exact way to build against a 32 bit architecture?

**Comment by ivanbuhov** [comment]
@bdauria Xcode comes with i386 and x86_64 simulators. Since your library has x86_64, armv7 and arm64 slices, make sure you are not running the app on i386. If this is not the case, you can upload the plugin so I can further investigate the issue.

**Comment by NathanWalker** [comment]
@bdauria if you are still having an issue, I could help assist - just handled a similar scenario with another custom .framework build.

**Comment by ivanbuhov** [comment]
I am closing the issue because of inactivity. If someone experience the same problem in future, feel free to reopen the issue.

**Comment by SandipFichadiya** [comment]
I am creating one native ios framework, and trying to integrate it within my nativescript project. I am getting following error:

```
** ARCHIVE SUCCEEDED **

2017-05-06 12:12:49.233 xcodebuild[6077:34656] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/_s/6l5z2bd97lv0wl9ztv1dmfph0000gn/T/demoProject_2017-05-06_12-12-49.231.xcdistributionlogs'.
1.2.840.113635.100.1.61
Exported demoProject.xcarchive to: /Users/myUser/Desktop/demoProject/platforms/ios/build/device
** EXPORT SUCCEEDED **

Project successfully built.
Installing...
Successfully installed on device with identifier 'a12aa12a121212a12a121a1a1aa12aa1a1a12a12'.
Executing before-livesync hook from /Users/myUser/Desktop/demoProject/hooks/before-livesync/nativescript-angular-sync.js
Transferring project files...
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Successfully transferred all files.
Refreshing application...
Successfully synced application org.nativescript.demoProject on device a12aa12a121212a12a121a1a1aa12aa1a1a12a12.


Executing before-watch hook from /Users/myUser/Desktop/demoProject/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 2.1.6
CONSOLE LOG file:///app/tns_modules/@angular/core/./bundles/core.umd.js:3032:20: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
NativeScript could not load bundle file:///var/containers/Bundle/Application/770AE54E-17D8-466F-AB0C-E416DF2D8E1B/demoProject.app/Frameworks/myframework.framework
CONSOLE ERROR file:///app/tns_modules/@angular/core/./bundles/core.umd.js:1091:24: ERROR Error: Uncaught (in promise): ReferenceError: Metadata for “myframework.myclassname” found but symbol not available at runtime.
MyClass@file:///app/tns_modules/nativescript-myplugindemo/plugindemo.js:8:31
createView@file:///app/tns_modules/nativescript-angular/view-util.js:122:33
createElement@file:///app/tns_modules/nativescript-angular/renderer.js:103:40
createElement@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:13085:62
createElement@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:9321:40
createViewNodes@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:11935:57
callViewAction@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:12347:28
execComponentViewsAction@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:12286:27
createViewNodes@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:12004:29
createRootView@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:11882:20
callWithDebugContext@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:13013:47
create@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:9818:60
createComponent@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:10018:68
activateOnGoForward@file:///app/tns_modules/nativescript-angular/router/page-router-outlet.js:152:70
activateWith@file:///app/tns_modules/nativescript-angular/router/page-router-outlet.js:138:37
placeComponentIntoOutlet@file:///app/tns_modules/@angular/router/./bundles/router.umd.js:4515:28
activateRoutes@file:///app/tns_modules/@angular/router/./bundles/router.umd.js:4496:50
file:///app/tns_modules/@angular/router/./bundles/router.umd.js:4432:72
forEach@[native code]
activateChildRoutes@file:///app/tns_modules/@angular/router/./bundles/router.umd.js:4432:36
activate@file:///app/tns_modules/@angular/router/./bundles/router.umd.js:4406:33
file:///app/tns_modules/@angular/router/./bundles/router.umd.js:4023:30
file:///app/tns_modules/rxjs/Observable.js:107:25
__tryOrSetError@file:///app/tns_modules/rxjs/Subscriber.js:243:20
```

**Comment by ivanbuhov** [comment]
@SandipFichadiya make sure the framework binary have a slice for the architecture you are deploying on. What is the output of `lipo -info {PluginPath}/platforms/ios/{FrameworkName}.framework/{FrameworkName}`?
