### ISSUE TITLE
Including TNSDebugging.h results in compiling errors

### ISSUE THREAD

**Issue by jeduden** [NativeScript/ios-runtime#713]
trying to integrate into an existing Objective-C/C++ app nativescript. When including TNSDebugging .h compiling fails with two errors:

1. Use of undeclared identifier 'typeof'; did you mean 'typeid' ?
    https://github.com/NativeScript/ios-runtime/blob/master/src/debugging/TNSDebugging.h#L33

2. Subscript of pointer to incomplete type 'void' ?
    https://github.com/NativeScript/ios-runtime/blob/master/src/debugging/TNSDebugging.h#L90

While the fixes seem to be straight forward, i am wondering why there are not occurring in the current builds ? 

I am using the following code to include TNSDebugging.h 

> #import <NativeScript.h>
> #import <TNSExceptionHandler.h>
> #include <TNSDebugging.h>

**Comment by jasssonpet** [comment]
This could be related to the C/C++ compilation flags or C/C++ dialect used. Here is an example: 
```shell
/Applications/Xcode_8.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang \
    -x objective-c \
    -arch x86_64 \
    -std=gnu99 \
    -fobjc-arc \
    -DDEBUG=1 \
    -isysroot /Applications/Xcode_8.2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk \
    -I$SRCROOT/internal \
    -F$SRCROOT/internal \
    -c $SRCROOT/TestApp/main.m \
    -o main.o
```

**Comment by jeduden** [comment]
Yes, you are right. The header compiles when Objective-C/C is used. i.e. a *.m file. As soon as Objective/C++ (*.mm) is used it starts failing. I made a PR with a potential fix.

**Comment by jeduden** [comment]
PR merged - thanks !
