### ISSUE TITLE
How to call the "useCredential" method of the sender of the challenge

### ISSUE THREAD

**Issue by mourice** [NativeScript/ios-runtime#720]
I am having http auth for one of the url inside my nativescript application.

 I am successfully getting the "**ReceiveAuthenticationChallenge**" callback by extending the NSURLConnection like below

    var MyNSURLConnectionDelegate = NSURLConnection.extend({
    				connectionDidReceiveAuthenticationChallenge: function (connection, challenge) {
    
    					if (challenge.previousFailureCount == 0) {
    						
                         }
                      }
                  });

but I am stuck at how to call the "useCredential" method of the sender of the challenge from native script. which we write in objective c as shown below

    [[challenge sender] useCredential:[NSURLCredential credentialWithUser:pusername password:ppassword  persistence:NSURLCredentialPersistencePermanent] forAuthenticationChallenge:challenge];

**Comment by ivanbuhov** [comment]
Hi @mourice 
This Objective-C line of code:
```
[[challenge sender] useCredential:[NSURLCredential credentialWithUser:pusername password:ppassword  persistence:NSURLCredentialPersistencePermanent] forAuthenticationChallenge:challenge];
```
translated to NativeScript would look like this:
```
challenge.sender.useCredentialForAuthenticationChallenge(NSURLCredential.credentialWithUserPasswordPersistence(pusername, ppassword, NSURLCredentialPersistencePermanent), challenge)
```

**Comment by mourice** [comment]
Already tried getting the below error

JS ERROR TypeError: challenge.sender.useCredentialForAuthenticationChallenge is not a function. (In 'challenge.sender.useCredentialForAuthenticationChallenge', 'challenge.sender.useCredentialForAuthenticationChallenge' is undefined

**Comment by ivanbuhov** [comment]
@mourice 
This happens because the `sender` property is [declared in the iOS headers](https://developer.apple.com/reference/foundation/nsurlauthenticationchallenge/1407533-sender?language=objc) to be of type `id<NSURLAuthenticationChallengeSender>`, so the runtime does not know about the existence of the `useCredential:forAuthenticationChallenge:` method. 

In such cases your best option is to use `performSelector:`/`performSelector:withObject:` but in your particular case the method has more than one argument (and there is no `performSelector:withObject:withObject:` method) so you must fallback to using the `NSInvocation` API which is more verbose. You can find an `NSInvocation` example in [this SO answer](http://stackoverflow.com/a/15761474/3968054).

**Comment by mourice** [comment]
Thanks for the way to achieve this. but I am new to Nativescript, It would be really helpful if you provide some Nativescript code.

**Comment by ivanbuhov** [comment]
@mourice It was my mistake, it seems that `performSelector:withObject:withObject:` method exists. Try with this in NativeScript:
```
challenge.sender.performSelectorWithObjectWithObject("useCredential:forAuthenticationChallenge:", credential, challenge);
```

**Comment by mourice** [comment]
@ivanbuhov 
Thanks for your help. After this change I am getting the "Service exited due to Segmentation fault 11" error and application is getting crashed

**Comment by ivanbuhov** [comment]
@mourice I can't think of something that can cause the crash but it will be helpful if you share the stack trace?

**Comment by mourice** [comment]
I am getting the crash on emulator but on actual device after calling the performSelector method. connection delegate for "connectionDidReceiveResponse" is not getting called. any idea?

**Comment by mourice** [comment]
application works in debug mode but crashing -n released mode for perform selector any idea?

**Comment by ivanbuhov** [comment]
@mourice Actually, in your particular case, the recommended way to call a method coming from `NSURLAuthenticationChallengeSender` protocol is to to use the protocol prototype chain:
```
NSURLAuthenticationChallengeSender.prototype.useCredentialForAuthenticationChallenge.call(challenge.sender, credential, challenge);
```
Let me know if this doesn't work for you. 

P.S.: You may find this [discussion](https://github.com/NativeScript/ios-runtime/issues/466) useful.

**Comment by mourice** [comment]
@ivanbuhov
Sometimes works on iPhone 5s. but getting continuous crash on iPhone6s.

**Comment by mourice** [comment]
@ivanbuhov

Thanks for your help on this issue really appreciate. 

I am setting the webview and connection delegate inside onInit function.
After I added the delay (setTimeout) in setting the webview and connection delegate no more crash and application works fine. 

Any idea whey the setTimeout is require.
