### ISSUE TITLE
sample code to implement NativeScript Class in TypeScript with self delegate

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/ios-runtime#725]
_From @xmlking on February 7, 2017 18:3_

I am new to NativeScript,  looking for sample code to implement NativeScript Class in TypeScript with self delegate?

here are more details : 
http://stackoverflow.com/questions/41991160/how-to-implement-nativescript-class-in-typescript-with-self-delegate

want to simplify my code my eliminating additional delegate class by directly implementing delegate methods in the main class that supposed to have a delegate. 
Thanks 

_Copied from original issue: NativeScript/NativeScript#3603_

**Comment by ivanbuhov** [comment]
@xmlking As the [doc](https://docs.nativescript.org/runtimes/ios/how-to/ObjC-Subclassing.html#typescript-support) says:
 > There should be no TypeScript constructor, because it will not be executed. Instead override one of the init methods.

You can override a base `init` method and place your delegate setting logic there:

```
public init() {
    var self = this.super.init();
    if (self) {
        self.delegate = self;
    }
    return self;
}
```

**Comment by xmlking** [comment]
@ivanbuhov thanks for you input.
my basic issue is I cannot inject Angular Service that extends `NSObject`
with following case I am getting runtime error, either with JS constructor() or init() methods :

```
file:///app/tns_modules/@angular/compiler/bundles/compiler.umd.js:18632:28: 
JS ERROR Error: Invalid provider for the NgModule 'MicrosoftBandModule' - only instances of 
Provider and Type are allowed, got: [?MicrosoftBandService?]
```

```ts
import {Injectable} from '@angular/core';
@Injectable()
export class MicrosoftBandService  extends NSObject implements ConnectionDelegate {
 public static ObjCProtocols = [ConnectionDelegate];
...
}
```
without `extends NSObject`  the angular service will be registered properly.  but  native delegates has to always extend NSObject. 
Need to research how to register angular service provider that extend    `NSObject`

**Comment by xmlking** [comment]
I tried following method, but this time I am getting `undefined` error :(

```
CONSOLE ERROR file:///app/tns_modules/tns-core-modules/trace/trace.js:160:30: ns-renderer: 
Error in :0:0 caused by: undefined is not an object (evaluating 'this.msband.connection$.subscribe')
```

```ts
export const MicrosoftBandToken = new OpaqueToken('MicrosoftBandToken');

@Injectable()
export class MicrosoftBandService  extends NSObject implements ConnectionDelegate {
    public static ObjCProtocols = [ConnectionDelegate];

    static new(): MicrosoftBandService {
        let self = <MicrosoftBandService>super.new()
        self.mbk = MicrosoftBand.alloc().init();
        if (self) {
            self.mbk.connectDelegate = self;
        }
        return self;
    }
...
}
```

```ts
import { MicrosoftBandToken, MicrosoftBandService } from './src/app/services/microsoftband.service.ios';
export class MicrosoftBandModule {

  static forRoot(): ModuleWithProviders {
    return {
      ngModule: MicrosoftBandModule,
      providers: [
        {provide: MicrosoftBandToken, useValue: MicrosoftBandService.new()},
      ]

    };
  }
}
```

```ts
import {MicrosoftBandToken, MicrosoftBandService} from '@xmlking/nativescript-ngx-microsoftband';

@Component({
    selector: 'app',
    templateUrl: "app.component.html"
})
export class AppComponent implements OnInit, OnDestroy {
    constructor(private zone: NgZone, @Inject(MicrosoftBandToken) private msband: MicrosoftBandService) {

    }

...
}

```

**Comment by ivanbuhov** [comment]
@xmlking It seems that an angular service can't derive from native object. Try not to register your `MicrosoftBandService` as angular service just to verify that the original problem - implementing NativeScript Class in TypeScript with self delegate is solved. Then you can create a separate class for your angular service.
