### ISSUE TITLE
LaunchScreen - NativeScript 2.5.0 - Still loading the default LaunchScreen even after replacing all the files and following the guidelines.

### ISSUE THREAD

**Issue by sudhanshu-15** [NativeScript/ios-runtime#726]
I followed the LaunchScreen guide provided here: https://docs.nativescript.org/publishing/creating-launch-screens-ios
I replaced all the files with the respective files of the correct dimensions, but still it is loading the default NativeScript launch screen. I also opened the LaunchScreen.storyboard and it shows me some graphics with a "?". Not sure if I am doing something wrong. Help would be really appreciated. Thanks.

![image](https://cloud.githubusercontent.com/assets/883233/22804063/6d687d36-eee5-11e6-898e-36c3196cf50e.png)

![image](https://cloud.githubusercontent.com/assets/883233/22804096/8cd0516c-eee5-11e6-94fb-6a437566a1c2.png)

![image](https://cloud.githubusercontent.com/assets/883233/22804112/9ee6f950-eee5-11e6-98fb-acc6b7c0944c.png)

![image](https://cloud.githubusercontent.com/assets/883233/22804382/d7e50e26-eee6-11e6-8f8a-4c590260e888.png)

**Comment by NickIliev** [comment]
Hi @sudhanshu-15 

No matter if you choose the manual approach or the WYSIWYG approach via XCode you should look out for two things that might result in your issue.

- make sure that you have the proper naming of your images corresponding to the corresponding [content.json](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/ios-runtime/issue_726/app/App_Resources/iOS/Assets.xcassets/LaunchImage.launchimage/Contents.json#L6) file. For each field in the **content.json** file there should be a corresponding file name with the extension. This might be the reason your XCode is showing non-existent file reference (the image with **?**). Using the WYSIWYG approach should generate the content.json for you but with the manual approach you should verify that you are using the correct naming of each file. Note taht there is a content.json for each asset folder (e.g. LaunchScreen.AspectFill, LaunchImage.Center, etc)

- after adding your new image resources it is **mandatory** to rebuild your app with reset **_platforms_** folder.
Delete **_platforms_** folder and rebuild
```
rm -rf platforms  // or manually delete
tns run ios

```

Test project with changed images can be found [here ](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/ios-runtime/issue_726)(added via XCode)

**Comment by sudhanshu-15** [comment]
@NickIliev Thank you so much for the response. The only thing I didn't do was to remove platforms. After following the suggestion of removing the platforms and adding them again, solved the problem. Thank you again. I will close the issue.
