### ISSUE TITLE
info from amazon

### ISSUE THREAD

**Issue by SumanSingh4** [NativeScript/ios-runtime#729]
I want to get info like order list/history from amazon.

is there any plugin for amazon??

or another way to retrieve info?

**Comment by ivanbuhov** [comment]
You can retrieve Amazon products data by using the [
Amazon Product Advertising API](https://affiliate-program.amazon.com/gp/advertising/api/detail/main.html). However, it seems Amazon have closed the API for mobile devices.
This is a quote from the [Product Advertising API License Agreement](https://affiliate-program.amazon.com/gp/advertising/api/detail/agreement.html):
> You will not, without our express prior written approval, use any Product Advertising Content on or in connection with any site or application designed or intended for use with a mobile phone or other handheld device ...

Here's a related article you may be interested in: [How Amazon killed Delicious Library for iPhone](http://www.zdnet.com/article/how-amazon-killed-delicious-library-for-iphone/)

**Comment by SumanSingh4** [comment]
Ok thnaxx. 

If you ever get any information regarding accessing info please inform me. I really really need it.
