### ISSUE TITLE
Feature Request: add global.ios = true

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/ios-runtime#733]
I would like to add some feature parity here.

I can currently easily do:  `if (global.android) { /* Do some android code */ } `

I would love to have a readonly `global.ios` set to a boolean `true` in the iOS runtime.  

As I currently do:
`if ( ! global.android) { /* iOS Code */ }`

However, it will break if windows runtime is ever released...   I don't like code that can break easily even though I suspect windows is still a ways out...

I have had many people ask me why I do `if (!global.android)` to detect iOS and why I don't just use `if (global.ios)` and I have to tell them because the iOS runtime doesn't have that support.  And you can probably guess the rest of the conversation about how incompetent they think you are...

Now, because I know how the runtimes work I am WELL aware the reason `global.android` works is because it is a side effect of the design of NativeScript.      But most people using the platform don't really understand the design and why 'global.android' works, so the iOS team looks, well....   

 I am willing to do a pull request for this if you are willing to accept it.   I personally think this would be a great simple new feature to add to the upcoming 3.0 release, and would make a lot of my plugins have  code that isn't as brittle.   :grinning:   

Thoughts, discussion?

**Comment by ivanbuhov** [comment]
@NathanaelA 
Does `if (global.NSObject)` check work for you?
If you find `global.ios` to be more convenient you can define a property:
```
Object.defineProperty(global, 'ios', {
    __proto__: null,
    value: (global.NSObject != undefined),
    configurable: false
});
```
If you find the check `global.NSObject != undefined` not being strong enough, you can combine it with more iOS specific APIs (e.g. `global.NSObject && global.NSString && global.UIDevice`). Alternatively, you can define the global variable in an module with `*.ios.js` extension and rely on the CLI to prepare it only on iOS. You can see a similar solution in tns-core-modules: [iOS check](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/platform/platform.ios.ts#L131), [Android check](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/platform/platform.android.ts#L152).

**Comment by PanayotCankov** [comment]
```
import { isAndroid, isIOS } from "platform";
if (isIOS) {
} else if (isAndroid) {
}
```

**Comment by NathanaelA** [comment]
@ivanbuhov - 
```
if (global.NSObject && global.NSString && typeof global.ios === "undefined") {
	global.ios = true;
	Object.freeze(global.ios);
}
```

Was added to my NS-Master-technology plugin well over a year ago.  ;-)     I use it (ns-master-technology) in most my apps.   I'm not as worried about my apps; that code is trivial to add to the app.js file so it is set at the start of the app.    

I was thinking in general this would be a good feature just so that it could be **used in plugins in general**.     I have developed over 30 plugins;  I find the missing (global.ios) an annoyance, it isn't a "major" issue; but it is just **annoying**.   I can work around it; but I don't see why I should always have to work around it, since it is such a trivial fix for the runtime engine and I can give you a pull request if you are willing to accept it...  ;-) 


@PanayotCankov -

I'm well aware of `platform`  ;-)    -   However bringing in `platform` has caused crashes at app startup in past versions of NativeScript.   I haven't tested it recently (so it still might be the case), but once burned, you tend to eliminate any code you can't control..  ;-)

 In addition using "global.android" requires NO parsing of any additional JS code because it doesn't have to require anything, making the plugin less dependent on things especially with webpack blowing up things frequently.   This also eliminates ~1000 lines of code that has to be parsed and loaded in if you don't have to require `platform` (and what it brings in with it -- although I do realize this code (platform) is brought in at some point by application and other calls; it is safer if people when using my plugins before application if I don't bring in anything out of sequence....

---

If this is change is not willing to be accepted/changed;  I can make my plugin generator add that code to any of my new plugins, so that I can use "global.ios" throughout the rest of the plugin codebase, but it seems like this is something better left to the runtime engine, which is why I was suggesting it.   ;-)

**Comment by ivanbuhov** [comment]
@NathanaelA 
Do you find `if (global.NSObject)` to be more annoying and less convenient than `if (global.ios)`?

**Comment by PanayotCankov** [comment]
@NathanaelA Ya ok, it is just that we suggested the runtimes to support some fields that can be used to check the runtime for ios vs android and debug vs release environments in the past but the result is what's now in "platforms". Obviously we have more arguments this time as well as support from the community so If it makes it to the runtimes this time, I'd be more than happy to deprecate the isAndroid/isIOS in the "platform".

**Comment by NathanaelA** [comment]
@ivanbuhov - The reason I don't just use NSObject/NSString is I can see someone creating an emulation class in NativeScript for Android and calling it NSObject, NSString, etc...  So that the functionality actually is more cross platform and so they can call something like `NSString.characterAtIndex(0,1)` and it would work on both platforms.    You know someone will do it...  ;-)   

I know this is a remote possibility; and so that is the reason I actually check TWO different objects; and more recently switched to checking NSString and UIDevice (so that way one of them is NOT prefixed with NS).         I believe this technique of checking at least two different unrelated objects is fairly safe; but it is  still not as safe as if the runtime had a built-in `.ios` property.  ;-)     

Like I said before I can easily detect it; and I can start including the:
```
if (global.UIDevice && global.NSString && typeof global.ios === "undefined") {
	global.ios = true;
	Object.freeze(global.ios);
}
```
in all my own plugins; but I figured I would see if we could just get `global.ios` dropped into the runtimes, rather than me working around it in all my plugins. 

Again this is more to eliminate an minor annoyance; not a major issue as I can easily work around it with the above code that I already use in a couple of my plugins.      I just would rather not have the annoyance.  And would be willing to submit a pull request if there is the possibility of it being accepted.  ;-)

**Comment by ivanbuhov** [comment]
@NathanaelA I agree that such checks for API availability (like `if (global.NSObject)`) are not 100% reliable because of the tiny possibility of someone mocking the API on the other platform. Keep in mind that this argument is valid if we introduce `global.ios`, too, because everyone can easily define `global.ios` on Android.

Currently, in case you don't want to [consume the `platform` module from the cross-platform modules](https://github.com/NativeScript/ios-runtime/issues/733#issuecomment-287692294), the only 100% reliable method of checking the platform is having platform-specific files in your app/plugin:
```
// os.android.js
module.exports = { android: true };
```

```
// os.ios.js
module.exports = { ios: true };
```

```
// in a random module
var os = require('./os');
if (os.ios) {
}
else if (os.android) {
}
```
I agree that in some cases introducing two additional files to be able to check the platform may be too much work for a simple task. 

A possible solution that has the strengths of both methods (the convenience of `if (global.NSObject)` and the reliability of using platform-specific modules) is to introduce read-only `global.__platform` property both in iOS and Android Runtimes (ping @Plamen5kov). The check will look like this:
```
if (global.__platform == "ios") { ... }
else if (global.__platform == "android") { ... }
```
or
```
if (global.__platform.ios) { ... }
else if (global.__platform.android) { ... }
```
The question here is whether the inconvenience of introducing two additional files (in the cases when you can't use the `platform` module) just to check the platform you are running on is a bigger issue than introducing yet another property on the global object. It's quite a subjective topic so I will appreciate more opinions here.

**Comment by NathanaelA** [comment]
That is true someone could define a global.ios on android; unless we went one step farther and created them on both platforms as false and readonly.    ;-)     Then you would have it bulletproof.  If you wanted I am willing to do a pull for that also.    
    
I actually have my own platform module (to work around a couple bugs in core modules, pulls already fix them but plugins need some backwards compatibility) myself as one of my plugins.
In that plugin I declare globally `global.nsPlatform = {ios: x, android:x, windows:x, ...}`  and then I freeze the nsPlatform object; but I am trying to eliminate dependencies on even my own plugins.     Simpler code to me is always better, less dependencies mean less things to go wrong.     I find it is way easier to write `if (global.android)` than `require('nativescript-platform'); if (global.nsPlatform.android)`  and so my platform module is only used in a couple of my plugins because it is way simpler to use the `if (global.android)` or `if (!global.android)`  vs making it a dependency and requiring it at the top of the app.     

My pref is to add `global.ios` to the ios engine, if not; I already have plenty of ways to work around it and have used most the techniques somewhere.  ;-)

**Comment by Plamen5kov** [comment]
@NathanaelA The problem can be solved by having a plugin that has two separate files `.android.js`/`.ios.js` with content: `export export const isIOS = true;` for `.ios.js` and `isAndroid` for android.
Cli will take care of putting the files wherever necessary and you can require the plugin in your code similar to what @PanayotCankov suggested: `import { isAndroid, isIOS } from "platform";`, then check the platform.
I don't see a need to introduce special properties in the runtimes, for the soul purpose of checking the platform.

>I'm well aware of platform ;-) - However bringing in platform has caused crashes at app startup in past versions of NativeScript. I haven't tested it recently (so it still might be the case), but once burned, you tend to eliminate any code you can't control.. ;-)

No need to depend on platform in this case. You can write your own plugin with 4 lines of code.

> In addition using "global.android" requires NO parsing of any additional JS code because it doesn't have to require anything, making the plugin less dependent on things especially with webpack blowing up things frequently. This also eliminates ~1000 lines of code that has to be parsed and loaded in if you don't have to require platform (and what it brings in with it -- although I do realize this code (platform) is brought in at some point by application and other calls; it is safer if people when using my plugins before application if I don't bring in anything out of sequence....

No longer a problem because you wont be requiring `platform`, but your plugin.

**Comment by NathanaelA** [comment]
@Plamen5kov - Might help if you read the ENTIRE thread before you respond, your message just re-iterates a solution I have ALREADY used in some of my plugins, and I even explained it in the message before your message.  ;-)    

Let me put this in another fashion that might be easier to understand; How many plugins do you have Plamen?   I've written around 40 of them so far for NS.   I deal with this ISSUE almost every time I create and/or work on a plugin --- do I do:

1. Add a dependency to my ns-platforms plugin, and require it.    
(Pro: Standard code, Con: extra dependency and potential issues with WebPack)
2. Cheat and do `if (global.android)` and `if (!global.android)` and figure the technical dept won't hit for a long time (if ever)
(Pro: Simple!   Con: Mythical Windows runtime  😀 ....).
3. Add: `if (global.UIDevice && global.NSString && typeof global.ios === "undefined") {	global.ios = true; 	Object.freeze(global.ios); }`  
(Pro: Simple, Con: extra code which is assuming UIDevice and NSString will both never be defined on Android)

This is one of the few feature requests that I actually have multiple ways to solve the issue; I am NOT asking for how to solve the issue; I'm asking the team to simplify `my task` as a consumer of the engine and make `global.ios` a standard fixture in the ios runtime engine, so that it is a EASY way to detect which engine I'm on without having to jump through **ANY** extra hoops.    This is a real pain point for someone developing lots of plugins, not a MAJOR pain point; but a _annoyance_ level pain point that I would love to get fixed so I no longer have to deal with it.

I have a plugin scaffolding generator that I wrote; it would be TRIVIAL for me to just add option 3 to it so that that is automatically added to all plugins that use a single JS/TS file.   But the best solution (imho) would be to add this to the engine.    Which is why I am making this request, my fallback plan is to just add option 3 to my generator and to all my existing plugins, as I think that is probably the best solution of the bunch outside of the engine change that we are discussing here.  

I am willing to do a pull request for this; but the NS team is very opinionated and I've learned it is a lot safer to ask if a pull request will be accepted than to do all the work and then have it rejected...

**Comment by NathanaelA** [comment]
Here is a prime example on how this ability on android solves my issue that just occurred two seconds ago.  (and it made me think of this issue right away) ---  I'm in the middle of tracing down a nasty bug in the Android runtimes with Pete so I have to  have `global.__enableVerboseLogging();` enabled in the main `app.js` file.   I've passed the new test android version to my clients; so now I'm testing all the my new changes on iOS now...

Guess what happened when I started the app on iOS.   BOOOOOM, iOS obviously has no `__enableVerboseLogging()` command; so it fails out immediately.   Quick and SIMPLE solution:

```
if (global.android) {
  global.__enableVerboseLogging();
}
```

And I'm done!   No mucking about at all!   No need to worry about including platforms or ns-platforms, etc, just a simple if statement and I'm working again on BOTH platforms...     And I realize  that including platforms or ns-platforms is not that much _more_ work (or annoyance); but then when you factor in when I go to delete this line of code I also have to go delete the import for platforms.   Why do I want any extra _annoyance_ factor.   Keep it simple.  ;-)   

And before we go off on a tangent -- yes I'm well aware their are other ways to skin this cat; `if (global.android)` is still way easier and faster to type than `if (global.__enableVerboseLogging)`...  ;-)

**Comment by ivanbuhov** [comment]
Summary:
1. We won't add `global.ios` because checking `if (global.ios)` is not any different than `if (global.NSObject)`. It still has the same weaknesses.
2. Currently, if you want to have platform specific code you can use the `platform` cross-platform module - `import { isAndroid, isIOS } from "platform";`. If you are not using the cross-platform modules, you can still include the following logic in your app/plugin:
```
// platform.ios.js
exports.isIOS = true;
```
```
// platform.android.js
exports.isAndroid = true;
```
```
var platform = require('./platform');
if (platform.isIOS) {
    ...
}
```
