### ISSUE TITLE
Swift didSet - using setters which utilize didSet appear to be problematic

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/ios-runtime#735]
When using a Swift 3.0 lib, Take for example:
https://github.com/audiokit/AudioKit/blob/master/AudioKit/Common/Internals/AudioKit.swift#L39-L43 shown here for convenience:

```
open static var output: AKNode? {
        didSet {
            engine.connect(output!.avAudioNode, to: engine.outputNode)
        }
    }
```

When using that setter like `AudioKit.output = anyValidNode` to any valid node will always result in immediate crash with `not a function` JS Error being logged at precisely that point of execution (just trying to use the setter). Everything else with the AudioKit api works within NativeScript except for seemingly the setters that utilize that `didSet` construct. I'm not sure if directly related to `didSet` or something else. Curious if anyone knows what this might be.

A sample project can be provided if needed.

**Comment by NathanWalker** [comment]
Here is a sample project where the above crash can be observed.
It is configured to run successfully right when you clone by using an obscure and rather hacky method to get around the above:

1. git clone https://github.com/NathanWalker/tns-audiokit.git
2. `npm run setup`
3. tns run ios --emulator

Take note of these lines:
https://github.com/NathanWalker/tns-audiokit/blob/master/app/audioplot.ts#L106-L114

You can comment/uncomment to see the crash on the setter.

**Comment by ivanbuhov** [comment]
Thank you @NathanWalker. Will take a look and will follow up with you.

**Comment by NathanWalker** [comment]
You're brilliant @ivanbuhov thank you! So it appears for Swift `didSet` constructs, the bridging header creates `set` methods for those 👍 That explains that and works!!
