### ISSUE TITLE
Consistancy on global.__collect() with android

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/ios-runtime#740]
Since 3.0 is supposed to be bringing things more consistency, between platforms, this might be too late for the 3.0 release, but I'm tossing it onto the table.  😀   

I was wonder what the thought would be to rename (or use but depreciate __collect) and use the `global.GC()` name that android is using.      Android's version is baked into the tns core modules; so that side can't really be renamed easily.   So since I don't recall seeing anything uses `__collect()` it would seem to be the more likely choice to be renamed to what the android version is using; so that both platforms have the same call that does a garbage collections.

**Comment by ivanbuhov** [comment]
@NathanaelA I like the idea of more consistent API names across both platforms and I know that we can afford to introduce some breaking changes in 3.0 but still I believe that "name consistency" is not a strong enough justification for introducing such breaking change (even if we only add `global.GC` preserving `global.__collect`).
Also, keep in mind that the following code:
```
if (global.GC) {
    global.GC();
}
```
may be found in existing apps and it is written with the intention to run GC only on Android. With the proposed change this code will trigger GC on iOS, too, and probably the app author will never notice it.

**Comment by NathanaelA** [comment]
Well, typically if I am having to manually running a GC, then it probably isn't a bad thing to do on both platforms.    

Right now you have to do:
if (global.android) { global.GC(); } else { global.__collect(); }
Seems crazy to have to force GC two different ways..   Doesn't appear to be a very consistent platform when you see things like this...   ;-)

But imho this is a minor issue for me.    I just have seen this GC issue pop up a lot in the last couple weeks in the TNS core modules; and so I figured I should make the time to post an issue to possibly finally fix it...   ;-)

**Comment by ivanbuhov** [comment]
@NathanaelA 
> Well, typically if I am having to manually running a GC, then it probably isn't a bad thing to do on both platforms.

This is often not the case. Often, the GC is triggered explicitly because of platform-specific reasons. 

However, since the benefits of the proposal are not technical but purely for developer convenience I believe that it is rather a subjective decision. My opinion is that "name consistency" is not a strong enough justification for introducing such breaking change, so I am closing the issue but if someone has different opinion or proposal - feel free to reopen it and leave a comment.
