### ISSUE TITLE
[Feature Request] Backwards 2.5 module compatibility with 3.0 runtimes.

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/ios-runtime#745]
I have not tested iOS yet, but on Android I can run the TNS Core modules 2.5 with the Android 3.0 Platform modules fine.  (See: https://github.com/NativeScript/android-runtime/issues/740) -- I would like to see if we can do the same thing with iOS and bring up the visibility to the team of trying to retain backwards compatibility for at least the short term future.   

I realize that breaking changes might be needed and if they are any that are done; can we please link to the pull request in this issue, so I can track what changes I need to do in a custom branch of the 2.5 core modules at least for several months after 3.0 is released...   

I have a real valid reason for this request and @ivanbuhov if you can contact me off-list (nathan@master-technology.com) -- I can share a private url which would make it immensely understandable the real **critical need** for this feature.

**Comment by ivanbuhov** [comment]
@NathanaelA The iOS Runtime (in its current state in master branch) is absolutely compatible with `tns-core-modules@2.5`. Additionally, we have no any planned effort for breaking this compatibility. My prediction is that in the final iOS Runtime v3.0 there won't be any breaking changes but of course I can't commit on this. Although v3.0 is a major version we are still conservative when it comes to breaking changes. Every breaking change introduction needs to be backed by valid arguments. However, if something down the road requires a breaking change to be introduced in the iOS Runtime, be sure that it will be announced publicly.

**Comment by ivanbuhov** [comment]
Here is a list of all {N} v3.0 breaking changes -> https://github.com/NativeScript/NativeScript/blob/master/Modules30Changes.md.

**Comment by NathanaelA** [comment]
Thanks @ivanbuhov - For anyone reading this later; the tns-core-modules list above are most the major changes between 2.5 and 3.x; there are other changes that are not listed.
