### ISSUE TITLE
[TNS 3.0 rc] - xcrun: error: unable to find utility "PackageApplication"

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/ios-runtime#751]
XCode 8.3 deprecated this tool however even when installing 3.0 rc and creating new project it appears it's still trying to use this. Steps to repo:

* `tns create MyApp --template tns-template-hello-world-ts@rc`
* `cd MyApp`
* Plug it an actual iPhone, `tns devices` to get it's id
* `tns run ios --device <device id>`

> xcrun: error: unable to find utility "PackageApplication", not a developer tool or in PATH

**Comment by ivanbuhov** [comment]
This issue was moved to NativeScript/nativescript-cli#2725
