### ISSUE TITLE
Switch not visible with NS 3.0 on ios

### ISSUE THREAD

**Issue by sebawita** [NativeScript/ios-runtime#764]
When I use `<Switch>` with NS 3.0, the component doesn't get rendered on iOS (it does work fine on Android though), however there seems to be an empty space where the UI component should be.
```
  <Switch
    [(ngModel)]="profile.angularPro">
  </Switch>
```

However when I use `horizontalAlignment="left"` the component appears just fine.
```
  <Switch
    [(ngModel)]="profile.angularPro"
    class="switch"
    horizontalAlignment="left">
  </Switch>
```

**Comment by ivanbuhov** [comment]
This issue was moved to NativeScript/NativeScript#4175
