### ISSUE TITLE
MetaData Generator missing items

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/ios-runtime#768]
I'm in the process of helping convert SCICharts to NativeScript and the metadata generator seems to be totally messing up on some of the header files.  

It is picking up the @interface but it is ignoring the @protocol that is assigned to the interface, so none of the protocol methods are in the meta data, which makes it very hard to use the plugin when the majority of the methods for parts of it are missing. 

As I have dived into what has been generated and what has not; I noticed that several of the items in the @protocol were using **SCIGenericType**.    This type also wasn't rendered into the meta data, and it appears anything relating to it isn't rendered into the metadata.

**SCIGenericType** is defined in the SCIGenericType.h file as:
```
typedef struct {
    /** SCIDataType information about type */
    SCIDataType type;
    union {
        /** char data. Is valid if type = SCIDataType_Byte */
        char charData;
        /** short data. Is valid if type = SCIDataType_Int16 */
        short int16Data;
        /** int data. Is valid if type = SCIDataType_Int32 */
        int int32Data;
        /** long long data. Is valid if type = SCIDataType_Int64 */
        long long int64Data;
        /** float data. Is valid if type = SCIDataType_Float */
        float floatData;
        /** double data or NSTimeInterval in seconds since 1970. Is valid if type = SCIDataType_Double or type = SCIDataType_DateTime */
        double doubleData;
        
        /** contains pointer to NSArray if type = SCIDataType_Array, or other NSObject if type = SCIDataType_Object */
        void * voidPtr;
        /** pointer to char array. Is valid if type = SCIDataType_CharPtr */
        char * charPtr;
        /** pointer to short array. Is valid if type = SCIDataType_Int16Ptr */
        short * int16Ptr;
        /** pointer to int array. Is valid if type = SCIDataType_Int32Ptr */
        int * int32Ptr;
        /** pointer to long long array. Is valid if type = SCIDataType_Int64Ptr */
        long long * int64Ptr;
        /** pointer to float array. Is valid if type = SCIDataType_FloatPtr */
        float * floatPtr;
        /** pointer to double array. Is valid if type = SCIDataType_DoublePtr */
        double * doublePtr;
    };
} SCIGenericType;
```
Is this an issue with the MetaData system that it can't use a union/struct as a valid data type?

To duplicate:
1. Create a simple empty plugin (doesn't need anything but the `platforms/ios` folder and the package.json file and then and the following `Podfile` to the platforms/ios folder.
```
source 'https://github.com/ABTSoftware/PodSpecs.git'
pod 'SciChart', '2.0.0.1437'
```

2. Then add this plugin to a new project.
3. Then build it using the metadata option.

If you check the Platforms/ios/Pods/SCICharts/Headers/ SCIDataSeries.h 
you will see `-(void) appendX:(SCIGenericType)x Y:(SCIGenericType)y;`
This is the missing method that clued me into something being wrong.  If you check the metadata generated NOTHING in the `@protocol SCIDataSeriesProtocol <NSObject>`  (line ~39) in this file is rendered into the metadata for the `@interface SCIDataSeries : NSObject <SCIDataSeriesProtocol>` (line ~273) item.   

In addition I tried manually adding the `appendX` to the @interface and it continued to ignore it, until I changed its data to `-(void) appendX:(int)x Y:(int)y;`, at that point it rendered it properly into the metadata.

I assume the majority of my issue stems from the SCIGenericType is not being rendered, which is eliminating anything else that has it as part of its meta signature.   

Is there a way to work around this?

**Comment by NathanaelA** [comment]
Doing some more research it appears this is known issue (no support for `unions`); https://docs.nativescript.org/runtimes/ios/Limitations.html.   Any idea on how to work around this?

**Comment by NathanaelA** [comment]
Is there any compile time flag `#define` that is set by NativeScript when it generates Metadata so that I can exclude the structure with the "union" and use a dummy structure object in its place.   I have manually hacked the header which allows me to proceed; but obviously the customer would prefer to be able to ship the cocoapod so it works for iOS and NativeScript...

**Comment by ivanbuhov** [comment]
@NathanaelA 
It seems that you have found the answer - the metadata generator skips unions, any structures that contain unions and any APIs that expect as a parameter or return structure that is or contains unions. This is a known limitation. The easiest workaround is to consume the desired API from native code  and expose a clean API in the JS world that doesn't expect union parameters.

**Comment by NathanaelA** [comment]
@ivanbuhov - Did you see my followup question?

Is there any `defines` that the metadata generator sets so that we can branch on the header file for NS.    If not, can we add one like `NATIVESCRIPTMETADATA` so that it is always set when doing metadata building.  This way the same header file which NEEDS the union for normal ObjC/Swift can work with NS by branching to `#ifdef` branch that will contain a non-unioned structure.  (The functions that take and create these, can still do so if the struct is proper sized, as NS doesn't actually have to do anything with the struct except pass it around)

**Comment by ivanbuhov** [comment]
@NathanaelA 
I like the idea of defining custom macro when generating metadata. It doesn't solve the case when you want to change a third-party header/library but still brings some value in cases when you have control over the header.
I made a PR for this - https://github.com/NativeScript/ios-runtime/pull/770.

**Comment by NathanaelA** [comment]
Yep, in this case they do have the control and this will be a life saver!   Thanks!

**Comment by NathanaelA** [comment]
For those who need to do this in the future the define is `__NATIVESCRIPT_METADATA_GENERATOR`

**Comment by ivanbuhov** [comment]
Fixed: https://github.com/NativeScript/ios-runtime/pull/770
