### ISSUE TITLE
Using the SFsafariviewcontroller delegate 

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/ios-runtime#772]
_From @itsjtwright on June 13, 2017 15:59_

In native script there is a delegate system for UIApplication event hooks that allow you to see when the app is opened, or when the app is closed or suspended ect. There is another delegate system that I cannot find a way to use and that is the SFsafariviewcontroller delegate, a setup that allows you to hook into events like load finished for the view controller as well as hooking into the done button. Here is a link to the apple docs on this delegate, https://developer.apple.com/documentation/safariservices/sfsafariviewcontrollerdelegate Is there any way to do something like this in nativescript?
```
class MyDelegate extends NSObject implements SFSafariViewControllerDelegate {
   public static ObjCProtocols = [SFSafariViewControllerDelegate];
    safariViewControllerDidFinish() {
        console.log('did finish');
}
```
or is the SFsafariviewcontroller delegate not apart of native script at this time?

_Copied from original issue: NativeScript/NativeScript#4373_

**Comment by ivanbuhov** [comment]
Hi @itsjtwright
`SFSafariViewController` and `SFSafariViewControllerDelegate` can be accessed in `NativeScript` as any other native Objective-C API.
Does the code example from your question work as expected? If not - what's the erroneous behavior? Do you see an error message?

**Comment by itsjtwright** [comment]
The code above just doesn't log anything, no action happens. I can only get delegate code to work with the UI delegate. Is my syntax correct or is there an issue there?

**Comment by itsjtwright** [comment]
The goal is to catch when the SFSVC ends and force orientation to vertical mode due to a bug in my app, but I just couldn't get the delegate to respond.

**Comment by ivanbuhov** [comment]
@itsjtwright 
The code above creates a new Objective-C class that extends `NSObject` and implements `SFSafariViewControllerDelegate` protocol. Since you are not instantiating the class, it is expected to have nothing happened when the code is executed.

To make it work, create an instance of your `MyDelegate` class and set it to the `delegate` property of a `SFSafariViewController` instance:
```
var viewController = SFSafariViewController.alloc().initWithURL(url);
viewController.delegate = new MyDelegate();
this.presentViewControllerAnimatedCompletion(viewController, true, null);
```

**Comment by itsjtwright** [comment]
My confusion is stemmed from this though 
```if (isIOS) {
    fontModule.ios.registerFont('ionicons.ttf');
    fontModule.ios.registerFont('fontawesome-webfont.ttf');
    fontModule.ios.registerFont('MaterialIcons-Regular.ttf');


    class MyDelegate extends UIResponder implements UIApplicationDelegate {
        public static ObjCProtocols = [UIApplicationDelegate];

        applicationDidFinishLaunchingWithOptions(application: UIApplication, launchOptions: NSDictionary): boolean {
            GoogleAnalyticsInitialize({
                trackingId: 'XX-XXXXX-XX',
                dispatchInterval: 60
            })
            return true;
        }
        applicationDidBecomeActive(application: UIApplication): void {
        console.log("applicationDidBecomeActive: " + application)
    }
    }

    application.ios.delegate = MyDelegate;
}```

This fires the applicationDidBecomeActive console.log, does the UIApplicationDelegate get special treatment or am I just confused about this whole thing? 

Also, due to a system being used that doesnt just give a url, I am using the https://github.com/bradmartin/nativescript-advanced-webview plugin for hooking into the SFSafariViewController so initWithUrl isn't an option to my understanding.

**Comment by ivanbuhov** [comment]
@itsjtwright In your example, after the definition of `MyDelegate` class it is set to `application.ios.delegate` property which will then be passed to `UIApplicationMain` by our `application` module. 

If you comment out the delegate assignment -> `application.ios.delegate = MyDelegate;` again nothing will happen. Just extending a class without using it will not have any effect.

So, to make your `SFSafariViewControllerDelegate` work, you have to give an instance of it to an existing `SFSafariViewController` object.

Let me know if this doesn't work for you?
