### ISSUE TITLE
Typescript extends does not make static properties from base available in the child object

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/ios-runtime#773]
This is not for native objects but for JS ones. So I have the following:
```ts
class Base {
   public static test = [1, 2, 3];
}
class Child extends Base {}
console.log(Child.test);
```
From what I see this is because the TS extend function here: https://github.com/NativeScript/ios-runtime/blob/master/src/NativeScript/__extends.js#L4 is not updated to the new one which also copies static properties:
```ts
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
```
Android runtime related issue: https://github.com/NativeScript/android-runtime/issues/783

**Comment by ginev** [comment]
@PeterStaev - I cannot reproduce this with the latest version of NativeScript. The snippet above works as expected both in a Android and a iOS application. Can you share more detailed instructions for reproducing the problem?

**Comment by PeterStaev** [comment]
@ginev I've just tested this on iOS and it indeed works as expected with latest TNS 👍
