### ISSUE TITLE
How to define an objective-c category in nativescript?

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/ios-runtime#775]
_From @gdtdpt on June 26, 2017 9:33_

I try to change the language setting in app runtime, but i found that it should be create a category in objective-c:
.h file
```objective-c
#import <Foundation/Foundation.h>

@interface NSBundle (Language)

+ (void)setLanguage:(NSString *)language;

@end
```
.m file
```objective-c
#import "NSBundle+Language.h"
#import <objc/runtime.h>

static const char kBundleKey = 0;

@interface BundleEx : NSBundle

@end

@implementation BundleEx

- (NSString *)localizedStringForKey:(NSString *)key value:(NSString *)value table:(NSString *)tableName
{
    NSBundle *bundle = objc_getAssociatedObject(self, &kBundleKey);
    if (bundle) {
        return [bundle localizedStringForKey:key value:value table:tableName];
    }
    else {
        return [super localizedStringForKey:key value:value table:tableName];
    }
}

@end

@implementation NSBundle (Language)

+ (void)setLanguage:(NSString *)language
{
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        object_setClass([NSBundle mainBundle],[BundleEx class]);
    });
    id value = language ? [NSBundle bundleWithPath:[[NSBundle mainBundle] pathForResource:language ofType:@"lproj"]] : nil;
    objc_setAssociatedObject([NSBundle mainBundle], &kBundleKey, value, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}

@end
```

I read the nativescript [document](http://docs.nativescript.org/angular/runtimes/ios/types/ObjC-Categories#objective-c-categories), it hasn't told me how to define a objective-c category in typescript.

Can anyone teach me how to change the above code into typescript ? 
Or Has any way to reload the current page or restart the app in iOS ?

Thanks.

- CLI: 3.0.3
- Cross-platform modules: 3.0.1
- Runtimes: tns-android: 3.0.1 & tns-ios: 3.0.1

_Copied from original issue: NativeScript/NativeScript#4454_

**Comment by ivanbuhov** [comment]
Hi @gdtdpt
You can't create an Objective-C category from JavaScript/TypeScript. If you really need a new Obj-C category I recommend [creating a NativeScript plugin](https://docs.nativescript.org/plugins/plugins#create-a-plugin). 
I am interested what is the scenario that really requires creating an Objective-C category from JavaScript? What do you want to achieve? Maybe you can achieve the same result with another approach?

**Comment by gdtdpt** [comment]
Hi @ivanbuhov 
Thanks for your answer. I want to change localization internally in nativescript application. I found a way to do this on android, then I want to find a way doing this on iOS. I search a native [way](https://github.com/maximbilan/ios_language_manager/blob/master/README.md) and I want to do the same things in nativescript.

**Comment by ivanbuhov** [comment]
@gdtdpt You can move the implementation of `+ (void)setLanguage:(NSString *)language` method in a plain JS function that expects 2 parameters: `NSBundle *bundle` and `NSString *language`.
