### ISSUE TITLE
Problems using swift framework in Nativescript

### ISSUE THREAD

**Issue by dgmaar** [NativeScript/ios-runtime#778]
Hi everyone, I'm trying to implement a library swift on my project. I create a plugin with library and I could install it without problems but when I try to call a function, javascript says that is not a function. I create another plugin with swift based on this example https://github.com/NativeScript/nativescript-cli-tests/tree/master/data/static-lib/hello-plugin and all works fine, please help me

This is a repo with my plugin and classes used https://github.com/dgmaar/pluginSwift

After install plugin, I'm able to create new SicarPushClient, but cannot call any functions

var client = new SicarPushClient();
client.connect(host);// This throws error

**Comment by ivanbuhov** [comment]
Hi @dgmaar 
Here is the [`SicarPushClient` interface](https://github.com/dgmaar/pluginSwift/blob/master/platforms/ios/PushService.framework/Headers/PushService-Swift.h#L153-L174) definition:
```
SWIFT_CLASS_NAMED("SicarPushClient")
@interface SicarPushClient : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Este es la funcion que se usa para asignar el Callback
/// ejemplo en Swift: cliente.setCallback(push: self.show);
/// \code
///  *
///
/// \endcode
- (void)setCallbackWithPush:(void (^ _Nonnull)(PushNotification * _Nonnull))push;
- (NSString * _Nonnull)getToken SWIFT_WARN_UNUSED_RESULT;
- (BOOL)connectWithIp:(NSString * _Nonnull)ip SWIFT_WARN_UNUSED_RESULT;
- (void)close;
/// Envia un objeto de PushNotification al cliente.
/// \code
///  *
///
/// \endcode
- (BOOL)sendWithNoti:(PushNotification * _Nonnull)noti SWIFT_WARN_UNUSED_RESULT;
- (void)setOnBackgroundWithRun:(BOOL)run;
- (BOOL)isOnBackground SWIFT_WARN_UNUSED_RESULT;
@end
```

It has no method called `connect`. You can try with `connectWithIp(ip)`.

**Comment by dgmaar** [comment]
Thanks! I will try

**Comment by dgmaar** [comment]
it works! thank you

**Comment by nguyenhuutinh** [comment]
hello, I have do the same as your demo project. I have a framework with object c and swift.
But when I try to check typings, **TNS_TYPESCRIPT_DECLARATIONS_PATH="$(pwd)/app/typings" tns build ios** there is no class and function in -swift.h were gerenated.
Do you have any idea?
