### ISSUE TITLE
TextBase UI components do not display as content view of UITableViewCell in {N} 3.0+

### ISSUE THREAD

**Issue by RVEIII** [NativeScript/ios-runtime#784]
I have an app where we allow the designer to modify a UITableView to display whatever {N} view they would like in the cells.  They simply write their code in typescript and give us information about where to find it.  As long as it implements the methods we need, we use it.

This worked for all {N} types we tried when we were using 2.5.  We upgraded to {N} 3.1.3 and we're seeing that all TextBase derived UI controls do not display.  They do display when we put them directly on a page.  But if we call over from native code to get the view, it displays as empty.

Here's what our ts code looks like:
```
import * as LabelModule from 'tns-core-modules/ui/label';

export class MySimpleExtension {
  public _label: LabelModule.Label;

  public view(): any {
    this._label = new LabelModule.Label();
    this._label.text = 'TESTING LABELS';
    return this._label;
  }
...
...
}
```

Here's what our native code does at cellForRow:
```
let cell = (tableView.dequeueReusableCell(withIdentifier: self.extensionReuseID))
      cell?.contentView.autoresizesSubviews = true
      if let view = sectionType.getView() {
        view.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        view.frame = (cell?.contentView.frame)!
        cell?.contentView.addSubview(view)
      }
      return cell!
```

If I switch view() to return a {N} switch control, it works fine.  If I use that view() method from a page in TypeScript code, it works fine.  It's just when I put it in a table view cell that it doesn't display the text.

**Comment by ivanbuhov** [comment]
This issue was moved to NativeScript/NativeScript#4670
