### ISSUE TITLE
Console evaluations do not work in Chrome DevTools

### ISSUE THREAD

**Issue by pkoleva** [NativeScript/ios-runtime#787]
Runtime version 
3.1.0

Steps to reproduce
1. Execute `tns debug ios --chrome`
2. Hit a breakpoint and try evaluating some expression (e.g "2=2", this.counter)

Expected result: Expression is evaluated
Actual result: nothing happens

**Comment by bundyo** [comment]
Tested and works with 3.2.0-2017-8-21-1.
