### ISSUE TITLE
Cannot call method from plugin

### ISSUE THREAD

**Issue by dgmaar** [NativeScript/ios-runtime#789]
Hi! I have problems calling a method from my plugin on iOS, this is the plugin https://github.com/dgmaar/pluginSwift. When I try to call method submitActionWithKey, I get error that method cannot be found, what I'm doing wrong?
This is how I try to call it:

client = new Client();
client.submitActionWithKey(key, callback);

**Comment by ivanbuhov** [comment]
@dgmaar There is no `submitActionWithKey` method of the [Client interface](https://github.com/dgmaar/pluginSwift/blob/master/nativescript-pushservice/platforms/ios/SocketSwift.framework/Headers/SocketSwift-Swift.h#L142-L156) that is exposed to Objective-C. You can try using [`submitActionWithKeyPush()`](https://github.com/dgmaar/pluginSwift/blob/master/nativescript-pushservice/platforms/ios/SocketSwift.framework/Headers/SocketSwift-Swift.h#L154).

**Comment by dgmaar** [comment]
thank you so much! that was the correct method
