### ISSUE TITLE
Chrome DevTools Elements Tab support

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/ios-runtime#791]
After introducing [Chrome DevTools Elements Tab support in the Android Runtime](https://github.com/NativeScript/android-runtime/issues/746) we can make it work on iOS, too. This requires implementing the DOM Agent and translate the Chrome Debugging Protocol messages to the Webkit Debug Protocol.
The logic can be implemented in the runtime or in the tns-core-modules.

**Comment by Pip3r4o** [comment]
The implementation is now part of the tns-core-modules, and will be available in the upcoming 3.3.0 release.
