### ISSUE TITLE
Runtime doesn't print the whole JS stacktrace

### ISSUE THREAD

**Issue by hshristov** [NativeScript/ios-runtime#792]
When there is an exception caused by code accessing incorrectly native APIs the runtime throws exception but with only 1 line. Instead it should print the whole JS stacktrace so developer knows which file throws the exceptions.

And that line that is currently printed is not the last line of the stacktrace but the previous :(

**Comment by ginev** [comment]
@hshristov - it seems there is an issue with `libffi` and `libunwind` on x86_64. We have logged it here: https://github.com/libffi/libffi/issues/385.

**Comment by mbektchiev** [comment]
Fixed with https://github.com/NativeScript/ios-runtime/pull/815
