### ISSUE TITLE
Unable to apply changes on device

### ISSUE THREAD

**Issue by gordingin** [NativeScript/ios-runtime#794]
I just created a new project and tried to run it in the simulator and received an error. 

Steps to create and run..

tns create new2 --ng
cd new2
tns run ios

Error....  
Searching for devices...
Executing before-liveSync hook from /Users/gordingin/test/new2/hooks/before-liveSync/nativescript-angular-sync.js
Executing before-prepare hook from /Users/gordingin/test/new2/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.4.2
Preparing project...
Unable to apply changes on device: 80C0FE16-2041-43AB-BD26-FE8003869E4A. Error is: Command failed: ruby -e "require 'xcodeproj'; Xcodeproj::Config.new('/Users/gordingin/test/new2/platforms/ios/plugins-debug.xcconfig').merge(Xcodeproj::Config.new('/Users/gordingin/test/new2/app/App_Resources/iOS/build.xcconfig')).save_as(Pathname.new('/Users/gordingin/test/new2/platforms/ios/plugins-debug.xcconfig'))"
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- xcodeproj (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
.
Executing after-watch hook from /Users/gordingin/test/new2/hooks/after-watch/nativescript-dev-typescript.js

Here are my versions of installed software....
@angular/cli: 1.4.0
node: 6.11.3
os: darwin x64
@angular/animations: 4.2.6
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/core: 4.2.6
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/platform-browser: 4.2.6
@angular/router: 4.2.6
typescript: 2.4.2
RALPHs-MBP:new2 gordingin$ tsc --version
Version 2.5.2
RALPHs-MBP:new2 gordingin$ tns --version
3.2.0
RALPHs-MBP:new2 gordingin$ 

Thank you
Ralph

**Comment by ivanbuhov** [comment]
@gordingin It seems that you don't have the [`xcodeproj` Ruby gem](https://rubygems.org/gems/xcodeproj/versions/1.4.1) installed. Run `tns doctor` to confirm if this is the problem. You can install it like this:

```
gem install xcodeproj -v 1.4.1
```

**Comment by xlcrr** [comment]
@ivanbuhov thanks for that. I had the same error. Now a new error. Progress!

To use gem I first had to exec on macos 10.12.6
$ rvm use system // now using system ruby
$ sudo gem install xcodeproj -v 1.4.1
$ tns run ios

Building project...
Xcode build...

=== BUILD TARGET MyApp OF PROJECT MyApp WITH CONFIGURATION Debug ===
No profiles for 'org.nativescript.MyApp' were found:  Xcode couldn't find a provisioning profile matching 'org.nativescript.MyApp'.
Code signing is required for product type 'Application' in SDK 'iOS 10.3'
Code signing is required for product type 'Application' in SDK 'iOS 10.3'
** BUILD FAILED **

Unable to apply changes on device: 35eede94bb00faeac9060469924d1871212a0265. Error is: Command xcodebuild failed with exit code 65.

**Comment by xlcrr** [comment]
If I add
PROVISIONING_PROFILE = testapp;
The iPhone emulator launches, but my app isn't on there.

**Comment by xlcrr** [comment]
Added
PROVISIONING_PROFILE = testapp;
Give it a minute after the emulator launched and the nativescript app appears! SWEET

**Comment by darind** [comment]
@xlcrr, the example you provided seems to be using the [`nativescript-vue`](https://nativescript-vue.org/) plugin which has recently hit the 1.0 milestone. It has a slightly different data-binding syntax from ns-core.

Here's how you could amend your sample code for this to work:

```javascript
const Vue = require("nativescript-vue");

new Vue({
  data() {
    return {
      message: "Hello Vue!"
    }
  },
  template: `
    <page>
      <stack-layout>
        <label :text="message"></label>
      </stack-layout>
    </page>
  `
}).$start();
```
