### ISSUE TITLE
Unable to embed in iOS application

### ISSUE THREAD

**Issue by n8armstrong** [NativeScript/ios-runtime#798]
What I tried:
* Installed [tns-ios](https://www.npmjs.com/package/tns-ios) v3.2.0
* Copied the `NativeScript PreBuild` run script phase from a new (`tns create HelloWorld`) NativeScript project (see below for details)
* Added the following to `Other linker flags`: `-sectcreate __DATA __TNSMetadata "$(CONFIGURATION_BUILD_DIR)/metadata-$(CURRENT_ARCH).bin"`

At this point the build fails with errors on `@import` and a few others.
![screen shot 2017-09-26 at 3 08 47 pm](https://user-images.githubusercontent.com/1187499/30884381-abeb4e62-a2cc-11e7-8d3d-36e59715b702.png)

![screen shot 2017-09-26 at 3 09 53 pm](https://user-images.githubusercontent.com/1187499/30884428-e4b98858-a2cc-11e7-8d39-534e23c7a6f1.png)

The run script looks like this:
```bash
"$SRCROOT/TeacherUITests/js/nativescript-pre-build"
```

And `nativescript-pre-build` looks like this (updated the path to map to correct location):
```bash
#!/usr/bin/env bash
set -e

pushd "$SRCROOT/TeacherUITests/js/node_modules/tns-ios/framework/internal/metadata-generator/bin"
./build-step-metadata-generator.py
popd
```

**Comment by jzilske** [comment]
I tried to embed a very simple NativScript application into an existing and rather large iOS app and am running into this also. I'm on nativescript 3.4.2 and tns-ios 3.4.1 both of which are current as of today. I see build failures during metadata generation similar to those above and those in https://github.com/NativeScript/sample-ios-embedded/issues/3 even though I'm on Xcode 9.2. What can I do to resolve this?

**Comment by tdermendjiev** [comment]
Hi, @jzilske 
When you added the metadata generation script to build phases, did you drag it up to the second location (as it is demonstrated [here](https://github.com/NativeScript/sample-ios-embedded/blob/master/HOWTO.md))?

**Comment by jzilske** [comment]
> When you added the metadata generation script to build phases, did you drag it up to the second location (as it is demonstrated here)?

Yes I did, but to no avail.

**Comment by tdermendjiev** [comment]
What is the exact error message you are getting? Thank you.

**Comment by jzilske** [comment]
> What is the exact error message you are getting? Thank you.

Thank you for trying to help, but I did manage to find a way around it. Metadata generation failed if I built RealmSwift which my app depends on in Swift 3.2 instead of 4 mode. Switching to Swift 4 resolved the issue for me.
