### ISSUE TITLE
Feature Request: Better error logging for the built in __extends

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/ios-runtime#807]
@NathanWalker and I were debugging an issue that only occurred on the iOS runtimes.  
It would give the awesome error `b.prototype` error from `__extends`
```
1   0x114ee7bf8 -[TNSRuntime executeModule:referredBy:]
2   0x10f6231e1 main
3   0x116c1665d start
4   0x1
undefined:7:68: JS ERROR TypeError: undefined is not an object (evaluating 'b.prototype')
Oct 19 17:11:01 NathanMac com.apple.CoreSimulator.SimDevice.3A54BCF4-85F7-4B94-8D6F-9C006FE91F2D[22248] (UIKitApplication:com.ugroupmedia.pnp.client.mobile[0xabfd][22270][27845]): Service exited due to Segmentation fault: 11
```

I created a custom iOS runtime with a modified __extends that looked like this
```
(function (d, b) {
try {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
} catch(e) { 
      console.log("Error:", e, e.stack); 
      throw e;
}
});
```

This allowed us to get a real stack trace.

My suggestion is that in debug mode the engine loads a `__debug_extends.js` file; and in release it loads the normal __extends.js file.  This way we can actually debug it when __extends starts throwing errors.

**Comment by NathanWalker** [comment]
This would have saved myself and the team I’m working with a full 48 hours of misery. Cannot upvote this enough. Thank you @NathanaelA again for the help with the custom runtime to allow us to get past the error which ended up being related to nativescript-angular/animations bundle.

**Comment by fealebenpae** [comment]
I believe TypeScript allows `__extends` to be overridden entirely in JavaScript by setting it on the global object before any transpiled code is loaded.

**Comment by NathanWalker** [comment]
We tried that but it didn’t work for nativescript Angular projects specifically.

**Comment by NathanaelA** [comment]
@fealebenpae - https://github.com/NativeScript/ios-runtime/blob/c949250601ca3072687512225da541f712eae903/src/NativeScript/GlobalObject.mm#L199

It is marked as ReadOnly.   My understanding is that you DO want this readonly so that things can't change it; because in the past we had issues where the internal was overwritten by an external __extends and that caused issues.

**Comment by ginev** [comment]
@NathanaelA @fealebenpae this line in `TNSRuntime.mm`:

https://github.com/NativeScript/ios-runtime/blob/32159ad8b13cd72374070cc4e0964b13c634d4d3/src/NativeScript/TNSRuntime.mm#L158

acquires the Error object that is thrown in the JavaScript world during the `__extends` execution. The following code then wraps this object into an `JSC::Exception` instance:

https://github.com/NativeScript/ios-runtime/blob/32159ad8b13cd72374070cc4e0964b13c634d4d3/src/NativeScript/TNSRuntime.mm#L166-L168

The `DoNotCaptureStack` option can be swapped for `CaptureStack` but that does not help. Digging a bit deeper, it seems that the `vm.interpreter->getStackTrace()` call in the `JSC::Exception` construction routine does not return the expected stack trace.

At this point, however: 

https://github.com/NativeScript/ios-runtime/blob/32159ad8b13cd72374070cc4e0964b13c634d4d3/src/NativeScript/TNSRuntime.mm#L166-L168

the `error` object that represents the JavaScript exception contains the stack information via the `stack` property which @NathanaelA uses in the `catch` implementation in `__extends.js` to print the stack-trace. It seems to me that it might be better to make sure this information is included into the report generated here and avoid the `console.log` in `__extends.js`:

https://github.com/NativeScript/ios-runtime/blob/32159ad8b13cd72374070cc4e0964b13c634d4d3/src/NativeScript/TNSRuntime.mm#L170

What do you think?

**Comment by NathanaelA** [comment]
@ginev - Deyan, I'm happy with whatever will spit out the log.  ;-)     At this point, no log makes it impossible to even know where to look.    Having a log is the goal of this exercise.  :grinning:

**Comment by lukeramsden** [comment]
Been working on this for 2 days now, no angular or webpack so the other solutions I found don't apply to me. @NathanaelA How exactly do I use your custom __extends? I looked at the current one and it mentions older ES versions, but I still get the error when targeting ES6. __extends.js doesn't appear anywhere in my file tree so I'm at a loss.
