### ISSUE TITLE
Retrieve value from NSDictionary type

### ISSUE THREAD

**Issue by jibon57** [NativeScript/ios-runtime#817]
Hello

I am trying to implement one Native library in NativeScript (https://github.com/hackiftekhar/IQMediaPickerController#example-usage). The native code like this:

```
@implementation ViewController
{
    NSDictionary *mediaInfo;
}

- (void)mediaPickerController:(IQMediaPickerController*)controller didFinishMediaWithInfo:(NSDictionary *)info;
{
    NSLog(@"Info: %@",info);//Here you'll get the information about captured or picked assets

    mediaInfo = [info copy];
    [self.tableView reloadData];
}
```

So, I am trying like this:

```
public mediaPickerControllerDidFinishMediaWithInfo(controller, info) {
   let mediaInfo = info.copy();
   console.log(mediaInfo);
}
```

I am getting output like this:

```
{
    IQMediaTypeImage =     (
                {
            IQMediaImage = "<UIImage: 0x608000290090> size {4288, 2848} orientation 0 scale 1.000000";
        }
    );
```

But I can’t acccess the information. Thanks in advance.

**Comment by tdermendjiev** [comment]
Hi @jibon57, if I understand correctly you are getting the proper NSDictionary by the delegate method but don't know how to access its values. According to [Apple docs](https://developer.apple.com/documentation/foundation/nsdictionary/1414347-objectforkey) you can do it by calling `dictionary.objectForKey(key)`. I had a look at the library's [repository](https://github.com/hackiftekhar/IQMediaPickerController/blob/5e56aff0f4adedd0876744ab41d7eed4607caa1a/IQMediaPickerController/IQAssetsPickerController/IQAssetsPickerController.m) and it seems like they are using the same pattern as in [UIImagePickerControllerDelegate](https://developer.apple.com/documentation/uikit/uiimagepickercontrollerdelegate?language=objc), i.e. accessing _media info_ values by using constants such as _UIImagePickerControllerOriginalImage_. That said, you should be able to access the image by calling `mediaInfo.objectForKey(IQMediaTypeImage)`.

**Comment by jibon57** [comment]
@tdermendjiev Thanks for your reply & sorry for late response. I just tried as your suggestion like this:

```
public mediaPickerControllerDidFinishMediaWithInfo(controller, info){
            let mediaInfo = info.copy();
            let data = mediaInfo.objectForKey(IQMediaTypeImage)
            console.log(data);
        }
```
Output:

`CONSOLE LOG file:///app/tns_modules/nativescript-filepicker/filepicker.js:19:20: (`

It's null output. Any idea, in where I am doing mistake.

Thanks

**Comment by tdermendjiev** [comment]
@jibon57 `mediaInfo.valueForKey(IQMediaTypeImage)` should work then.

**Comment by jibon57** [comment]
@tdermendjiev Thanks again for reply. From me the result is same :( .. Will you please share your working code here?

**Comment by jibon57** [comment]
@tdermendjiev Thanks for your reply. I tried like bellow:

```
public mediaPickerControllerDidFinishMediaWithInfo(controller, info){
            let mediaInfo = info.copy();
            let data = mediaInfo.valueForKey(IQMediaTypeImage);
            console.log(data); 
        }
```
but same output:

`CONSOLE LOG file:///app/tns_modules/nativescript-filepicker/filepicker.js:19:20: (`

Will you please share your working code?

Thanks

**Comment by tdermendjiev** [comment]
@jibon57 it appears that it's a [nativescript-cli related issue](https://github.com/NativeScript/nativescript-cli/issues/3105) with printing multiline console logs which we are currently working on. If you run the project from XCode you will be able to see the full logs and respectively the proper ones. Here is the code of the ViewController I used to reproduce the issue:

````
class RootViewController extends UIViewController implements IQMediaPickerControllerDelegate {
	public static ObjCProtocols = [IQMediaPickerControllerDelegate];

	viewDidLoad() {
		console.log("Root loaded");
	}

	viewDidAppear() {
		let controller = IQMediaPickerController.alloc().init();
		controller.delegate = this;
		this.presentViewControllerAnimatedCompletion(controller, true, null);
	}

	mediaPickerControllerDidFinishMediaWithInfo(controller, info) {
		console.log(info.valueForKey("IQMediaTypeImage"));
	}

	mediaPickerControllerDidCancel(controller){
		console.log("Media picker canceled");
	}
}
````

How were you able to print the whole NSDictionary output from your first comment - by running from XCode or from the CLI?

**Comment by jibon57** [comment]
@tdermendjiev Thank you so much !!! I thought my code has some problem that's why the output was null. I got the output of my first comment was from an older version of NativeScript. In XCode I am getting the complete output now. Now another questions... Can I use the value of `IQMediaImage` directly to show in view or uploading to remote server? Or how can I reuse that for view or upload?

**Comment by tdermendjiev** [comment]
@jibon57 you can use the `IQMediaImage` value pretty much the same way you would use `UIImage` in a native function. For image uploading you can refer to [this one](https://stackoverflow.com/questions/39334643/how-to-upload-file-using-multipart-form-data-in-nativescript). In case you are now able to properly print the desired values I will close this issue. If you have issues unrelated to the current, please open a new one.

**Comment by jibon57** [comment]
@tdermendjiev Thanks for your reply. Will you please give some hints to use the value of `IQMediaImage`? For example if I want to display the image in view.

**Comment by tdermendjiev** [comment]
In iOS the `UIImageView` class is used for images to be displayed. Let's say you have the instance variable`imageView`(UIImageView instance) and the `IQMediaImage` value assigned to the variable `iqMediaImage`(UIImage instance). The you set the imageView's image just like: ``imageView.image = iqMediaImage``.
