### ISSUE TITLE
Incorrrect module path resolution

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/ios-runtime#822]
Related to [this issue](https://github.com/NativeScript/android-runtime/issues/334) which was resolved in android-runtime. Also logged and discussed [here](https://github.com/NativeScript/NativeScript/issues/3501#issuecomment-343457582)

Steps to reproduce:
- use [this test application](https://github.com/NickIliev/NS-Issues/tree/master/NativeScript/issue_3501_new)
- without any modification, the `moment` library would work on Android and will not work on iOS.
using[ this "hack"](https://github.com/NativeScript/NativeScript/issues/3501#issuecomment-343456812) will also resolve the issue for iOS.

Milestone: Correct the module path resolution for iOS as it works in Android.

**Comment by etabakov** [comment]
Closing this issue as resolved.
