### ISSUE TITLE
Error when trying to build NativeScript target

### ISSUE THREAD

**Issue by surdu** [NativeScript/ios-runtime#828]
I'm trying to debug our app's ios-runtime error following [the tutorial from the docs](https://docs.nativescript.org/runtimes/ios/how-to/debug-ios-runtime) but when I try to [build the 
NativeScript target for the ios-runtime](https://docs.nativescript.org/runtimes/ios/how-to/debug-ios-runtime#3-build-the-nativescriptxcodeproj-nativescript-target) I get the following error:

```
PhaseScriptExecution CMake\ Rules cmake-build/NativeScript.build/Debug-iphoneos/libffi.build/Script-21C4144A2026427486AF6FBE.sh
    cd /Users/nicolae.surdu/work/ios-runtime
    /bin/sh -c /Users/nicolae.surdu/work/ios-runtime/cmake-build/NativeScript.build/Debug-iphoneos/libffi.build/Script-21C4144A2026427486AF6FBE.sh

echo ""

cd /Users/nicolae.surdu/work/ios-runtime/src/libffi && /Users/nicolae.surdu/work/ios-runtime/build/scripts/build-step-libffi.sh
+ for CURRENT_ARCH in '$ARCHS'
+ build armv7
+ local ARCH=armv7
+ local BINARY_DIR=build_iphoneos-armv7-Debug
+ '[' -f build_iphoneos-armv7-Debug/.libs/libffi.a ']'
+ local TRIPLE
+ '[' armv7 == i386 ']'
+ '[' armv7 == x86_64 ']'
+ '[' armv7 == armv7 ']'
+ TRIPLE=arm-apple-darwin11
+ autoreconf -i
autoreconf: 'configure.ac' or 'configure.in' is required
make: *** [/Users/nicolae.surdu/work/ios-runtime/cmake-build/CMakeFiles/libffi] Error 1
Command /bin/sh failed with exit code 2
```

**Versions**
 - MacOs Sierra **v10.12.6 (16G29)**
 - XCode **v9.1 (9B55)**

**Comment by tdermendjiev** [comment]
Hi @surdu, were you able to build successfully any of the targets in the ios-runtime project following the instructions in the repo's [README](https://github.com/NativeScript/ios-runtime)?

**Comment by surdu** [comment]
@tdermendjiev
Based on your suggestion I've realized that I needed to use `--recursive` when cloning the repo, so this solved my initial problem, but now I get this error:

```
dyld: Symbol not found: _utimensat
  Referenced from: /usr/local/bin/cmake
  Expected in: /usr/lib/libSystem.B.dylib

/bin/sh: line 1: 87967 Abort trap: 6           /usr/local/bin/cmake -E touch_nocreate /Users/nicolae.surdu/work/ios-runtime/cmake-build/WebKit-prefix/src/WebKit-build/DerivedSources/JavaScriptCore/LLIntAssembly.h
make[1]: *** [/Users/nicolae.surdu/work/ios-runtime/cmake-build/WebKit-prefix/src/WebKit-build/DerivedSources/JavaScriptCore/LLIntAssembly.h] Error 134
Command /bin/sh failed with exit code 2

** BUILD FAILED **
```

**Comment by tdermendjiev** [comment]
@surdu what I am trying to figure out is whether you are having issues building the ios-runtime in general or just building it as a dynamic lib for the CLI project. Did you follow the instructions [here](https://github.com/NativeScript/ios-runtime) and manage to build any of the Nativescript.xcodeproj targets?

**Comment by surdu** [comment]
@tdermendjiev Ok, so this is really odd and annoying: 

If I follow any of the two scenario, dynamic (from the tutorial) or not (from the readme), and do a clean before the build, sometimes it works, but most of the times fails with the last mentioned error.

If it worked, then if I do a clean and try again, it starts failing again.

I have now a build that worked for the dynamic build that I will not touch and will continue with the tutorial and see how that goes.

It would be nice if anybody can help me to understand what's going on and make the build work every time, as the current situation is not sustainable.

**Comment by tdermendjiev** [comment]
@surdu What is your cmake version and how did you install it? Would you be able to try with [this one](https://cmake.org/files/v3.3/cmake-3.3.2-Darwin-x86_64.dmg)?

**Comment by surdu** [comment]
@tdermendjiev YES! That was the problem. I was having v3.1.3 (as per the docs) but upgrading to v3.3.2 fixed this issue.
