### ISSUE TITLE
 Lost databinding context after app resume

### ISSUE THREAD

**Issue by priyangamani** [NativeScript/ios-runtime#846]
After App Resume the data binding context is not working.how to resolve the issues by using same page event.

**Comment by tdermendjiev** [comment]
Hello @priyangamani, would you be able to provide more detailed info on the issue? Thank you.

**Comment by priyangamani** [comment]
In application on resume stage i need to bind the text value in Label tag.But i cannot bind the value,during application.on resume event.So, How can i pass the data or set the text value during app resume stage.
(Binding Context is not working)..
 
please see my below code..

var Observable = require("data/observable").Observable;
var app = require("application");

JS://
app.on(app.resumeEvent, function (args) {
    console.log("Barcode Resumeevent");
    pageData.set("text", "1234");
    pageData.set("enable", "true");
    page.bindingContext = pageData;
});

XML://
<GridLayout   visibility="{{ enable=='true'  ? 'visible' : 'collapsed' }}" >
<Label row="0" text="{{ text }}"  horizontalAlignment="center" verticalAlignment="bottom"  />
</GridLayout>

**Comment by priyangamani** [comment]
By using Application on resume event i need to set the text value in xml(data-Binding context).But data-binding context is not working during resumeEvent. So,how can i need to set the text value by using resumeEvent.

please check my below code...

//Js

var app = require("application");
var Observable = require("data/observable").Observable;
/*****************************
* resumeEvent
******************************/
app.on(app.resumeEvent, function (args) {
    console.log("Barcode Resumeevent");
    pageData.set("text", "1234");
    page.bindingContext = pageData;
});

//XML

```
<GridLayout   visibility="{{ enable=='true'  ? 'visible' : 'collapsed' }}" >
<Label row="0" text="{{ text }}"  horizontalAlignment="center" verticalAlignment="bottom"  />
</GridLayout>
``` @tdermendjiev

**Comment by NickIliev** [comment]
@priyangamani thank you for your interest in NativeScript.

Regarding your question - you should persist your data (e.g. using [application-settings](https://docs.nativescript.org/cookbook/application-settings) module) and write them to your Observable model when you are creating it.

The issue you are dealing with is a how-to concept not related to iOS runtime code.
Please, note that this repository is for logging issues, bugs and features related to iOS runtime.
For how-to related questions please use the community channels like [the NativeScript forum](https://discourse.nativescript.org/), [the NativeScript community channel](https://nativescriptcommunity.slack.com/messages/general) or [SO](https://stackoverflow.com/questions/tagged/nativescript).
