### ISSUE TITLE
Crash screen not shown

### ISSUE THREAD

**Issue by surdu** [NativeScript/ios-runtime#880]
I have a simple code that when I press a button it throw a JS error. 

On iOS only, the app crashes without displaying the gray crash screen that shows the stack trace.

Maybe it's related to #792 ?

**Comment by NickIliev** [comment]
@surdu please post the involved code and the thrown error

**Comment by surdu** [comment]
Sorry, I wasn't clear enough: I intentionally crash the app by throwing an error. 

The problem is that the app exits on iOS instead of seeing the NativeScript gray exception screen that show the error stack trace (sorry, I don't know the actual name of that screen).

**Comment by surdu** [comment]
In the default hello world NativeScript application, in the `main-view-model.js`, change the tap handling for the counter button to be this:

```
    viewModel.onTap = function() {
        throw new Error("This be an error");
    }
```

When you'll tap the button, on android you'll correctly see this screen due to the error:
<img width="342" alt="screen shot 2018-02-14 at 16 27 50" src="https://user-images.githubusercontent.com/11520795/36209297-0b2adaa0-11a4-11e8-9a85-8584a9b4eb0d.png">

But on iOS, the app just crashes and exits.

**Comment by NickIliev** [comment]
@surdu thanks for the clarification!
The thing is that the graying screen is enabled for Android only when we are creating Android Error activity to visualize the error in the JavaScript stack trace and in the Android Logcat.
For iOS, this approach is not possible and we have never supported Error screen on iOS.
Still the whole info from the error is printed in your terminal. For more verbose logs you can even call
````
tns run ios --log trace
```
