### ISSUE TITLE
Chrome DevTools  console evaluation doesn't work with `tns debug --start` 

### ISSUE THREAD

**Issue by Natalia-Hristova** [NativeScript/ios-runtime#905]
### If there is no issue for your problem, tell us about it
When  debugging ios and try to use Chrome DevTools console evaluation, the expression you type is deleted and not executed on pressing "Enter". The same works if you `tns debug ios` without the `--start` option 

### Please, provide the following version numbers that your issue occurs with:

- CLI: `4.0.0-2018-04-05-11381`
- Runtime(s): 
```
"tns-ios": {
	"version": "4.0.1-rc-2018-04-05-01"
}
```
### Please, tell us how to recreate the issue in as much detail as possible. 
1. `tns run ios` some app on simulator
2. `tns debug ios --start`
3. Open the url in Chrome
4. Go to the Chrome DevTools console tab and write e.g. `2+2`

or start debugging with `tns debug ios --inspector --start`

[Here's](https://www.screencast.com/t/s6zpfvSTs9Rf) a video of the issue.

**Comment by dunjunliu** [comment]
1) ios-runtime seems can only be used on Safri if i want use console tab;
2) devtools used different protocol for console;
