### ISSUE TITLE
feature: Enable app Podfile

### ISSUE THREAD

**Issue by DickSmith** [NativeScript/ios-runtime#939]
Sometimes a project just needs to add a `Podfile` without any JS/TS, but a full plugin must be created:
1. https://github.com/tjvantoll/nativescript-IQKeyboardManager (Until recently was only a podfile)
0. https://github.com/Essent/nativescript-disable-bitcode (just a postinstall to strip all bitcode from a project).

Additionally, this is where a project should be able to set its platform version level, as well. (and plugin Podfiles should not).

In many ways this is similar to many of the settings and package management actions that can be taken in `app.gradle` (dependencies not requiring JS, package overrides, and min platform).

Would likely just come from `App_Resources` like similar files.

**Comment by NickIliev** [comment]
+1 From slack conversation with a client

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3807
