### ISSUE TITLE
3rd party static libraries: Integrate Cocoapods with the CLI Plugins Mechanism

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#94]
This will require us to support build from the Xcode workspace the cocoapods generate.

We will have to somehow generate metadata for the cocoapods. The best solution would be to generate module maps from the podspecs.

We will have to reasearch what part of the cocoa apis can we consume (e.g there may be C apis that get stripped during the linking, although cocoapods add -ObjC flag)

[Later this issue will probably be integrated with the NPM plugins mechanism, and allow pods to be specified in the package.json or a podfile in a plugin](https://github.com/NativeScript/nativescript-cli/issues/362).

**Comment by jasssonpet** [comment]
Moved to: https://github.com/NativeScript/nativescript-cli/issues/729
