### ISSUE TITLE
Disable swipe back  using enableSwipeBackNavigation  doesn't work

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/ios-runtime#956]
I've created a new simple plain empty project : 

`tns create aaa --ng`

In the ctor of the items component , I did exactly what [this post suggests](https://discourse.nativescript.org/t/disabling-swipe-gestures-in-ios-preventing-navigation-back/3169/3)

```
constructor(private page: Page) {
        this.page.enableSwipeBackNavigation = false;
}
```

But the suggested code (also [in here](https://github.com/NativeScript/NativeScript/issues/3075) by @tsonevn ) - doesn't work in the latest version.

As you can see : I'm still able to drag the window : 

<img width="361" alt="screen shot 2018-07-18 at 23 31 56" src="https://user-images.githubusercontent.com/2842123/42907324-1e3ce118-8ae6-11e8-8747-de3f7996dad0.png">

It happens in emulator and also on a real device.
(nativescript 4.1)

Attached sample project : https://ufile.io/umni8

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/NativeScript#6091
