### ISSUE TITLE
Introduce a setting for discarding uncaught exceptions from called JS methods

### ISSUE THREAD

**Issue by mbektchiev** [NativeScript/ios-runtime#965]
We need a setting to enable and disable catching exceptions when calling JS methods from the runtime. If enabled, those exceptions will be caught and logged without propagating them.
The default value of the setting is `false`. If such an error occurs it will be thrown as an Objective C exception and if it remains unhandled, will crash the application.

If you want to enable it you should add the following in your app/package.json file this:

```JavaScript
{
	...
	"discardUncaughtJsExceptions": true
}
```
Analogous to https://github.com/NativeScript/android-runtime/issues/1119

**Comment by Natalia-Hristova** [comment]
This feature is implemented and will be available in `tns-ios 4.2.0`
