### ISSUE TITLE
when i build new release in xcode i am getting errors 

### ISSUE THREAD

**Issue by hariaravind10** [NativeScript/ios-runtime#968]
My package.json file

{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "***.******.****",
    "tns-android": {
      "version": "4.1.3"
    },
    "tns-ios": {
      "version": "4.1.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "email-validator": "^2.0.3",
    "nativescript-angular": "^5.3.0",
    "nativescript-camera": "^4.0.2",
    "nativescript-gradient": "^2.0.1",
    "nativescript-plugin-firebase": "^6.4.1",
    "nativescript-social-share": "^1.5.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-calendar": "^3.6.1",
    "nativescript-ui-chart": "^3.6.1",
    "nativescript-ui-listview": "^3.5.0",
    "nativescript-ui-sidedrawer": "^4.0.0",
    "node-sass": "^4.9.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.5.2",
    "tns-core-modules": "^4.2.0-2018-07-05-01",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~6.1.0-rc.0",
    "@ngtools/webpack": "~6.1.0-rc.2",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.7.1",
    "nativescript-dev-webpack": "^0.15.0",
    "typescript": "~2.7.2"
  }
}```
PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/user/Library/Developer/Xcode/DerivedData/client-cpytipjuelwjgdbcblyjcsavgeho/Build/Intermediates.noindex/client.build/Debug-iphoneos/client.build/Script-63E7CBC5939EE7A03003558A.sh
    cd /Users/user/Desktop/Aravind/HARI/dkavihari0.3/srs/client/platforms/ios
    /bin/sh -c /Users/user/Library/Developer/Xcode/DerivedData/client-cpytipjuelwjgdbcblyjcsavgeho/Build/Intermediates.noindex/client.build/Debug-iphoneos/client.build/Script-63E7CBC5939EE7A03003558A.sh

diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

**Comment by NickIliev** [comment]
Please provide the needed information so we could investigate the issue 

```
### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.
```
