### ISSUE TITLE
Live-sync in the CLI

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#97]
We need something like a file watcher in the CLI that upon file save will perform fast deploy on the device.

We should check whether a regular "tns run ios" fits in decent times with the latest metadata generator and library improvements. If the delay is small we should simply hook a file watcher.

If the build time is not acceptable we should research how to deliver the changes to the phone and restart the app fast.

**Comment by ligaz** [comment]
Shouldn't this issue be part of the NativeScript CLI repo? 

_Note: There is already existing LiveSync infrastructure (including watching) that we can borrow from AppBuilder CLI._

**Comment by PanayotCankov** [comment]
The build times, along with eventual infrastructure that will be placed in the "tns-ios" project template belong here.

**Comment by devangpaliwal** [comment]
It should be very similar to react-native's cmd+r feature. 

RN wins in this department.

**Comment by emmanuelbuah** [comment]
+1. Borrow from RN if possible. RN is already looking at nativescript for package/module management. It only make sense to learn form each other.

**Comment by NathanaelA** [comment]
@PanayotCankov did you see my http://github.com/NathanaelA/NativeScript-LiveSync plugin -- it is currently only Android; but their is no reason it shouldn't work just as well on a IOS device other than I'm not as familiar on the IOS platform.    It allows _instant_ syncs for css, js & xml files, without restart of application.     Which makes developing pretty darn awesome if you have a emulator up and running your project on the same box you are developing on...

**Comment by PanayotCankov** [comment]
@Nathanaela, your plugin literally generated an euphoria in the NativeScript team. However the cordova tools that Telerik develops already has some code dealing with live-sync and since our CLI is literally rip off their CLI, the live-sync feature was hand-over to them, they will back-port some code to enable it for the {N}.

After all who does not like free piggy-back ride.

Here you can see details of the live-sync in the {N} CLI: https://github.com/NativeScript/nativescript-cli/issues/523 It should be live in v1.2.0 which will come quite soon.

I would suggest you post requirements and suggestions there.

**Comment by PanayotCankov** [comment]
This is now a property of the CLI.
