### ISSUE TITLE
Allow embedders to have a reference to the embedded NS app viewcontroller

### ISSUE THREAD

**Issue by tdermendjiev** [NativeScript/ios-runtime#972]
Currently embedded app is always presented modally on top of the rootViewController without the embedder having any control over it's UIViewController and it's way of presentation (push, modal present etc.). We need to keep a reference to it.

**Comment by tdermendjiev** [comment]
Implemented by #945

**Comment by Natalia-Hristova** [comment]
This issue was moved to NativeScript/NativeScript#6173
