### ISSUE TITLE
Reading collisionBoundingPath on UIView results in Objective C exception

### ISSUE THREAD

**Issue by MartoYankov** [NativeScript/ios-runtime#978]
### If there is no issue for your problem, tell us about it
collisionBoundingPath is an optional property and might not have a setter/getter. Visual Studio Code debugger tries to read all properties of a native object and tries to call it resulting in exception `(CoreFoundation) -[UIScrollView collisionBoundingPath]: unrecognized selector sent to instance 0x7fb0ca8cea00`. This currently breaks the app and debugging stops. Connected to https://github.com/NativeScript/nativescript-vscode-extension/issues/198.31

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.2.0
- Cross-platform modules: 4.2.0
- Runtime(s): 4.2.0

### Please, tell us how to recreate the issue in as much detail as possible. 
Debug an app and hover over any variable/property that holds a native object.

### Is there any code involved? 
[my-blank-ts.zip](https://github.com/NativeScript/ios-runtime/files/2286882/my-blank-ts.zip)

1. Start the app with VS Code debug
2. Set a breakpoint in app/home.1/home-page.ts line 17
3. Tap on `Navigate to Second`
4. Once the breakpoint hits, hover over the `native` variable.

**Comment by Natalia-Hristova** [comment]
Fixed in `tns-ios` **next** version -> `v4.3.0-2018-09-19-01`
