### ISSUE TITLE
libffi cannot handle double3, double4, SCNVector3 function parameters

### ISSUE THREAD

**Issue by tdermendjiev** [NativeScript/ios-runtime#979]
It appears that double3 and double4 vectors are not passed the same way  as other vectors to functions. While float2, float3, float4 and double2 vectors are being found in the xmm registers when the callee function executes when we pass double3 and double4 xmm0 and xmm1 contain invalid values.

**Update:** Parameters of type SCNVector3 are not passed properly as well. **The rest of the SCNVectors should also be tested as well as the existing (in Testrunner) structs as parameters.**

**Comment by NathanaelA** [comment]
Hey, is there a PR making a note of this limitation in the documentation.   Shouldn't this be clearly documented so that others don't waste a lot of time since this is now a known limitation currently

**Comment by NathanaelA** [comment]
One more note; the change log has this "bug" as fixed in 5.1.0; that is very misleading as this is not fixed as far as I can tell.   Might want to fix that.

**Comment by mbektchiev** [comment]
There's no limitation right now. The  `double3, double4, SCNVector3` vectors are now fully supported. The fix is merged with the PRs related with this issue #997

**Comment by mbektchiev** [comment]
@NathanaelA It seems you're right and currently the vector tests crash on i386 and armv7 architectures. 

We'll attempt to fix them or note the limitation in the documentation. Thank you for bringing up the problem and sorry for the misleading.

**Comment by mbektchiev** [comment]
It turns out that libffi currently can't support SIMD vector parameters and return values out of the box for the `armv7` and `i386` architectures. It's outside of the scope of tasks of our team to fix it and we'll make sure to properly document this limitation. 

As a workaround developers that need to support 32-bit architectures can write native wrappers in plugins.
