### ISSUE TITLE
Performance Optimizations Based on TelerikNEXT Conference App

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#98]
Try to squeeze as much as possible out of the TelerikNEXT Conference App. The application is close to the target LOB style applications we target. It has rich UI with lot of CSS styles and layout.

We should maximize the frame-rates, minimize CPU utilization, allocations, memory usage, frame-rate spikes/hiccups.

We should provide report on time spent in GC, JSC JavaScript or native code as well as memory spent for JavaScript heap and native allocations.

**Comment by PanayotCankov** [comment]
We've done some profiling. On excessive scrolling we generate NSStrings for the JavaScript strings, and we can optimize some of that sort of marshaling.

In addition the cells generate new font descriptors, while they can be recycled so there are some areas for improvement in the NativeScript modules.

Further the list view is shared between the 3 sources (conference days) and it used to cache the cell heights. Moving from one day to the next will cause the list view to assume wrong cell heights and appear jumping. This however is problem in the app implementation.

We will resume effort here once we implement the performance profiling in the WebInspector and the NativeScript for iOS.

**Comment by ligaz** [comment]
Can you check the fake group header as well? It seems that it is causing the perceived slowness while scrolling the list view.
