### ISSUE TITLE
Accessing an iOS methods (same name different params) in an external iOS library

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/ios-runtime#983]
_From @demetrio812 on August 31, 2018 12:40_

Hello,
I'm writing a plugin to use a stomp library written in iOS (https://github.com/WrathChaos/StompClientLib).

Beside the initial compilation problems (solved forcing the swift version to 3) I have a problem accessing a specific method of the class `StompClientLib`: `openSocketWithURLRequest`

Debugging the app with VS Code and accessing the element in javascript, I can see all the other methods, the only one is missing is `openSocketWithURLRequest`.

Is it because there are 2 methods with the same name but different parameters?

```swift
    public func openSocketWithURLRequest(request: NSURLRequest, delegate: StompClientLibDelegate) {
        self.delegate = delegate
        self.urlRequest = request
        // Opening the socket
        openSocket()
    }
    
    public func openSocketWithURLRequest(request: NSURLRequest, delegate: StompClientLibDelegate, connectionHeaders: [String: String]?) {
        self.connectionHeaders = connectionHeaders
        openSocketWithURLRequest(request: request, delegate: delegate)
        self.connection = true
    }
```

How can I access them from Typescript?

I've checked the documentation and forums but didn't find anything...

Thanks,
Dem

_Copied from original issue: NativeScript/NativeScript#6231_

**Comment by demetrio812** [comment]
Hello again,
I've forked (https://github.com/demetrio812/StompClientLib) the iOS library and changed the name plus added other methods and made public the simple method `public func openSocket()` but unfortunately it keep not finding any of them, so at this point I don't think it's the same name the problem, but I don't know why these specific methods aren't picked but all the others (i.e. `public func disconnect()`) are...

Any hint?

Cheers,
Dem

**Comment by demetrio812** [comment]
Hello @aaayushsingh, thanks for replying, I've checked the rules, actually should your example have an extra `With`? like `commitWithTransactionId`?

However methods without params shouldn't have problems anyway (that's why I've made openSocket public for testing).

Actually I was wrong about `disconnect`, I've confused it with another one in the super class, I cannot see any methods except for:

<img width="320" alt="screenshot 2018-09-01 11 59 30" src="https://user-images.githubusercontent.com/385644/44945354-837b2c80-addf-11e8-89e8-56776b0af3c9.png">

Any idea?

Here the example project I'm using: https://www.dropbox.com/s/gs5qcrq8se6juye/nativescript-stomp-client.zip?dl=0

I'm stuck at the moment

Thanks,
Dem

**Comment by demetrio812** [comment]
I've also just tried with another very similar pod: `EIDAKStompClient`

It's basically the same swift class, is it possible that the problem is related to the fact that they aren't written in Objective-C?

Dem

**Comment by aaayushsingh** [comment]
@demetrio812 The extra `With` isn't added, only function parameters. I thought you were able to call `disconnect()`. Then my solution would probably have worked but I guess we are in the same boat. I have a related issue #984.

**Comment by demetrio812** [comment]
anything from the NS team? @NickIliev ? I'm starting to get worried that I cannot use all the native libraries in NS, hopefully I'm wrong

**Comment by demetrio812** [comment]
@aaayushsingh I've solved the problem thanks to triniwiz (in the slack plugins channel):

I had to use @objc to expose the methods to objective-c (with Swift 4 they aren't automatically exposed anymore), I've also user @objcMembers for the main class.

This is what I did in my fork (ignore the other commits as they were all tests):

<img width="989" alt="screenshot 2018-09-04 01 07 01" src="https://user-images.githubusercontent.com/385644/45003947-c0ae0d00-afdf-11e8-84ce-8f5eb874ff55.png">

Hope this can help, @NickIliev is there any plan to work directly with the swift library, without having to fork it?

Cheers,
Dem

**Comment by NickIliev** [comment]
@demetrio812 the Swift supported is logged [here ](https://github.com/NativeScript/ios-runtime/issues/257)but is not a priority at this very moment.

You can still convert Swift pods to Obj-C using [this solution](https://github.com/NativeScript/ios-runtime/issues/257#issuecomment-299774584)

**Comment by demetrio812** [comment]
Hello @NickIliev thanks for replying, with swift 4.1 I think this should start being important, setting the swift language to 3 may work now but it's not going to work forever

Thanks again!

**Comment by mbektchiev** [comment]
@demetrio812 I found an alternative approach which will not require changing the Swift version back to 3.0. 

There's another configuration variable which will only bring back the old behavior of automatically exposing all methods to ObjectiveC. It's called `SWIFT_SWIFT3_OBJC_INFERENCE`.

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

Here's the great blog post that I learnt about it from: https://www.runtastic.com/blog/en/swift-4-migration/

**Comment by demetrio812** [comment]
@mbektchiev that's very good to know I'll test it!! Thanks!
