### ISSUE TITLE
Build containing @next rejected by Apple:

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/ios-runtime#991]
_From @abhayastudios on September 16, 2018 18:28_

### Tell us about the problem

Build containing @next rejected by Apple:

>We identified one or more issues with a recent delivery for your app, "MyApp". Please correct the following issues, then upload again.
>
>Non-public API usage:
>
>- The app references non-public symbols in Frameworks/NativeScript.framework/NativeScript: _CCRandomCopyBytes, _kCCRandomDefault
>
>If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
```
$ tns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 4.2.3 version and is up to date.
✔ Component tns-core-modules has 4.3.0-2018-09-14-01 version and is up to date.
✔ Component tns-android has 4.2.0 version and is up to date.
✔ Component tns-ios has 4.3.0-2018-09-13-01 version and is up to date.
```

_Copied from original issue: NativeScript/NativeScript#6272_

**Comment by mbektchiev** [comment]
@abhayastudios Version `4.3.0-2018-09-18-01` is published as `@next` in NPM and should resolve the issue. Feel free to give it a try.

**Comment by abhayastudios** [comment]
@mbektchiev I can confirm this is working now! Thanks a lot for the fast solution.
